import type { ResolvedLiveOverlayScene } from "./live-overlay";

export type OverlayReceiveFailure = "network" | "non_2xx" | "timeout" | "malformed_json" | "unexpected_scene" | "aborted";
export type OverlayTransportState = { scene: ResolvedLiveOverlayScene; connected: boolean; held: boolean; failureReason: OverlayReceiveFailure | null; generation: number };

const MODES = new Set(["standby", "now_playing", "artist_card", "wheel_ready", "wheel_reencrypting", "wheel_spinning", "wheel_result", "wheel_confirmed", "sponsor", "video_placeholder", "system_message", "session_active"]);
function str(v: unknown): v is string { return typeof v === "string" && v.trim().length > 0; }
function finite(v: unknown): v is number { return typeof v === "number" && Number.isFinite(v); }
function iso(v: unknown): v is string { return str(v) && Number.isFinite(Date.parse(v)); }
function trackOk(track: unknown): boolean { const t = track as Record<string, unknown> | null; return Boolean(t && str(t.artistName) && str(t.trackTitle) && (t.durationLabel == null || typeof t.durationLabel === "string") && (t.sourceType == null || typeof t.sourceType === "string")); }
function syncOk(sync: unknown, provider: "youtube" | "tiktok"): boolean { const s = sync as Record<string, unknown> | null; if (!s || s.provider !== provider) return false; const identity = provider === "youtube" ? str(s.videoId) : str(s.postId); return Boolean(identity && str(s.trackId) && ["playing", "paused", "stopped"].includes(String(s.playbackState)) && finite(s.currentTimeSeconds) && iso(s.hostUpdatedAt) && typeof s.muted === "boolean" && (s.durationSeconds == null || finite(s.durationSeconds))); }
function candidateOk(candidate: unknown): boolean { const c = candidate as Record<string, unknown> | null; return Boolean(c && str(c.id) && str(c.artistName) && str(c.trackTitle) && finite(c.weight) && (c.tracks == null || (Array.isArray(c.tracks) && c.tracks.every(candidateOk)))); }
function wheelOk(wheel: unknown): boolean { const w = wheel as Record<string, unknown> | null; if (!w) return true; if (!["idle", "ready", "reencrypting", "spinning", "result_pending", "confirmed", "signal_lost"].includes(String(w.status))) return false; if (!Array.isArray(w.displayCandidates) || !w.displayCandidates.every(candidateOk)) return false; if (w.resultTrack != null && !candidateOk(w.resultTrack)) return false; for (const key of ["finalRotationDeg", "landingAngleDeg", "spinDurationMs"]) if (w[key] != null && !finite(w[key])) return false; return true; }
export function isResolvedLiveOverlayScene(value: unknown): value is ResolvedLiveOverlayScene { const s = value as Partial<ResolvedLiveOverlayScene> | null; if (!s || typeof s !== "object") return false; if (!MODES.has(String(s.mode)) || !MODES.has(String(s.resolvedMode)) || !str(s.reason) || typeof s.automatic !== "boolean" || typeof s.overrideActive !== "boolean" || typeof s.wheelOverlayActive !== "boolean" || !finite(s.wheelSpinsOwed) || !iso(s.updatedAt)) return false; if ((s.mode === "now_playing" || s.mode === "artist_card") && !trackOk(s.track)) return false; if (s.track != null && !trackOk(s.track)) return false; if (s.youtube != null && !syncOk(s.youtube, "youtube")) return false; if (s.tiktok != null && !syncOk(s.tiktok, "tiktok")) return false; if (!wheelOk(s.wheelCeremony)) return false; return true; }
export function extractOverlayScene(payload: unknown): ResolvedLiveOverlayScene { const scene = (payload as { scene?: unknown } | null)?.scene ?? payload; if (!isResolvedLiveOverlayScene(scene)) throw new Error("unexpected_scene"); return scene; }
export function reduceOverlaySuccess(previous: OverlayTransportState, scene: ResolvedLiveOverlayScene, generation: number): OverlayTransportState { return generation < previous.generation ? previous : { scene, connected: true, held: false, failureReason: null, generation }; }
export function reduceOverlayFailure(previous: OverlayTransportState, reason: OverlayReceiveFailure, generation: number): OverlayTransportState { return generation < previous.generation ? previous : { ...previous, connected: false, held: true, failureReason: reason, generation }; }

export type ProviderLifecycleState = { failedId: string | null; initCount: number; status: "idle" | "failed" | "ready" };
export function providerShouldInitialize(state: ProviderLifecycleState, mediaId: string): boolean { return state.failedId !== mediaId; }
export function providerMarkFailed(state: ProviderLifecycleState, mediaId: string): ProviderLifecycleState { return { ...state, failedId: mediaId, status: "failed" }; }
export function providerBeginMedia(state: ProviderLifecycleState, mediaId: string): ProviderLifecycleState { if (state.failedId === mediaId) return state; return { failedId: null, initCount: state.initCount + 1, status: "ready" }; }
export function providerSwitchMedia(state: ProviderLifecycleState, mediaId: string): ProviderLifecycleState { void mediaId; return { failedId: null, initCount: state.initCount + 1, status: "ready" }; }

export type WheelAudioAttemptResult = { notice: string | null; attempts: string[]; played: boolean; blocked: boolean };
export async function playWheelSpinWithFallback(paths: string[], play: (path: string, generation: number) => Promise<void>, generation: number, isCurrent: (generation: number) => boolean): Promise<WheelAudioAttemptResult> { const attempts = paths.slice(0, 2); for (const path of attempts) { if (!isCurrent(generation)) return { notice: null, attempts, played: false, blocked: false }; try { await play(path, generation); if (!isCurrent(generation)) return { notice: null, attempts, played: false, blocked: false }; return { notice: null, attempts, played: true, blocked: false }; } catch (error) { const blocked = error instanceof DOMException && error.name === "NotAllowedError"; if (blocked) return { notice: "WHEEL AUDIO BLOCKED — CLICK ENABLE AUDIO", attempts: [path], played: false, blocked: true }; } } return { notice: "WHEEL SPIN AUDIO UNAVAILABLE — CEREMONY CONTINUES SILENTLY", attempts, played: false, blocked: false }; }


export type WheelAudioLike = { src: string; loop: boolean; volume: number; currentTime: number; pause: () => void; play: () => Promise<void> };
export function terminateWheelSpinAudio(audio: WheelAudioLike | null, options: { volume: number; clearSource?: boolean } = { volume: 1 }): void { if (!audio) return; audio.pause(); audio.currentTime = 0; audio.volume = options.volume; audio.loop = false; if (options.clearSource) audio.src = ""; }
