import {createHash,randomBytes,timingSafeEqual} from "node:crypto";
export const ONLINE_ROOM_TTL=20*60*1000;
export const ONLINE_HOST_TIMEOUT=60000;
export const ONLINE_FIGHTERS=["6-bit","cache-back","cliff","dj-floppydisc","mac-modem","mr-nice-guy","ms-mayhem","stolz","kaveman-brown","dr3wbaby","ash-flowers","wittyf0x","doofnoobler","lyra","papa-oak","lost-marbles","mutilator","bnl-01","9-bit"] as const;
export class OnlineRoomError extends Error { constructor(message:string,public status=400){super(message);} }
type Seat={name:string;fighter:string;ready:boolean;lastSeen:number;tokenHash:string};
type Description={type:"offer"|"answer";sdp:string};
type Room={code:string;createdAt:number;expiresAt:number;host:Seat;guest:Seat|null;hostDescription:Description|null;guestDescription:Description|null};
export interface OnlineRoomStore {read(code:string):Promise<string|null>;cas(code:string,old:string|null,next:string|null,now:number):Promise<boolean>;list():Promise<string[]>;}
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
function screenName(value:unknown){if(typeof value!=="string")throw new OnlineRoomError("Choose a screen name.");const name=value.replace(/[^\p{L}\p{N} _.-]/gu,"").replace(/\s+/g," ").trim();if(!name||Array.from(name).length>24)throw new OnlineRoomError("Use a screen name of 1â€“24 characters.");return name;}
function roomCode(value:unknown){if(typeof value!=="string"||! /^[A-Z0-9]{6}$/.test(value))throw new OnlineRoomError("Use the six-character room code.");return value;}
function publicSeat(seat:Seat|null){return seat?{name:seat.name,fighter:seat.fighter,ready:seat.ready}:null;}
function owns(seat:Seat|null,token:string){if(!seat||typeof token!=="string"||token.length<24||token.length>96)return false;const actual=hash(token);return seat.tokenHash.length===actual.length&&timingSafeEqual(Buffer.from(seat.tokenHash),Buffer.from(actual));}
export function createOnlineRooms({store,now=Date.now,token=()=>randomBytes(24).toString("base64url"),code=()=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",bytes=randomBytes(6);return Array.from(bytes,b=>chars[b%chars.length]).join("");}}:{store:OnlineRoomStore;now?:()=>number;token?:()=>string;code?:()=>string}){
 async function read(id:string){const raw=await store.read(roomCode(id));if(!raw)throw new OnlineRoomError("This session is no longer available.",404);const room=JSON.parse(raw) as Room;if(room.expiresAt<=now())throw new OnlineRoomError("This session expired. Create another.",410);return {raw,room};}
 function role(room:Room,key:string){if(owns(room.host,key))return "host" as const;if(owns(room.guest,key))return "guest" as const;throw new OnlineRoomError("This seat is no longer available.",401);}
 async function mutate<T>(id:string,key:string,change:(room:Room,seat:"host"|"guest")=>T){for(let i=0;i<5;i++){const {raw,room}=await read(id),seat=role(room,key),result=change(room,seat);if(room[seat])room[seat]!.lastSeen=now();if(await store.cas(id,raw,JSON.stringify(room),now()))return result;}throw new OnlineRoomError("Session changed. Please retry.",409);}
 return {
 async create(value:unknown){const name=screenName(value),key=token(),time=now();for(let i=0;i<6;i++){const id=code();const room:Room={code:id,createdAt:time,expiresAt:time+ONLINE_ROOM_TTL,host:{name,fighter:"6-bit",ready:false,lastSeen:time,tokenHash:hash(key)},guest:null,hostDescription:null,guestDescription:null};if(await store.cas(id,null,JSON.stringify(room),time))return {code:id,role:"host" as const,token:key,expiresAt:room.expiresAt};}throw new OnlineRoomError("Sessions are busy. Please retry.",503);},
 async join(id:string,value:unknown){const name=screenName(value),key=token();for(let i=0;i<5;i++){const {raw,room}=await read(id);if(room.guest)throw new OnlineRoomError("This session already has two players.",409);if(now()-room.host.lastSeen>=ONLINE_HOST_TIMEOUT)throw new OnlineRoomError("The host is no longer here.",410);room.guest={name,fighter:"9-bit",ready:false,lastSeen:now(),tokenHash:hash(key)};if(await store.cas(id,raw,JSON.stringify(room),now()))return {code:id,role:"guest" as const,token:key,expiresAt:room.expiresAt};}throw new OnlineRoomError("Another player joined. Choose another session.",409);},
 async list(){const time=now();return (await store.list()).map(raw=>JSON.parse(raw) as Room).filter(r=>!r.guest&&r.expiresAt>time&&time-r.host.lastSeen<ONLINE_HOST_TIMEOUT).sort((a,b)=>b.createdAt-a.createdAt).slice(0,20).map(r=>({code:r.code,hostName:r.host.name,fighter:r.host.fighter,createdAt:r.createdAt}));},
 async poll(id:string,key:string){return mutate(id,key,(room,seat)=>({code:room.code,role:seat,expiresAt:room.expiresAt,host:publicSeat(room.host),guest:publicSeat(room.guest),description:seat==="host"?room.guestDescription:room.hostDescription}));},
 async select(id:string,key:string,value:{fighter?:unknown;ready?:unknown}){if(!ONLINE_FIGHTERS.includes(value.fighter as typeof ONLINE_FIGHTERS[number])||typeof value.ready!=="boolean")throw new OnlineRoomError("Choose an available fighter.");return mutate(id,key,(room,seat)=>{const player=room[seat]!;const changed=player.fighter!==value.fighter;player.fighter=value.fighter as string;player.ready=player.ready&&changed?false:value.ready as boolean;return {ok:true};});},
 async signal(id:string,key:string,value:unknown){return mutate(id,key,(room,seat)=>{const description=value as Description;if(!description||description.type!==(seat==="host"?"offer":"answer")||typeof description.sdp!=="string"||description.sdp.length>65536||!description.sdp.startsWith("v=0"))throw new OnlineRoomError("The connection signal is invalid.");if(seat==="host")room.hostDescription={type:description.type,sdp:description.sdp};else room.guestDescription={type:description.type,sdp:description.sdp};return {ok:true};});},
 async leave(id:string,key:string){for(let i=0;i<5;i++){const {raw,room}=await read(id),seat=role(room,key);if(seat==="guest"){room.guest=null;room.host.ready=false;room.hostDescription=null;room.guestDescription=null;}if(await store.cas(id,raw,seat==="host"?null:JSON.stringify(room),now()))return {ok:true};}throw new OnlineRoomError("Session changed. Please retry.",409);},
 };
}
