import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
const file=new URL("../src/lib/member-radio-routes.ts",import.meta.url);
const context={user:{id:"member-id",name:"Artist Member"},session:{expiresAt:new Date(Date.now()+3_600_000).toISOString()},revision:3,artists:[{id:"123e4567-e89b-42d3-a456-426614174000",projectKey:"artist project"}],legacyReferences:[]};
const history={currentShow:null,totals:{submitted:1,shows:1,finished:0,skipped:0,removed:0,active:1,unknown:0},tracks:[],truncated:false};
const headers={"cache-control":"private, no-store","referrer-policy":"no-referrer",vary:"Cookie"};
function load(overrides={}){
 const m={exports:{}};let calls=0,reads=0;
 vm.runInNewContext(ts.transpileModule(fs.existsSync(file)?fs.readFileSync(file,"utf8"):"",{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{
  module:m,exports:m.exports,Request,Response,Headers,URL,Date,
  require:id=>id==="server-only"?{}:id.endsWith("member-artists")?{getMemberArtistContext:async()=>{calls++;return overrides.context?overrides.context(calls):{ok:true,data:context};},isMemberArtistOrigin:req=>new URL(req.url).origin==="https://www.barcode-network.com",memberArtistPrivateHeaders:headers,memberArtistProblem:(status,code)=>Response.json({code},{status,headers})}:id.endsWith("member-access")?{lookupMemberAccess:async()=>{calls++;return overrides.owner?overrides.owner(calls):{ok:true,data:{user:{id:"owner-id"},access:{owner:true}}};}}:id.endsWith("broadcast-archive")?{broadcastArchiveArtistHref:key=>"/radio/archive?artist="+encodeURIComponent(key)}:id.endsWith("queue")?{getMemberQueueHistory:async params=>{reads++;overrides.capture?.(params);return history;},getMemberQueueArtistLabels:async()=>[{projectKey:"artist project",projectLabel:"Artist Project"}],getOwnerQueueArtistCatalog:async params=>{reads++;overrides.capture?.(params);return{artists:[],nextCursor:null};},getOwnerQueueAssociationCandidates:async params=>{reads++;overrides.capture?.(params);return{candidates:[],nextCursor:null};}}:(()=>{throw new Error(id)})(),
 });return{...m.exports,count:()=>({calls,reads})};
}
const request=(path="radio-history")=>new Request("https://www.barcode-network.com/api/member/"+path,{headers:{cookie:"__Secure-barcode_id.session_token=member"}});
test("private radio history uses only exact fresh identity/grants and never query-provided Member IDs",async()=>{let captured;const api=load({capture:p=>{captured=p;}});assert.equal((await api.getMemberRadioHistoryResponse(request("radio-history?memberId=other"))).status,400);assert.equal(api.count().reads,0);const response=await api.getMemberRadioHistoryResponse(request());assert.equal(response.status,200);assert.equal(captured.memberId,"member-id");assert.equal(captured.activeArtistIds[0],context.artists[0].id);assert.deepEqual(captured.approvedLegacyReferences,context.legacyReferences);const data=await response.json();assert.equal(data.artists[0].projectLabel,"Artist Project");assert.deepEqual(data.history,history);assert.equal(response.headers.get("vary"),"Cookie");assert.equal(api.count().calls,2);});
test("revoked Artist or switched identity during source read stops private response",async()=>{for(const next of [{...context,revision:4},{...context,user:{id:"different-member",name:"Other"}}]){const api=load({context:n=>({ok:true,data:n===1?context:next})});const response=await api.getMemberRadioHistoryResponse(request());assert.equal(response.status,409);assert.equal((await response.json()).history,undefined);}});
test("Owner radio sources require current Member Owner, including after source read",async()=>{const denied=load({owner:()=>({ok:true,data:{user:{id:"crew"},access:{owner:false}}})});assert.equal((await denied.getOwnerRadioCandidatesResponse(request("owner/radio-candidates"))).status,403);assert.equal(denied.count().reads,0);const revoked=load({owner:n=>n===1?{ok:true,data:{user:{id:"owner-id"},access:{owner:true}}}:{ok:false,status:401,code:"AUTH_REQUIRED"}});assert.equal((await revoked.getOwnerRadioCandidatesResponse(request("owner/radio-candidates"))).status,401);});
test("Owner source queries are bounded and do not accept identity, contact or arbitrary selectors",async()=>{const api=load();for(const query of ["source=all&source=native","memberId=other","limit=100","source=rehearsal","query="+"x".repeat(101),"cursor=not-valid!"]){assert.equal((await api.getOwnerRadioCandidatesResponse(request("owner/radio-candidates?"+query))).status,400);}assert.equal(api.count().reads,0);assert.equal((await api.getOwnerArtistCatalogResponse(request("owner/artist-catalog?source=all"))).status,400);});
