import assert from "node:assert/strict";
import fs from "node:fs";
import Module,{createRequire} from "node:module";
import path from "node:path";
import test from "node:test";
import ts from "typescript";
for(const key of ["UPSTASH_REDIS_REST_URL","UPSTASH_REDIS_REST_TOKEN","QUEUE_REDIS_REST_URL","QUEUE_REDIS_REST_TOKEN","BLOB_READ_WRITE_TOKEN","VERCEL"])delete process.env[key];
process.env.BARCODE_QUEUE_PRODUCTION_ENABLED="true";
process.env.BARCODE_MEMBER_SERVICE_URL="https://member-auth.barcode-network.com";
process.env.BARCODE_MEMBER_SERVICE_TOKEN="private-service-token-test-only-1234";
const root=path.resolve(import.meta.dirname,"..");const resolve=Module._resolveFilename;const load=Module._load;
Module._resolveFilename=function(request,parent,...args){return resolve.call(this,request.startsWith("@/")?path.join(root,"src",request.slice(2)):request,parent,...args);};
Module._load=function(id,...args){return id==="server-only"?{}:load.call(this,id,...args);};
Module._extensions[".ts"]=function(m,filename){m._compile(ts.transpileModule(fs.readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},fileName:filename}).outputText,filename);};
const require=createRequire(import.meta.url);const queue=require("../src/lib/queue.ts");const route=require("../src/app/api/queue/route.ts");const types=require("../src/lib/queue-types.ts");
const artistId="123e4567-e89b-42d3-a456-426614174000";
let lookupStatus=200,lookups=0,seq=0;
globalThis.fetch=async(url)=>{assert.match(String(url),/^https:\/\/member-auth\.barcode-network\.com\/api\/member\/artists$/);lookups++;return Response.json(lookupStatus===200?{user:{id:"durable-member-id",name:"Member Name"},session:{expiresAt:new Date(Date.now()+3_600_000).toISOString()},revision:9,artists:[{id:artistId,projectKey:"approved project"}],legacyReferences:[]}:{code:lookupStatus===403?"ACCOUNT_SUSPENDED":"AUTH_REQUIRED"},{status:lookupStatus});};
async function fresh(){const state=await queue.getRadioQueueState();if(state.session.status!=="archived")await queue.archiveCurrentQueueSession();const next=await queue.startNewQueueSession({purpose:"live_broadcast",submissionCooldownSeconds:0});await queue.setQueueOpen(true);return next.session.sessionId;}
function request(sessionId,extra={},cookie="",origin="https://www.barcode-network.com") {return new Request("https://www.barcode-network.com/api/queue",{method:"POST",headers:{"content-type":"application/json",origin,...(cookie?{cookie}:{})},body:JSON.stringify({sessionId,artist:"Submitted Credit",title:"Song "+(++seq),mode:"link",link:"https://example.test/song-"+seq,tiktokHandle:"@test",acceptedLegal:true,termsVersion:types.PUBLIC_QUEUE_LEGAL_TERMS_VERSION,privacyVersion:types.PUBLIC_QUEUE_LEGAL_PRIVACY_VERSION,queueTermsVersion:types.PUBLIC_QUEUE_LEGAL_QUEUE_TERMS_VERSION,acceptedCheckboxText:types.PUBLIC_QUEUE_LEGAL_CHECKBOX_TEXT,...extra})});}
async function stored(id){const state=await queue.getRadioQueueState();return [...state.queue,state.nextInLine,state.loadedTrack,...state.history,...state.removed].filter(Boolean).find(t=>t.id===id);}

test("guest body cannot forge durable ownership and never depends on Member service",async()=>{lookups=0;lookupStatus=200;const session=await fresh();const response=await route.POST(request(session,{submissionMemberId:"forged-owner",approvedArtistId:artistId,approvedArtistLinkRevision:123}));assert.equal(response.status,201);const body=await response.json();const track=await stored(body.track.id);assert.equal(track.submissionMemberId,null);assert.equal(track.approvedArtistId,null);assert.equal(lookups,0);});
test("signed-in intake stamps live Member identity and approved Artist while public acceptance stays redacted",async()=>{lookupStatus=200;lookups=0;const session=await fresh();const response=await route.POST(request(session,{submissionMemberId:"forged-owner",artistId},"__Secure-barcode_id.session_token=real-session"));assert.equal(response.status,201,JSON.stringify(await response.clone().json()));const body=await response.json();const track=await stored(body.track.id);assert.equal(track.submissionMemberId,"durable-member-id");assert.equal(track.approvedArtistId,artistId);assert.equal(track.approvedArtistLinkRevision,9);assert.equal(lookups,1);for(const key of ["submissionMemberId","approvedArtistId","approvedArtistLinkRevision"])assert.equal(key in body.track,false);});
test("expired or suspended account cannot silently become guest and writes no song",async()=>{for(const status of [401,403,503]){lookupStatus=status;const session=await fresh();const before=await queue.getRadioQueueState();const response=await route.POST(request(session,{},"__Secure-barcode_id.session_token=old-session"));assert.equal(response.status,status);const after=await queue.getRadioQueueState();assert.equal(after.revision,before.revision);}});
test("unapproved Artist or cross-site signed-in submission is rejected before queue admission",async()=>{lookupStatus=200;for(const [artist,origin]of[["423e4567-e89b-42d3-a456-426614174000","https://www.barcode-network.com"],[artistId,"https://evil.test"]]){const session=await fresh();const before=await queue.getRadioQueueState();const response=await route.POST(request(session,{artistId:artist},"__Secure-barcode_id.session_token=member",origin));assert.equal(response.status,403);assert.equal((await queue.getRadioQueueState()).revision,before.revision);}});
