import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createMatch,advanceMatch,performAction,consumeEvents,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {limbContact} from '../public/games/system-clash/play/fight-combat-geometry.mjs';
const base=new URL('../public/games/system-clash/play/assets/',import.meta.url),cache=new Map();
function native(id){if(cache.has(id))return cache.get(id);const clips={};let manifest;for(const bank of ['fighters','arcade']){const m=JSON.parse(readFileSync(new URL(`${bank}/${id}/manifest.json`,base),'utf8'));if(bank==='fighters')manifest=m;for(const [name,data]of Object.entries(m.clips)){const frames=Object.values(data.frames).flat(),size=data.sourceSize??[Math.max(...frames.map(f=>f.rect[0]+f.rect[2])),Math.max(...frames.map(f=>f.rect[1]+f.rect[3]))];clips[name]=compileFightClip(data,{width:size[0],height:size[1]},m,name);}}const art={manifest,clips},result={art,metadata:combatMetadata([art])[0]};cache.set(id,result);return result;}
function scene(ids=['6-bit','6-bit'],facing='right',gap=106,clips=ids.map(id=>native(id).metadata)){const match=createMatch({mode:'local',start:false,fighters:ids.map(id=>({id,height:native(id).art.manifest.height})),clips});match.phase='fight';const dir=facing==='right'?1:-1;match.fighters[0].x=900;match.fighters[1].x=900+dir*gap;match.fighters[0].facing=facing;match.fighters[1].facing=facing==='right'?'left':'right';return match;}
function advance(match,ms,controls=[{},{}]){advanceMatch(match,ms,controls);}
for(const facing of ['left','right'])for(const [action,gap]of [['kick',230],['low-punch',140],['low-kick',205]])test(`native ${action} contacts its physically reached body ${action==='low-punch'?'within its calibrated reach':'beyond the old center cap'} (${facing})`,()=>{const m=scene(undefined,facing,gap);assert(performAction(m,0,action));advance(m,1000);const events=consumeEvents(m);assert.equal(events.filter(e=>e.type==='hit').length,1);assert.equal(events.filter(e=>e.type==='miss').length,0);});
for(const facing of ['left','right'])test(`calibrated native low-punch stops before the former oversized contact gap (${facing})`,()=>{const m=scene(undefined,facing,170);assert(performAction(m,0,'low-punch'));advance(m,1000);const events=consumeEvents(m);assert.equal(events.filter(e=>e.type==='hit').length,0,'The narrowed native fist cannot gain invisible replacement reach');assert.equal(events.filter(e=>e.type==='miss').length,1);assert.equal(m.fighters[1].hp,100);});
for(const facing of ['left','right'])test(`native long contact keeps proper guard and a true distant whiff (${facing})`,()=>{const guard=scene(undefined,facing,230);advance(guard,550,[{},{block:true}]);consumeEvents(guard);performAction(guard,0,'kick');advance(guard,900,[{},{block:true}]);assert.equal(consumeEvents(guard).filter(e=>e.type==='block').length,1);const far=scene(undefined,facing,600);performAction(far,0,'kick');advance(far,1000);assert.equal(far.fighters[1].hp,100);assert.equal(consumeEvents(far).filter(e=>e.type==='miss').length,1);});
function fixture(tip,grip=tip){const poses=Object.fromEntries(['right','left'].map(facing=>{const d=facing==='right'?1:-1;return [facing,[{bounds:{left:-35,top:-250,right:35,bottom:0},sites:{head:{x:0,y:-230},torso:{x:0,y:-170},legs:{x:0,y:-70},grip:{x:grip*d,y:-170}},hurt:[{site:'head',left:-12,right:12,top:-245,bottom:-220},{site:'torso',left:-10,right:10,top:-205,bottom:-80},{site:'legs',left:-12,right:12,top:-80,bottom:0}],strikeStart:{x:40*d,y:-170},strike:{x:tip*d,y:-170},strikeRadius:8}]];}));const combatPoses={frames:poses,entries:[{index:0,start:0,end:600}],duration:600,loop:false};return {idle:{duration:600,loop:true,combatPoses:{...combatPoses,loop:true}},punch:{duration:600,contactMs:170,activeEndMs:280,combatPoses},kick:{duration:600,contactMs:170,activeEndMs:280,combatPoses}};}
for(const facing of ['left','right'])test(`style reach neither stretches nor retracts a native fist (${facing})`,()=>{const stretched=scene(['dj-floppydisc','6-bit'],facing,125,[fixture(80),fixture(80)]);performAction(stretched,0,'kick');advance(stretched,700);assert.equal(stretched.fighters[1].hp,100,'The actual tip plus radius stops before the measured chest edge');const shortened=scene(['wittyf0x','6-bit'],facing,145,[fixture(120),fixture(120)]);performAction(shortened,0,'punch');advance(shortened,700);assert(shortened.fighters[1].hp<100,'The actual fist is not pulled back by the style');});
for(const facing of ['left','right'])test(`a grab requires the native hand to reach a body, independent of fist strike (${facing})`,()=>{const tooShort=scene(['mac-modem','6-bit'],facing,110,[fixture(160,50),fixture(100)]);performAction(tooShort,0,'grab');advance(tooShort,800);assert.equal(tooShort.fighters[1].hp,100,'A long punch strike cannot substitute for the gripping hand');const reaches=scene(['6-bit','6-bit'],facing,145,[fixture(160,140),fixture(100)]);performAction(reaches,0,'grab');advance(reaches,800);assert(reaches.fighters[1].hp<100,'A measured gripping hand can reach beyond the old130 center cap');});
test('missing native geometry retains bounded fallback reach',()=>{const m=scene(['6-bit','6-bit'],'right',230,[{},{}]);performAction(m,0,'kick');advance(m,1000);assert.equal(m.fighters[1].hp,100);assert.equal(consumeEvents(m).filter(e=>e.type==='miss').length,1);});
for(const side of ['left','right'])test(`ground push redistributes blocked wall movement (${side})`,()=>{const m=scene(['6-bit','9-bit'],'right',105,[{},{}]),edge=m.fighters[0]._worldWidth-210;m.fighters[0].x=side==='left'?210:edge-105;m.fighters[1].x=m.fighters[0].x+105;advance(m,100,side==='left'?[{},{move:-1}]:[{move:1},{}]);assert(Math.abs(m.fighters[1].x-m.fighters[0].x)>=105-1e-7);assert(m.fighters[0].x>=210);assert(m.fighters[1].x<=edge);});
test('committed grounded attacks and a newly landed jump cannot bypass core push',()=>{const clips=fixture(120),m=scene(['6-bit','6-bit'],'right',20,[clips,clips]);for(const f of m.fighters){f.action='punch';f.actionTime=20;}advance(m,10);assert(Math.abs(m.fighters[1].x-m.fighters[0].x)>20,'Active bodies resolve actual torso overlap');const landing=scene(['6-bit','6-bit'],'right',20,[clips,clips]);landing.fighters[0].action='jump';landing.fighters[0]._jump={elapsed:570,duration:580,move:0,attackUsed:false};advance(landing,10);assert.equal(landing.fighters[0]._jump,null);assert(Math.abs(landing.fighters[1].x-landing.fighters[0].x)>20,'Landing is separated in the same engine step');});
test('a body above the grounded core and the held throw victim keep their intentional positions',()=>{const clips=fixture(120),air=scene(['6-bit','6-bit'],'right',20,[clips,clips]);air.fighters[0].action='jump';air.fighters[0]._jump={elapsed:280,duration:580,move:0,attackUsed:false};advance(air,10);assert.equal(air.fighters[1].x-air.fighters[0].x,20);const held=scene(['6-bit','6-bit'],'right',20,[clips,clips]);held.fighters[0].action='grab';held.fighters[1].action='grabbed';advance(held,10);assert.equal(held.fighters[1].x-held.fighters[0].x,20);});
function strikeFixture(tip,start={x:40,y:-170}){const clips=fixture(120);for(const facing of ['right','left']){const dir=facing==='right'?1:-1;for(const name of ['idle','punch','kick']){const pose=clips[name].combatPoses.frames[facing][0];pose.strike={x:tip.x*dir,y:tip.y};pose.strikeStart={x:start.x*dir,y:start.y};pose.hurt=[{site:'torso',left:-10,right:10,top:-205,bottom:-80}];}}return clips;}
for(const facing of ['left','right'])test(`diagonal limb corners cannot add native reach (${facing})`,()=>{const m=scene(['6-bit','6-bit'],facing,100,[strikeFixture({x:83,y:-212},{x:40,y:-230}),strikeFixture({x:120,y:-170})]);performAction(m,0,'punch');advance(m,700);assert.equal(m.fighters[1].hp,100,'The endpoint is 7px from each box edge: its 8px radius cannot bridge the 9.899px corner distance');assert.equal(consumeEvents(m).filter(e=>e.type==='miss').length,1);});
for(const facing of ['left','right'])test(`exact limb tangency remains a physical contact (${facing})`,()=>{const m=scene(['6-bit','6-bit'],facing,100,[strikeFixture({x:110,y:-213},{x:40,y:-213}),strikeFixture({x:120,y:-170})]);performAction(m,0,'punch');advance(m,700);assert(m.fighters[1].hp<100,'The limb center is exactly its 8px radius above the torso top');});
for(const facing of ['left','right'])test(`airborne hit testing preserves the attacking limb altitude (${facing})`,()=>{for(const [height,wantHit] of [[-170,false],[-300,true]]){const m=scene(['6-bit','6-bit'],facing,100,[strikeFixture({x:120,y:height},{x:40,y:height}),strikeFixture({x:120,y:-170})]);m.fighters[1].action='jump';m.fighters[1]._jump={elapsed:280,duration:580,move:0,attackUsed:false};performAction(m,0,'punch');m.fighters[0].actionTime=160;advance(m,10);assert.equal(m.fighters[1].hp<100,wantHit,height===-170?'A grounded fist cannot be translated to the victim\u2019s altitude':'A raised native fist can contact the airborne torso');}});
for(const side of ['left','right'])test(`native wall push uses measured chest width rather than a universal 105px gap (${side})`,()=>{const clips=fixture(120),m=scene(['6-bit','6-bit'],'right',20,[clips,clips]);const edge=m.fighters[0]._worldWidth-210;m.fighters[0].x=side==='left'?210:edge-20;m.fighters[1].x=m.fighters[0].x+20;advance(m,10);assert(Math.abs(m.fighters[1].x-m.fighters[0].x-52.9)<1e-7,'Right/left native chest half-widths are 26.8px and26.1px; tails, fists and floor width do not enlarge push');assert.equal(side==='left'?m.fighters[0].x:m.fighters[1].x,side==='left'?210:edge);});
test('incomplete native attack sites fall back without an undefined endpoint crash',()=>{const clips=fixture(120);for(const facing of ['left','right']){delete clips.punch.combatPoses.frames[facing][0].strike;delete clips.punch.combatPoses.frames[facing][0].strikeStart;}const m=scene(['6-bit','6-bit'],'right',230,[clips,clips]);performAction(m,0,'punch');assert.doesNotThrow(()=>advance(m,700));assert.equal(m.fighters[1].hp,100);assert.equal(consumeEvents(m).filter(e=>e.type==='miss').length,1);});
for(const facing of ['left','right'])test(`grab collision uses the same native hand frame as its drawn throw tempo (${facing})`,()=>{const attacker=fixture(160,50);attacker.punch.combatPoses.entries=[{index:0,start:0,end:175},{index:1,start:175,end:600}];for(const face of ['left','right']){const dir=face==='right'?1:-1,first=attacker.punch.combatPoses.frames[face][0];attacker.punch.combatPoses.frames[face]=[first,{...first,sites:{...first.sites,grip:{x:140*dir,y:-170}}}];}const m=scene(['mac-modem','6-bit'],facing,145,[attacker,fixture(100)]);performAction(m,0,'grab');m.fighters[0].actionTime=150;advance(m,10);const view=getFighterView(m,0);assert(view.elapsed>=175,'The visible hand has entered its long grip frame');assert.equal(view.poseIndex,1,'Collision and rendering sample the same native frame');assert.equal(consumeEvents(m).filter(e=>e.type==='hit').length,1,'The drawn native hand reaches the torso');});

// Independent oracle: shortest Euclidean distance from a finite segment to the
// unexpanded box. It does not reproduce the production rounded-strip algorithm.
function segmentBoxDistance2(start,end,body){const dx=end.x-start.x,dy=end.y-start.y;let enter=0,leave=1,intersects=true;for(const [origin,delta,min,max]of [[start.x,dx,body.left,body.right],[start.y,dy,body.top,body.bottom]]){if(delta===0){if(origin<min||origin>max)intersects=false;continue;}const a=(min-origin)/delta,b=(max-origin)/delta;enter=Math.max(enter,Math.min(a,b));leave=Math.min(leave,Math.max(a,b));}if(intersects&&enter<=leave)return 0;const pointBox=p=>Math.max(body.left-p.x,0,p.x-body.right)**2+Math.max(body.top-p.y,0,p.y-body.bottom)**2;let result=Math.min(pointBox(start),pointBox(end));const length2=dx*dx+dy*dy;for(const x of [body.left,body.right])for(const y of [body.top,body.bottom]){const t=length2?Math.max(0,Math.min(1,((x-start.x)*dx+(y-start.y)*dy)/length2)):0;result=Math.min(result,(x-start.x-t*dx)**2+(y-start.y-t*dy)**2);}return result;}
test('native active fist and foot capsules match an independent closest-distance oracle for all fighters and facings',t=>{const roster=JSON.parse(readFileSync(new URL('fight-roster.json',base),'utf8')).fighters.filter(f=>f.enabled);let checks=0;for(const {id}of roster){const clips=native(id).metadata;for(const action of ['punch','kick','low-punch','low-kick','uppercut','crouch-punch','crouch-kick','crouch-high-kick','double-punch','power-kick','jump-punch','jump-kick']){const clip=clips[action];if(!clip?.combatPoses)continue;const active=clip.combatPoses.entries.filter(entry=>entry.end>clip.contactMs&&entry.start<clip.activeEndMs);for(const facing of ['left','right']){const dir=facing==='right'?1:-1,victim=clips.idle.combatPoses.frames[dir===1?'left':'right'][0];for(const entry of active){const pose=clip.combatPoses.frames[facing][entry.index];for(let gap=60;gap<=330;gap+=15)for(const region of victim.hurt){const body={...region,left:region.left+dir*gap,right:region.right+dir*gap};const want=segmentBoxDistance2(pose.strikeStart,pose.strike,body)<=pose.strikeRadius**2+1e-8;const contact=limbContact(pose.strikeStart,pose.strike,body,pose.strikeRadius);assert.equal(!!contact,want,`${id} ${action} ${facing} gap${gap} ${body.site}`);if(contact){assert(contact.x>=body.left&&contact.x<=body.right&&contact.y>=body.top&&contact.y<=body.bottom,'Contact event lies on the physical body box');}checks++;}}}}}assert(checks>=20000,`All native active poses must be exercised; observed ${checks} capsule/body comparisons`);t.diagnostic(`${checks} independent native capsule/body comparisons across ${roster.length} fighters`);});
test('zero-length limbs use circle distance and contact at a true rounded tangent',()=>{const body={site:'torso',left:100,right:120,top:100,bottom:120};assert.equal(limbContact({x:92,y:92},{x:92,y:92},body,10),null);assert.deepEqual(limbContact({x:90,y:100},{x:90,y:100},body,10),{x:100,y:100,site:'torso'});assert.deepEqual(limbContact({x:110,y:110},{x:110,y:110},body,0),{x:110,y:110,site:'torso'});});
test('a near-floor jumping body resolves actual overlapping cores before takeoff clearance',()=>{const clips=fixture(120);clips.jump={...clips.idle,loop:false};const m=scene(['6-bit','6-bit'],'right',20,[clips,clips]);m.fighters[0].action='jump';m.fighters[0]._jump={elapsed:20,duration:580,move:0,attackUsed:false};advance(m,10);const gap=m.fighters[1].x-m.fighters[0].x;assert(gap>=52.9-1e-7&&gap<=70+1e-7,'The rising torso and lower leg clear the grounded core within native body bounds; an air flag cannot disable physical push');});
for(const facing of ['left','right'])for(const side of ['left','right'])test(`two committed native bodies fully separate against a ${side} wall (${facing})`,()=>{const clips=fixture(120),m=scene(['6-bit','6-bit'],facing,20,[clips,clips]),edge=m.fighters[0]._worldWidth-210;const left=side==='left'?210:edge-20;const sorted=[...m.fighters].sort((a,b)=>a.x-b.x);sorted[0].x=left;sorted[1].x=left+20;for(const f of m.fighters){f.action='punch';f.actionTime=20;}advance(m,10);assert(Math.abs(sorted[1].x-sorted[0].x-52.9)<1e-7,'The wall-blocked half is redistributed even while both bodies are committed');assert.equal(side==='left'?sorted[0].x:sorted[1].x,side==='left'?210:edge);});
for(const facing of ['left','right'])test(`the native physical chest edge that blocks movement can also take a fist contact (${facing})`,()=>{const m=scene(['6-bit','6-bit'],facing,105,[fixture(80),fixture(80)]);performAction(m,0,'punch');advance(m,700);assert(m.fighters[1].hp<100,'The measured chest edge lies inside the native fist radius, although the generic torso box is narrower');assert.equal(consumeEvents(m).filter(e=>e.type==='hit'&&e.action==='punch').length,1);});
