import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {compilePoseRenderTimeline,samplePoseTween,poseTweenMesh,drawPoseMesh,drawPoseTween,poseTweenCacheSize,clearPoseTweenCache} from '../public/games/system-clash/play/fight-pose-tween.mjs';
import {poseFrameIndex,poseTransform} from '../public/games/system-clash/play/fight-attachments.mjs';
import {walkRig} from '../public/games/system-clash/play/fight-walk-rig.mjs';
import {createFightRenderer} from '../public/games/system-clash/play/fight-renderer.mjs';
import {createOnlineCombatController,makeFightSnapshot} from '../public/games/system-clash/play/fight-network-state.mjs';
import {createMatch,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
const ROOT=new URL('../public/games/system-clash/play/',import.meta.url);
const read=(bank,id)=>JSON.parse(readFileSync(new URL(`assets/${bank}/${id}/manifest.json`,ROOT),'utf8'));
const fake=c=>({width:Math.max(...Object.values(c.frames).flat().map(f=>f.rect[0]+f.rect[2])),height:Math.max(...Object.values(c.frames).flat().map(f=>f.rect[1]+f.rect[3]))});
const ids=JSON.parse(readFileSync(new URL('assets/fight-roster.json',ROOT),'utf8')).fighters.filter(f=>f.enabled).map(f=>f.id);
test('every native animation gains distinct visual intermediates without changing authoritative keys or timeline',()=>{
 let total=0,four=0,eight=0;
 for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const before=JSON.stringify(c),a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name),original=JSON.stringify(a.timeline),r=a.renderTimeline??compilePoseRenderTimeline(a),n=c.frames.right.length,active=new Set(a.timeline.entries.map(e=>e.index)).size;assert.equal(JSON.stringify(c),before);assert.equal(JSON.stringify(a.timeline),original);assert.equal(r.poseCount,active>1?n+2:active);assert.equal(r.duration,a.timeline.duration);assert.equal(new Set(r.poses.map(p=>p.kind==='native'?`n${p.index}`:`t${p.from}/${p.to}/${p.amount}`)).size,r.poseCount);if(n===4)four++;if(n===8)eight++;total++;}}
 assert.equal(total,683);assert.equal(four,424);assert.equal(eight,27);
});
test('inserted visual poses leave exact native contact, impact hold, recovery endpoints and explicit choreography untouched',()=>{
 for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name);for(const facing of ['left','right']){assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:0}),null);assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:a.timeline.duration-.001}),null);assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:100,frameIndex:0}),null);for(const t of [c.contactMs,c.activeEndMs,c.liftMs,c.releaseMs,c.alignMs].filter(Number.isFinite))assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:t}),null,`${id}/${name}/${facing}@${t}`);}}}
});
test('native width and rigid head mesh stay exact while a true transition changes lower pixels',()=>{
 const m=read('fighters','6-bit'),c=m.clips.walk,a=compileFightClip(c,fake(c),m,'walk');let sampled=null;for(const entry of a.renderTimeline.entries){sampled=samplePoseTween(a,{clip:'walk',facing:'right',elapsed:(entry.start+entry.end)/2});if(sampled)break;}assert(sampled);const mesh=poseTweenMesh(a,{clip:'walk',facing:'right'},sampled);const f=c.frames.right[sampled.from],tr=poseTransform(a,f),head=f.attachments.head,headY=head[1]*.5;const p=mesh.map({x:head[0]-8,y:headY}),q=mesh.map({x:head[0]+8,y:headY});assert(Math.abs(q.x-p.x-16*tr.sx)<1e-9,'Rigid skull width cannot change');assert.equal(p.y,q.y);assert(mesh.vertices.some(v=>Math.hypot(v.destination.x-tr.point(v.source).x,v.destination.y-tr.point(v.source).y)>.1),'Intermediate is a changed pose, not a held crop');
});
test('reduced motion, explicit frame and masked/body-cut composition retain native rendering',()=>{
 const m=read('fighters','6-bit'),c=m.clips.walk,a=compileFightClip(c,fake(c),m,'walk'),ctx={canvas:{},drawImage(){throw Error('No raster should be drawn');}};for(const view of [{reducedMotion:true},{frameIndex:1},{halfMask:1},{rotation:1},{eraseProgress:.5},{aftermath:{region:{}}}])assert.equal(drawPoseTween(ctx,a,{clip:'walk',facing:'right',elapsed:60,...view}),false);
});
test('combat metadata derives only original native poses when the visual timeline is present',()=>{
 const m=read('fighters','9-bit'),c=m.clips.punch,a=compileFightClip(c,fake(c),m,'punch'),withVisual=combatMetadata([{manifest:m,clips:{punch:a}}]);delete a.renderTimeline;const native=combatMetadata([{manifest:m,clips:{punch:a}}]);assert.deepEqual(withVisual,native);
});

test('a visual transition never rolls back to its source pose before its next native key',()=>{
 for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name),r=a.renderTimeline;for(let i=0;i<r.entries.length;i++){const pose=r.poses[r.entries[i].pose];if(pose.kind!=='tween')continue;let last=pose.amount;for(let j=i+1;j<r.entries.length;j++){const next=r.poses[r.entries[j].pose];if(next.kind==='native'){assert.equal(next.index,pose.to,`${id}/${bank}/${name}: future pose cannot return to original before key boundary`);break;}assert.equal(next.from,pose.from);assert.equal(next.to,pose.to);assert(next.amount>last);last=next.amount;}}}}
});
test('all inserted facing poses deform measured native geometry rather than padding the holds',()=>{
 let added=0;for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name);for(const facing of ['left','right'])for(const pose of a.renderTimeline.poses){if(pose.kind!=='tween')continue;const mesh=poseTweenMesh(a,{facing},pose),tr=poseTransform(a,mesh.frame),maximum=Math.max(...mesh.vertices.map(v=>Math.hypot(v.destination.x-tr.point(v.source).x,v.destination.y-tr.point(v.source).y)));assert(maximum>.01,`${id}/${bank}/${name}/${facing} must add real source geometry, not a duplicate hold`);added++;}}}assert.equal(added,2696);
});
const require=createRequire(import.meta.url);let nativeCanvas=null;try{nativeCanvas=require(process.env.SYSTEM_CLASH_CANVAS_MODULE??'@napi-rs/canvas');}catch{}
test('32 actual native raster intermediates remain single opaque bodies and reuse bounded lazy caches',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas;let scenes=0;const hash=b=>createHash('sha256').update(b).digest('hex');
 for(const id of ids.filter(id=>id!=='bnl-01').slice(0,16)){const m=read('fighters',id),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL(`assets/fighters/${id}/${c.file}`,ROOT))),a=compileFightClip(c,image,m,'walk');for(const facing of ['left','right']){const e=a.renderTimeline.entries.find(e=>a.renderTimeline.poses[e.pose].kind==='tween'),view={clip:'walk',facing,elapsed:(e.start+e.end)/2},sample=samplePoseTween(a,view),frame=c.frames[facing][sample.from],tr=poseTransform(a,frame),canvas=createCanvas(640,600),ctx=canvas.getContext('2d'),native=createCanvas(640,600),n=native.getContext('2d');n.drawImage(image,...frame.rect,320+tr.tx,560+tr.ty,frame.rect[2]*tr.sx,frame.rect[3]*tr.sy);assert(drawPoseTween(ctx,a,view,{frame,transform:tr,dx:320+tr.tx,dy:560+tr.ty,canvasFactory:createCanvas}));const pixels=ctx.getImageData(0,0,640,600).data;assert.notEqual(hash(pixels),hash(n.getImageData(0,0,640,600).data),`${id}/${facing} adds a raster pose`);let occupied=0,bottom=0;for(let y=0;y<600;y++)for(let x=0;x<640;x++)if(pixels[(y*640+x)*4+3]>48){occupied++;bottom=Math.max(bottom,y);}assert(occupied>500);assert(bottom<=561,'Interpolated native feet cannot fall through the stage');const before=hash(pixels),cacheCount=poseTweenCacheSize(a);ctx.clearRect(0,0,640,600);assert(drawPoseTween(ctx,a,view,{frame,transform:tr,dx:320+tr.tx,dy:560+tr.ty,canvasFactory(){throw Error('Warm rendering must reuse the cached native raster');}}));assert.equal(hash(ctx.getImageData(0,0,640,600).data),before);assert.equal(poseTweenCacheSize(a),cacheCount);assert(cacheCount<=32);scenes++;}}assert.equal(scenes,32);
});
test('a native mesh cache stays bounded even across many source phases',{skip:!nativeCanvas},()=>{
 const {createCanvas}=nativeCanvas,image=createCanvas(20,30),ic=image.getContext('2d');ic.fillStyle='#f0f';ic.fillRect(3,2,14,28);const frame={rect:[0,0,20,30],anchor:[10,30],opaqueBounds:[3,2,17,30]},asset={image,scale:1,name:'idle',fighterId:'test',data:{frames:{right:[frame],left:[frame]}},timeline:{entries:[{index:0,start:0,end:100}],duration:100}},ctx=createCanvas(100,100).getContext('2d'),tr=poseTransform(asset,frame);for(let k=0;k<40;k++)assert(drawPoseMesh(ctx,asset,frame,p=>tr.point(p),{x:50,y:60,canvasFactory:createCanvas,cacheKey:String(k)}));assert.equal(poseTweenCacheSize(asset),32);
});
test('guest walks retain absolute time and full articulation across consecutive native loops',()=>{
 const m=read('fighters','6-bit'),c=m.clips.walk,a=compileFightClip(c,fake(c),m,'walk'),duration=a.timeline.duration,schema={roster:['6-bit','9-bit'],clipIds:[['idle','walk'],['idle','walk']],matchId:1};let time=0;
 const guest=createOnlineCombatController({...schema,seat:1,now:()=>time,clipTimings:[{walk:{duration,loop:true}},{}]});assert(guest.receive({type:'start',matchId:1,seed:77}));
 const match=createMatch({mode:'local',stage:'radio-studio',start:false});match.phase='fight';const views=match.fighters.map((_,i)=>getFighterView(match,i));views[0]={...views[0],clip:'walk',elapsed:duration-20,facing:'right'};
 const snapshot=makeFightSnapshot(match,views,{...schema,seq:1,at:0});assert(snapshot);assert(guest.receive({type:'snapshot',snapshot}));
 let previous=0,first=null;for(const age of [30,duration+30,2*duration+30]){time=age;const view=guest.views()[0];assert.equal(view.elapsed,duration-20+age);assert.equal(view.nativeElapsed,view.elapsed);assert(view.elapsed>previous);previous=view.elapsed;const index=poseFrameIndex(a,view),rig=walkRig(a,view,c.frames.right[index]);assert.equal(rig.strength,1,'A later step must not repeat the initial 100ms strength ramp');if(first){assert.equal(index,first.index);assert.equal(rig.cacheKey,first.rig.cacheKey);assert.deepEqual(rig.feet,first.rig.feet);}else first={index,rig};}
});

test('essential leg articulation remains visible under reduced motion while decorative pose tweening stops',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas,m=read('fighters','6-bit'),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL(`assets/fighters/6-bit/${c.file}`,ROOT))),a=compileFightClip(c,image,m,'walk'),view={clip:'walk',facing:'right',elapsed:150},frame=c.frames.right[poseFrameIndex(a,view)],tr=poseTransform(a,frame),rig=walkRig(a,view,frame),options={frame,transform:tr,dx:320+tr.tx,dy:560+tr.ty,rig,canvasFactory:createCanvas},normal=createCanvas(640,600),reduced=createCanvas(640,600),native=createCanvas(640,600);
 assert(drawPoseTween(normal.getContext('2d'),a,view,options));assert.equal(samplePoseTween(a,{...view,reducedMotion:true}),null);assert(drawPoseTween(reduced.getContext('2d'),a,{...view,reducedMotion:true},options));native.getContext('2d').drawImage(image,...frame.rect,320+tr.tx,560+tr.ty,frame.rect[2]*tr.sx,frame.rect[3]*tr.sy);
 const pixels=canvas=>canvas.getContext('2d').getImageData(0,0,640,600).data;assert.deepEqual(pixels(reduced),pixels(normal),'Preference cannot alter visible leg contact');assert.notDeepEqual(pixels(reduced),pixels(native),'The raised foot remains visible');
});

test('the actual walking renderer retains gait and outboard toes inside an upper source exclusion mask',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas,m=read('fighters','dj-floppydisc'),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL(`assets/fighters/dj-floppydisc/${c.file}`,ROOT))),a=compileFightClip(c,image,m,'walk'),probe=createCanvas(1280,720),pc=probe.getContext('2d');let chosen=null;
 for(let phase=0;phase<24&&!chosen;phase++){const view={clip:'walk',facing:'right',elapsed:a.timeline.duration*(1+phase/24),x:640,y:0,opacity:1},index=poseFrameIndex(a,view),frame=c.frames.right[index],tr=poseTransform(a,frame);pc.clearRect(0,0,1280,720);assert(drawPoseTween(pc,a,view,{frame,transform:tr,dx:640+tr.tx,dy:620+tr.ty,rig:walkRig(a,view,frame),canvasFactory:createCanvas}));const pixels=pc.getImageData(0,0,1280,720).data,outside=[];for(let y=500;y<640;y++)for(let x=400;x<900;x++)if(pixels[(y*1280+x)*4+3]>160&&(x<640+tr.tx||x>=640+tr.tx+frame.rect[2]*tr.sx))outside.push((y*1280+x)*4);if(outside.length>5)chosen={view,index,frame,outside};}
 assert(chosen,'A real Floppy step moves opaque toe pixels outside the old native crop');const {view,index,frame,outside}=chosen;frame.sourceExclusions=[[0,0,frame.rect[2],40]];clearPoseTweenCache(a);
 const art={manifest:m,clips:{walk:a}},metadata=combatMetadata([art])[0],fighter={id:m.id,name:m.character,height:m.height,hp:100,maxHp:100,action:'walk',actionTime:view.elapsed,_clips:metadata},match={phase:'fight',combatTime:view.elapsed,fighters:[fighter,{id:'9-bit',name:'Nine',hp:100,maxHp:100}],stagePickups:[],projectiles:[],roundRemaining:90000},canvas=createCanvas(1280,720),renderer=createFightRenderer(canvas);
 renderer.draw({match,views:[view],art:[art],presentationTimeMs:150,reducedMotion:true});assert(poseTweenCacheSize(a)>0,'The masked body must draw its leg mesh rather than leave physical feet invisible');const drawn=canvas.getContext('2d').getImageData(0,0,1280,720).data;
 const crop=()=>canvas.getContext('2d').getImageData(480,200,320,120).data,head=crop();renderer.draw({match,views:[{...view,frameIndex:index}],art:[art],presentationTimeMs:150,reducedMotion:true});const control=canvas.getContext('2d').getImageData(0,0,1280,720).data;let visible=0;for(const i of outside)if(Math.abs(drawn[i]-control[i])+Math.abs(drawn[i+1]-control[i+1])+Math.abs(drawn[i+2]-control[i+2])>6)visible++;assert(visible>=outside.length*.9,`The hair exclusion crop must retain actual outboard toe pixels (${visible}/${outside.length})`);
 const final=crop();let changed=0,max=0;for(let i=0;i<head.length;i++){const delta=Math.abs(final[i]-head[i]);if(delta)changed++;max=Math.max(max,delta);}assert(max<=2&&changed<head.length*.04,'Rigid upper crop permits only native mesh resampling rounding: '+changed+'/'+head.length+' channels; max '+max);
});