import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createMatch,advanceMatch,performAction,consumeEvents,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {createGamepadInput} from '../public/games/system-clash/play/fight-gamepad.mjs';
const root=new URL('../public/games/system-clash/play/assets/',import.meta.url);
const roster=JSON.parse(fs.readFileSync(new URL('fight-roster.json',root))).fighters.filter(f=>f.enabled);
function nativeArt(id){let manifest;const clips={};for(const bank of ['fighters','arcade','deletions']){const dir=new URL(bank+'/'+id+'/',root),m=JSON.parse(fs.readFileSync(new URL('manifest.json',dir)));if(bank==='fighters')manifest=m;for(const[name,data]of Object.entries(m.clips)){const frames=Object.values(data.frames).flat(),size={width:Math.max(...frames.map(f=>f.rect[0]+f.rect[2])),height:Math.max(...frames.map(f=>f.rect[1]+f.rect[3]))};const clip=bank==='deletions'?'delete-'+name:name;clips[clip]=compileFightClip(data,size,m,clip);}}return {manifest,clips};}
const art=Object.fromEntries(roster.map(f=>[f.id,nativeArt(f.id)]));
function scene(ids=['6-bit','6-bit'],native=false,facing='right',stage='witty-wasteland'){const a=ids.map(id=>art[id]),m=createMatch({mode:'local',start:false,stage,roundTimeMs:0,fighters:a.map(f=>({id:f.manifest.id,height:f.manifest.height})),clips:native?combatMetadata(a):undefined});m.phase='fight';const dir=facing==='right'?1:-1;m.fighters[0].x=1200;m.fighters[1].x=1200+dir*(native?150:106);m.fighters[0].facing=facing;m.fighters[1].facing=facing==='right'?'left':'right';return m;}
function advance(m,ms,controls=[{},{}]){while(ms>0){const dt=Math.min(100,ms);advanceMatch(m,dt,controls);ms-=dt;}}
for(const {id} of roster)for(const facing of ['right','left'])test(`${id} simultaneous contacts trade without seat priority (${facing})`,()=>{const m=scene([id,id],false,facing);for(const i of [1,0])assert(performAction(m,i,'low-punch'));advance(m,400);assert(m.fighters.every(f=>f.hp<f.maxHp));assert.deepEqual(consumeEvents(m).filter(e=>e.type==='hit').map(e=>e.attacker).sort(),[0,1]);});
for(const fastSeat of [0,1])test(`earlier physical light contact interrupts a slower strike from seat ${1-fastSeat}`,()=>{const m=scene();performAction(m,fastSeat,'low-punch');performAction(m,1-fastSeat,'kick');advance(m,400);assert.equal(m.fighters[fastSeat].hp,m.fighters[fastSeat].maxHp);assert(m.fighters[1-fastSeat].hp<m.fighters[1-fastSeat].maxHp);});
test('simultaneous lethal strikes draw rather than award either seat',()=>{const m=scene();m.fighters.forEach(f=>f.hp=1);performAction(m,0,'punch');performAction(m,1,'punch');advance(m,400);assert.equal(m.phase,'over');assert.equal(m.winner,null);assert(m.fighters.every(f=>f.hp===0));});
const pad=(held=[],axes=[0,0])=>({index:0,id:'DualSense',mapping:'standard',connected:true,axes,buttons:Array.from({length:17},(_,i)=>({pressed:held.includes(i),value:held.includes(i)?1:0}))});
for(const direction of [-1,1])for(const source of ['stick','dpad'])test(`PS5 ${source} Up then horizontal in the next sample produces directional jump ${direction}`,()=>{const adapter=createGamepadInput();adapter.sample([pad()],0);const m=scene();let r=adapter.sample([source==='stick'?pad([],[0,-.7]):pad([12])],1);for(const event of r.events.filter(e=>e.type==='press'))performAction(m,event.player,event.action,r.players[event.player]);advance(m,20,r.players);r=adapter.sample([source==='stick'?pad([],[direction*.7,-.7]):pad([12,direction>0?15:14])],21);advance(m,60,r.players);assert(Math.sign(m.fighters[0].x-1200)===direction);assert.equal(m.fighters[0].action,'jump');});
test('horizontal motion never starts a jump and late input cannot reverse an established jump',()=>{const m=scene();advance(m,20,[{move:1},{}]);assert.equal(m.fighters[0].action,'walk');performAction(m,0,'jump',{move:1});advance(m,120,[{move:1},{}]);const x=m.fighters[0].x;advance(m,50,[{move:-1},{}]);assert(m.fighters[0].x>x);});
for(const {id} of roster)for(const facing of ['right','left'])for(const action of ['low-punch','punch'])test(`${id} repeated corner ${action} leave a real guard opportunity (${facing})`,()=>{const m=scene([id,id],true,facing),dir=facing==='right'?1:-1;m.fighters[1].x=dir>0?2350:210;m.fighters[0].x=m.fighters[1].x-dir*150;m.fighters.forEach(f=>{f.hp=1000;f.maxHp=1000;});let hits=0,blocks=0,escaped=false;for(let t=0;t<6000;t+=10){performAction(m,0,action,{move:dir});advanceMatch(m,10,[{move:dir},{block:hits>0}]);for(const e of consumeEvents(m)){if(e.type==='hit')hits++;if(e.type==='block')blocks++;}if(hits>0&&['idle','block','crouch','walk'].includes(m.fighters[1].action))escaped=true;}if(hits===0)return;assert(escaped,'Wall pressure must not refresh stun forever');assert(hits<8,'A held defense cannot lose to unlimited one-button repetition');});
for(const {id} of roster)for(const facing of ['right','left'])test(`${id} native captured body lifts, releases and lands without floor travel (${facing})`,()=>{const dir=facing==='right'?1:-1;let m;for(let gap=65;gap<=300;gap+=5){const candidate=scene([id,id],true,facing);candidate.fighters[1].x=1200+dir*gap;performAction(candidate,0,'grab');advance(candidate,230);if(candidate.fighters[1].action==='grabbed'){m=candidate;break;}}assert(m,'The actual native palm must first capture a legally separated own opponent');const attacker=m.fighters[0],victim=m.fighters[1],lift=attacker._clips[getFighterView(m,0).clip].liftMs;while(attacker.actionTime<lift+20)advance(m,5);assert(getFighterView(m,1).y<0,'Captured whole body must be visibly lifted');for(let t=0;t<1000&&victim.action==='grabbed';t+=5){assert(getFighterView(m,1).y<0,'The captured native body stays raised until its actual release');advance(m,5);}assert.equal(victim.action,'thrown');const launch=getFighterView(m,1);assert(launch.y<0&&launch.airborne);let landX=null;for(let t=0;t<1100;t+=10){advance(m,10);const v=getFighterView(m,1);const floorX=v.x+(victim._clips[v.clip]?.endOffsetX?.[v.facing]??0);if(v.y===0&&landX===null)landX=floorX;if(landX!==null&&['thrown','knockdown'].includes(victim.action))assert(Math.abs(floorX-landX)<.001,'The landed body cannot continue sliding through its flight');}assert.notEqual(landX,null);assert.equal(consumeEvents(m).filter(e=>e.type==='land'&&e.target===1).length,1);});
for(const facing of ['right','left'])test(`a heavy power kick sends the intact body backward through an air arc (${facing})`,()=>{const m=scene(['9-bit','9-bit'],false,facing),dir=facing==='right'?1:-1;performAction(m,0,'power-kick');advance(m,400);assert.equal(m.fighters[1].action,'thrown');assert(getFighterView(m,1).y<0);assert((m.fighters[1].x-(1200+dir*106))*dir>0);});

function equip(m,index,type='pulse-driver'){m.fighters[index].weapon={id:'test-weapon-'+index,type,name:type,charges:3};}
for(const firstSeat of [0,1])test('simultaneous lethal pulse shots draw regardless of input order '+firstSeat,()=>{const m=scene();m.fighters.forEach(f=>f.hp=1);equip(m,0);equip(m,1);performAction(m,firstSeat,'punch');performAction(m,1-firstSeat,'punch');advance(m,400);assert.equal(m.phase,'over');assert.equal(m.winner,null);assert(m.fighters.every(f=>f.hp===0));assert(m.fighters.every(f=>f.weapon.charges===2));});
for(const seat of [0,1])test('weapon input mashing consumes one charge per committed release for seat '+seat,()=>{const m=scene();m.fighters[1-seat].x=m.fighters[seat].x+(seat===0?600:-600);equip(m,seat);performAction(m,seat,'punch');for(let t=0;t<350;t+=10){performAction(m,seat,'punch');advance(m,10);}assert.equal(m.fighters[seat].weapon.charges,2);assert.equal(consumeEvents(m).filter(e=>e.type==='weapon-use').length,1);});
for(const seat of [0,1])test('interrupting a weapon before release retains its charge for seat '+seat,()=>{const m=scene();equip(m,seat);performAction(m,seat,'punch');performAction(m,1-seat,'low-punch');advance(m,400);assert.equal(m.fighters[seat].weapon.charges,3);assert.equal(consumeEvents(m).filter(e=>e.type==='weapon-use').length,0);});

for(const facing of ['right','left'])for(const firstSeat of [0,1])test('simultaneous grabs clash without capture or damage '+facing+' order'+firstSeat,()=>{const m=scene(['6-bit','6-bit'],false,facing),positions=m.fighters.map(f=>f.x);performAction(m,firstSeat,'grab');performAction(m,1-firstSeat,'grab');advance(m,220);assert(m.fighters.every(f=>f.hp===f.maxHp));assert(m.fighters.every(f=>f.action==='grab'));assert(m.fighters.every(f=>Math.abs(f.x-positions[m.fighters.indexOf(f)])>=20));assert.equal(consumeEvents(m).filter(e=>e.type==='throw').length,0);advance(m,800);assert(m.fighters.every(f=>f.action==='idle'));});

for(const {id}of roster)for(const facing of ['right','left'])test(id+' native body throw reaches a damaged connecting wall once '+facing,()=>{const m=scene([id,id],true,facing,'radio-studio'),dir=facing==='right'?1:-1,attacker=m.fighters[0],victim=m.fighters[1],side=dir>0?'right':'left';m.stage.walls[side].damage=70;victim.x=dir>0?2350:210;attacker.x=dir>0?2340:220;performAction(m,0,'grab');attacker._contactDone=true;attacker.actionTime=attacker._clips.grab?.contactMs??180*attacker._style.tempo.throw;victim.action='grabbed';victim.actionTime=0;victim._throwDirection=dir;victim._throwAttacker=0;victim._throwDistance=attacker._style.throwDistance;victim._grabHold={attacker:0,duration:(attacker._clips.grab?.releaseMs??480*attacker._style.tempo.throw)-attacker.actionTime,startX:victim.x,startY:0,y:0};advance(m,1400);assert.equal(m.stage.id,dir>0?'sheila-office':'studio-rat-lair');const events=consumeEvents(m);assert.equal(events.filter(e=>e.type==='wall-impact').length,1);assert.equal(events.filter(e=>e.type==='stage-transition').length,1);assert(m.fighters.every(f=>f.x>=210&&f.x<=2350));});

for(const weaponSeat of [0,1])test('same-time weapon and unarmed contact retain both physical results '+weaponSeat,()=>{const m=scene();equip(m,weaponSeat,'neural-spike');performAction(m,0,'punch');performAction(m,1,'punch');advance(m,300);assert.equal(m.fighters[weaponSeat].hp,m.fighters[weaponSeat].maxHp-8);assert.equal(m.fighters[1-weaponSeat].hp,m.fighters[1-weaponSeat].maxHp-16);assert.equal(m.fighters[weaponSeat].weapon.charges,2);const hits=consumeEvents(m).filter(e=>e.type==='hit');assert.equal(hits.length,2);assert.equal(hits.find(e=>e.attacker===weaponSeat).damageKind,'cut');assert.equal(hits.find(e=>e.attacker!==weaponSeat).damageKind,'bruise');});

for(const seat of [0,1])test('a jump enters the last contact step before either seat measures it '+seat,()=>{const m=scene(),attacker=m.fighters[seat],victim=m.fighters[1-seat],dir=seat===0?1:-1;attacker.x=1000;victim.x=1000+dir*180.1;victim.action='jump';victim._jump={elapsed:0,duration:580,move:-dir,attackUsed:false};attacker._clips.punch.contactMs=170;attacker._clips.punch.activeEndMs=170;performAction(m,seat,'punch');attacker.actionTime=169;advanceMatch(m,1);assert.equal(consumeEvents(m).filter(e=>e.type==='hit').length,1,'Both motions must advance before contact at the exact active boundary');});

for(const ids of [...roster.map(f=>[f.id,f.id==='doofnoobler'?'9-bit':'doofnoobler']),['doofnoobler','papa-oak']])for(const facing of ['right','left'])test('actual native contextual grab captures and lifts '+ids.join(' to ')+' '+facing,()=>{let captured;const dir=facing==='right'?1:-1;for(let gap=80;gap<=300;gap+=5){const m=scene(ids,true,facing);m.fighters[1].x=1200+dir*gap;performAction(m,0,'grab');advance(m,230);if(m.fighters[1].action==='grabbed'){captured=m;break;}}assert(captured,'At least one legally body-separated native grip must capture this height matchup');advance(captured,200);assert(getFighterView(captured,1).y<0,'Actual captured whole body rises with the actual visible grip');advance(captured,400);assert(consumeEvents(captured).some(e=>e.type==='throw'&&e.target===1));});

for(const {id}of roster)for(const facing of ['right','left'])test(id+' actual native ordinary grip captures a physical opponent '+facing,()=>{let captured;const dir=facing==='right'?1:-1;for(let gap=65;gap<=300;gap+=5){const m=scene([id,id],true,facing);m.fighters[1].x=1200+dir*gap;performAction(m,0,'grab');advance(m,230);if(m.fighters[1].action==='grabbed'){captured=m;break;}}assert(captured,'The real native grip must be reachable after physical body push');advance(captured,200);assert(getFighterView(captured,1).y<0||captured.fighters[1].action==='thrown');advance(captured,500);assert(consumeEvents(captured).some(e=>e.type==='throw'&&e.target===1));});

test('a distant projectile wall hit cannot drag its shooter backward',()=>{const m=scene();m.fighters[0].x=1200;m.fighters[1].x=2350;equip(m,0);performAction(m,0,'punch');advance(m,1500);assert(m.fighters[1].hp<m.fighters[1].maxHp);assert.equal(m.fighters[0].x,1200);});

for(const facing of ['right','left'])test('native held body stays above the floor through the exact release '+facing,()=>{let m;const dir=facing==='right'?1:-1;for(let gap=65;gap<=300;gap+=5){const candidate=scene(['6-bit','9-bit'],true,facing);candidate.fighters[1].x=1200+dir*gap;performAction(candidate,0,'grab');advance(candidate,230);if(candidate.fighters[1].action==='grabbed'){m=candidate;break;}}assert(m);const release=m.fighters[0]._clips.grab.releaseMs;let before=false,after=false;for(let t=0;t<500;t++){advance(m,1);const time=m.fighters[0].actionTime;if(time>=release-2&&time<=release+2){assert(getFighterView(m,1).y<0,'The raised native body cannot touch the floor between lift and release');before||=time<release;after||=time>=release;}}assert(before&&after);});

for(const {id}of roster)for(const facing of ['right','left'])test(id+' actual simultaneous native punches trade at reachable spacing '+facing,()=>{let trade=false;const dir=facing==='right'?1:-1;for(let gap=65;gap<=300;gap+=5){const m=scene([id,id],true,facing);m.fighters[1].x=1200+dir*gap;performAction(m,1,'punch');performAction(m,0,'punch');advance(m,400);if(consumeEvents(m).filter(e=>e.type==='hit').length===2){trade=true;assert(m.fighters.every(f=>f.hp<f.maxHp));break;}}assert(trade,'Both actual native fists must retain an equal-time physical hit when they reach');});
for(const {id}of roster)for(const fastSeat of [0,1])test(id+' earlier native light contact interrupts a slower native strike from seat '+(1-fastSeat),()=>{let connected=false;for(let gap=65;gap<=300;gap+=5){const m=scene([id,id],true);m.fighters[1].x=1200+gap;const slower=['punch','kick','power-kick'].find(action=>m.fighters[0]._clips[action].contactMs>m.fighters[0]._clips['low-punch'].contactMs);assert(slower);performAction(m,1-fastSeat,slower);performAction(m,fastSeat,'low-punch');advance(m,400);const hits=consumeEvents(m).filter(e=>e.type==='hit');if(hits.some(e=>e.attacker===fastSeat)){connected=true;assert.equal(m.fighters[fastSeat].hp,m.fighters[fastSeat].maxHp);assert.equal(hits.length,1);break;}}assert(connected,'The test needs a genuine reachable native light contact');});
for(const {id}of roster)for(const facing of ['right','left'])test(id+' actual native grip throws into a damaged connecting wall '+facing,()=>{let crossed=false;const dir=facing==='right'?1:-1,side=dir>0?'right':'left';for(let gap=65;gap<=300;gap+=5){const m=scene([id,id],true,facing,'radio-studio');m.stage.walls[side].damage=70;m.fighters[1].x=dir>0?2350:210;m.fighters[0].x=m.fighters[1].x-dir*gap;performAction(m,0,'grab');advance(m,230);if(m.fighters[1].action!=='grabbed')continue;advance(m,1800);if(m.stage.id!=='radio-studio'){const events=consumeEvents(m);assert.equal(events.filter(e=>e.type==='wall-impact').length,1);assert.equal(events.filter(e=>e.type==='stage-transition').length,1);assert.equal(events.filter(e=>e.type==='land'&&e.target===1).length,1);crossed=true;break;}}assert(crossed,'A real captured body within throwing distance must physically reach the damaged wall');});
