import test from 'node:test';
import assert from 'node:assert/strict';
import Module,{createRequire} from 'node:module';
import fs from 'node:fs';
import ts from 'typescript';
const require=createRequire(import.meta.url);
Module._extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const file=new URL('../src/lib/system-clash-voice.ts',import.meta.url);
const implementation=fs.existsSync(file)?require(file.pathname.replace(/^\/([A-Za-z]:)/,'$1')):{};
const make=implementation.createTournamentVoiceService??(()=>({status:async()=>({}),publish:async()=>({}),subscribe:async()=>({}),answer:async()=>({}),ready:async()=>({}),heartbeat:async()=>({}),close:async()=>({})}));
const offer={type:'offer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=mid:0\r\na=sendonly\r\n'};
const answer={type:'answer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=mid:0\r\na=recvonly\r\n'};
function fixture(enabled=true){
 const actor=id=>({id,name:id,sessionExpiresAt:9999999});
 let ctx={code:'ABCDEF',status:'running',currentBoutId:'bout-1',hostMemberId:'host',bout:{id:'bout-1',status:'live',roomCode:'ROOMAA',roomMatchId:1,p1:'p1',p2:'p2'},entrants:[{id:'p1',memberId:'one',fighter:'6-bit'},{id:'p2',memberId:'two',fighter:'cliff'}]};
 let evidence={code:'ROOMAA',matchId:1,matchPhase:'match',hostMemberId:'one',guestMemberId:'two',hostFighter:'6-bit',guestFighter:'cliff',tournament:{code:'ABCDEF',boutId:'bout-1'}};
 const sessions=new Map(),pubs=new Map(),calls=[];let n=0,time=1000,afterCall=null,transform=v=>v,closeFailure=false,contextWait=null;
 const resources={read:async h=>sessions.has(h)?structuredClone(sessions.get(h)):null,write:async(h,v)=>{sessions.set(h,structuredClone(v));},remove:async h=>sessions.delete(h),renew:async(value,activate=false)=>{const current=sessions.get(value.handle);if(!current||current.closing)return false;const updated={...structuredClone(current),updatedAt:Math.max(current.updatedAt,value.updatedAt),...(value.mids.length?{mids:[...value.mids]}:{}),...(activate?{ready:true}:{})};sessions.set(value.handle,updated);if(updated.kind==="publish"&&updated.ready)pubs.set(updated.binding+":"+updated.entrantId,structuredClone(updated));return true;},beginClose:async(value)=>{const current=sessions.get(value.handle);if(!current)return null;const closing={...structuredClone(current),closing:true,ready:false};sessions.set(value.handle,closing);const key=current.binding+":"+current.entrantId;if(pubs.get(key)?.handle===value.handle)pubs.delete(key);return structuredClone(closing);},publications:async key=>[...pubs.values()].filter(p=>p.binding===key),putPublication:async p=>{pubs.set(p.binding+':'+p.entrantId,structuredClone(p));},removePublication:async p=>{const key=p.binding+':'+p.entrantId;if(pubs.get(key)?.handle===p.handle)pubs.delete(key);}};
 const provider={enabled,async request(path,method='POST',body){calls.push({path,method,body});if(afterCall)afterCall();if(path==='sessions/new')return{sessionId:'session-'+(++n)};if(path.endsWith('tracks/close')&&closeFailure)throw new Error('temporary close failure');if(path.endsWith('tracks/new'))return transform({sessionDescription:body.sessionDescription?answer:{type:'offer',sdp:answer.sdp},tracks:body.tracks.map((t,i)=>({...t,mid:t.mid??String(i)}))});return{};}};
 const service=make({provider,resources,readContext:async()=>{if(contextWait){const wait=contextWait;contextWait=null;await wait;}return structuredClone(ctx)},readMatch:async()=>structuredClone(evidence),now:()=>time,id:()=>('00000000-0000-4000-8000-'+String(++n).padStart(12,'0'))});
 return{service,actor,calls,sessions,pubs,setContext:v=>ctx=v,setEvidence:v=>evidence=v,getContext:()=>structuredClone(ctx),getEvidence:()=>structuredClone(evidence),setTime:v=>time=v,afterCall:v=>afterCall=v,setTransform:v=>transform=v,setCloseFailure:v=>closeFailure=v,holdContext:()=>{let release;contextWait=new Promise(r=>release=r);return release;}};
}
test('missing SFU activation returns unavailable and never allocates media',async()=>{const f=fixture(false);assert.equal((await f.service.status('ABCDEF',f.actor('one'))).available,false);await assert.rejects(()=>f.service.publish({code:'ABCDEF',offer,mid:'0'},f.actor('one')),e=>e.status===503);assert.equal(f.calls.length,0);});
test('only two assigned fighters in the exact live room can publish',async()=>{const f=fixture();await assert.rejects(()=>f.service.publish({code:'ABCDEF',offer,mid:'0'},f.actor('host')),e=>e.status===403);f.setEvidence({...f.getEvidence(),tournament:{code:'OTHER1',boutId:'bout-1'}});await assert.rejects(()=>f.service.publish({code:'ABCDEF',offer,mid:'0'},f.actor('one')),e=>e.status===409);assert.equal(f.calls.length,0);});
test('publication stays undiscoverable until connected and never exposes SFU locators',async()=>{const f=fixture(),a=f.actor('one'),p=await f.service.publish({code:'ABCDEF',offer,mid:'0'},a);assert.ok(p.handle);assert.equal((await f.service.status('ABCDEF',f.actor('viewer'))).speakers.length,0);await f.service.ready({code:'ABCDEF',handle:p.handle},a);const status=await f.service.status('ABCDEF',f.actor('viewer'));assert.deepEqual(status.speakers.map(s=>s.entrantId),['p1']);assert.ok(!JSON.stringify(status).includes('session-'));assert.ok(!JSON.stringify(p).includes('session-'));});
test('subscriber gets server chosen publications and another member cannot answer its session',async()=>{const f=fixture(),p=await f.service.publish({code:'ABCDEF',offer,mid:'0'},f.actor('one'));await f.service.ready({code:'ABCDEF',handle:p.handle},f.actor('one'));const sub=await f.service.subscribe({code:'ABCDEF'},f.actor('viewer'));assert.equal(sub.tracks[0].entrantId,'p1');assert.ok(!JSON.stringify(sub).includes('session-'));await assert.rejects(()=>f.service.answer({code:'ABCDEF',handle:sub.handle,answer},f.actor('other')),e=>e.status===403);await f.service.answer({code:'ABCDEF',handle:sub.handle,answer},f.actor('viewer'));assert.equal(f.calls.at(-1).method,'PUT');assert.ok(f.calls.at(-1).path.endsWith('/renegotiate'));});
test('foreign track selectors and nonaudio SDP fail before SFU allocation',async()=>{const f=fixture();await assert.rejects(()=>f.service.subscribe({code:'ABCDEF',sessionId:'foreign',tracks:[]},f.actor('viewer')),e=>e.status===400);await assert.rejects(()=>f.service.publish({code:'ABCDEF',offer:{type:'offer',sdp:offer.sdp+'m=video 9 UDP/TLS/RTP/SAVPF 96\r\n'},mid:'0'},f.actor('one')),e=>e.status===400);assert.equal(f.calls.length,0);});
test('ended match cannot renew or pull but owner cleanup still closes its tracks',async()=>{const f=fixture(),a=f.actor('one'),p=await f.service.publish({code:'ABCDEF',offer,mid:'0'},a);await f.service.ready({code:'ABCDEF',handle:p.handle},a);f.setEvidence({...f.getEvidence(),matchPhase:'over'});await assert.rejects(()=>f.service.heartbeat({code:'ABCDEF',handle:p.handle},a),e=>e.status===409);await assert.rejects(()=>f.service.subscribe({code:'ABCDEF'},f.actor('viewer')),e=>e.status===409);await f.service.close({code:'ABCDEF',handle:p.handle},a);assert.equal(f.pubs.size,0);assert.equal(f.calls.at(-1).body.force,true);assert.deepEqual(f.calls.at(-1).body.tracks,[{mid:'0'}]);});
test('match change during a provider request withdraws the newly allocated voice',async()=>{const f=fixture();f.afterCall(()=>f.setContext({...f.getContext(),status:'paused'}));await assert.rejects(()=>f.service.publish({code:'ABCDEF',offer,mid:'0'},f.actor('one')),e=>e.status===409);assert.equal(f.pubs.size,0);});

test('partially successful subscriptions close allocated tracks before rejecting the voice',async()=>{const f=fixture();for(const id of ['one','two']){const p=await f.service.publish({code:'ABCDEF',offer,mid:'0'},f.actor(id));await f.service.ready({code:'ABCDEF',handle:p.handle},f.actor(id));}f.setTransform(v=>({...v,tracks:v.tracks.map((t,i)=>i===1?{errorCode:'track_unavailable'}:t)}));await assert.rejects(()=>f.service.subscribe({code:'ABCDEF'},f.actor('viewer')),e=>e.status===503);assert.deepEqual(f.calls.at(-1).body,{tracks:[{mid:'0'}],force:true});});
test('failed SFU closure retains private cleanup identifiers and retry succeeds',async()=>{const f=fixture(),a=f.actor('one'),p=await f.service.publish({code:'ABCDEF',offer,mid:'0'},a);await f.service.ready({code:'ABCDEF',handle:p.handle},a);f.setCloseFailure(true);await assert.rejects(()=>f.service.close({code:'ABCDEF',handle:p.handle},a));assert.equal(f.pubs.size,0);assert.ok(f.sessions.has(p.handle));await assert.rejects(()=>f.service.ready({code:'ABCDEF',handle:p.handle},a),e=>e.status===409);f.setCloseFailure(false);await f.service.close({code:'ABCDEF',handle:p.handle},a);assert.ok(!f.sessions.has(p.handle));});

for(const action of ['ready','heartbeat'])test('closing wins against an in-flight '+action+' and cannot resurrect publication',async()=>{const f=fixture(),a=f.actor('one'),p=await f.service.publish({code:'ABCDEF',offer,mid:'0'},a);if(action==='heartbeat')await f.service.ready({code:'ABCDEF',handle:p.handle},a);const release=f.holdContext(),pending=f.service[action]({code:'ABCDEF',handle:p.handle},a);await new Promise(r=>setImmediate(r));await f.service.close({code:'ABCDEF',handle:p.handle},a);release();await assert.rejects(()=>pending,e=>e.status===409);assert.equal(f.pubs.size,0);assert.ok(!f.sessions.has(p.handle));});
