import test from 'node:test';
import assert from 'node:assert/strict';
import {createLoungeTracker} from '../public/games/system-clash/play/tournament-lounge.mjs';
const snapshot=(revision,overrides={})=>({code:'ABC123',revision,status:'lobby',round:0,entrants:[{id:'a',fighter:'6-bit',name:'A',status:'approved',ready:false},{id:'b',fighter:'cache-back',name:'B',status:'approved',ready:false}],bouts:[],currentBoutId:null,championId:null,...overrides});
test('hydration and presence-only snapshots never replay stack sounds',()=>{const t=createLoungeTracker();assert.deepEqual(t.update(snapshot(1)),[]);assert.deepEqual(t.update(snapshot(2)),[]);const s=snapshot(3);s.entrants.push({id:'c',status:'pending',fighter:'cliff'});assert.deepEqual(t.update(s).map(e=>e.type),['join']);assert.deepEqual(t.update(s),[]);});
test('confirmed draw uses actual server pairing slots including rotating byes',()=>{const t=createLoungeTracker();t.update(snapshot(1));const drawn=snapshot(2,{status:'running',round:1,bouts:[{id:'r1',round:1,p1:'b',p2:'a',status:'pending'}]});assert.deepEqual(t.update(drawn).map(({type,entrantId,boutId,slot})=>({type,entrantId,boutId,slot})),[{type:'draw',entrantId:'b',boutId:'r1',slot:0},{type:'draw',entrantId:'a',boutId:'r1',slot:1}]);assert.deepEqual(t.update({...drawn,revision:3}),[]);});
test('new survival round moves every surviving block once; completed champion sounds once',()=>{const t=createLoungeTracker();const first=snapshot(2,{status:'running',round:1,bouts:[{id:'r1',round:1,p1:'a',p2:'b',status:'complete',winner:'a'}]});t.update(first);const next={...first,revision:3,round:2,bouts:[...first.bouts,{id:'r2',round:2,p1:'b',p2:'a',status:'pending'}]};assert.deepEqual(t.update(next).map(e=>e.type),['advance','advance']);const complete={...next,revision:4,status:'complete',championId:'a'};assert.deepEqual(t.update(complete).map(e=>e.type),['champion']);assert.deepEqual(t.update({...complete,revision:5}),[]);});
test('old responses and different tournament hydration cannot manufacture transitions',()=>{const t=createLoungeTracker();t.update(snapshot(8));assert.deepEqual(t.update(snapshot(7,{entrants:[{id:'x',status:'pending'}]})),[]);assert.deepEqual(t.update(snapshot(1,{code:'OTHER1',entrants:[{id:'x',status:'pending'}]})),[]);assert.deepEqual(t.update(snapshot(2,{code:'OTHER1',entrants:[{id:'x',status:'pending'}]})),[]);});
test('ready and match call cues only occur on meaningful changes, withdrawn rows do not restack',()=>{const t=createLoungeTracker();t.update(snapshot(1));const ready=snapshot(2);ready.entrants[0].ready=true;assert.deepEqual(t.update(ready).map(e=>e.type),['ready']);const live={...ready,revision:3,currentBoutId:'r1',bouts:[{id:'r1',round:1,p1:'a',p2:'b',status:'ready'}]};assert.deepEqual(t.update(live).map(e=>e.type),['draw','draw','call']);assert.deepEqual(t.update({...live,revision:4}),[]);});
