import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync,statSync} from 'node:fs';
import {createHash} from 'node:crypto';
const music=await import('../public/games/system-clash/play/game-music.mjs').catch(()=>({}));
const root=new URL('../public/games/system-clash/play/',import.meta.url);
const manifest={tracks:{title:{file:'assets/audio/music/title.mp3'},select:{file:'assets/audio/music/select.mp3'},online:{file:'assets/audio/music/online.mp3'},tournament:{file:'assets/audio/music/tournament.mp3'},six:{file:'assets/audio/music/6-bit.mp3'},lyraA:{file:'assets/audio/music/lyra-a.mp3'},lyraB:{file:'assets/audio/music/lyra-b.mp3'},radio:{file:'assets/audio/music/radio.mp3'}},menus:{title:'title',select:'select',online:'online',tournament:'tournament'},fighters:{'6-bit':['six'],lyra:['lyraA','lyraB']},stages:{'radio-studio':'radio'}};
class Events{listeners=new Map();addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,new Set());this.listeners.get(type).add(fn);}removeEventListener(type,fn){this.listeners.get(type)?.delete(fn);}emit(type,event={}){for(const fn of this.listeners.get(type)??[])fn(event);}}
class Timers{now=0;id=0;jobs=new Map();setTimeout=(fn,ms)=>{const id=++this.id;this.jobs.set(id,{fn,at:this.now+ms});return id;};clearTimeout=id=>this.jobs.delete(id);advance(ms){const target=this.now+ms;while(true){const next=[...this.jobs].sort((a,b)=>a[1].at-b[1].at)[0];if(!next||next[1].at>target)break;this.now=next[1].at;this.jobs.delete(next[0]);next[1].fn();}this.now=target;}}
function fixture({parent,blocked=false,fadeMs=0,catalog=manifest}={}){const doc=new Events();doc.hidden=false;doc.documentElement={dataset:parent?{}:{systemClashHost:'1'}};const win=new Events(),timers=new Timers(),audios=[];class Media extends Events{volume=0;currentTime=0;paused=true;muted=false;assignments=[];plays=0;set src(value){this.assignments.push(value);this.source=value;}get src(){return this.source;}play(){this.plays++;if(blocked)return Promise.reject(Error('gesture required'));this.paused=false;return Promise.resolve();}pause(){this.paused=true;}removeAttribute(name){if(name==='src')this.source='';}load(){}}
 Object.assign(win,{location:{href:'https://game.test/online.html'},document:doc,Audio:class extends Media{constructor(){super();audios.push(this);}},setTimeout:timers.setTimeout,clearTimeout:timers.clearTimeout,performance:{now:()=>timers.now}});win.parent=parent??win;
 assert.equal(typeof music.createGameMusic,'function','Music lifecycle is implemented');const player=music.createGameMusic({window:win,document:doc,manifest:catalog,fadeMs});return {player,win,doc,timers,audios};}
const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve();};
test('screen routing uses supplied menu, arena and own fighter themes with stage fallback',()=>{assert.equal(typeof music.resolveMusicTrack,'function');for(const [scene,want]of [[{screen:'title'},'title'],[{screen:'select'},'select'],[{screen:'online'},'online'],[{screen:'tournament'},'tournament'],[{screen:'arena',stage:'radio-studio'},'radio'],[{screen:'fight',fighter:'6-bit',stage:'radio-studio'},'six'],[{screen:'fight',fighter:'9-bit',stage:'radio-studio'},'radio'],[{screen:'fight',fighter:'lost-marbles',stage:'radio-studio'},'radio']])assert.equal(music.resolveMusicTrack(manifest,scene)?.id,want);});
test('Lyra variants are stable within one match and cycle between matches',()=>{assert.equal(typeof music.resolveMusicTrack,'function');assert.equal(music.resolveMusicTrack(manifest,{screen:'fight',fighter:'lyra',variant:0}).id,'lyraA');assert.equal(music.resolveMusicTrack(manifest,{screen:'fight',fighter:'lyra',variant:1}).id,'lyraB');assert.equal(music.resolveMusicTrack(manifest,{screen:'fight',fighter:'lyra',variant:2}).id,'lyraA');});
test('only the selected track loads and render repeats do not restart playback',async()=>{const f=fixture();f.player.setScene({screen:'title'});await flush();assert.equal(f.audios.length,1);assert.deepEqual(f.audios[0].assignments,['https://game.test/assets/audio/music/title.mp3']);assert.equal(f.audios[0].plays,0);await f.player.unlock();f.audios[0].currentTime=17;for(let i=0;i<50;i++)f.player.setScene({screen:'title'});await flush();assert.equal(f.audios[0].plays,1);assert.equal(f.audios[0].currentTime,17);assert.equal(f.audios[0].loop,true);f.player.destroy();});
test('mute and pause resume the selected music without rewinding it',async()=>{const f=fixture();f.player.setScene({screen:'fight',fighter:'6-bit'});await f.player.unlock();const audio=f.audios[0];audio.currentTime=23;f.player.setMuted(true);assert.equal(audio.paused,true);f.player.setMuted(false);await flush();assert.equal(audio.paused,false);f.player.setPaused(true);assert.equal(audio.paused,true);f.player.setPaused(false);await flush();assert.equal(audio.paused,false);assert.equal(audio.currentTime,23);assert.equal(audio.assignments.length,1);assert(audio.volume>0&&audio.volume<.5);f.player.destroy();});
test('hidden and suspended screens stop music, then resume their existing position',async()=>{const f=fixture();f.player.setScene({screen:'online'});await f.player.unlock();const audio=f.audios[0];audio.currentTime=9;f.doc.hidden=true;f.doc.emit('visibilitychange');assert.equal(audio.paused,true);f.doc.hidden=false;f.doc.emit('visibilitychange');await flush();assert.equal(audio.paused,false);f.player.suspend();assert.equal(audio.paused,true);f.player.resume();await flush();assert.equal(audio.paused,false);assert.equal(audio.currentTime,9);f.player.destroy();});
test('nested screens share one audio owner and dormant parents cannot stop the active child',async()=>{const parent=fixture();parent.player.setScene({screen:'title'});await parent.player.unlock();const child=fixture({parent:parent.win});child.player.setScene({screen:'fight',fighter:'6-bit'});await flush();assert.equal(parent.audios.length,1);assert.equal(child.audios.length,0);const audio=parent.audios[0];assert.equal(audio.src,'https://game.test/assets/audio/music/6-bit.mp3');parent.player.suspend();assert.equal(audio.paused,false);child.player.setPaused(true);assert.equal(audio.paused,true);child.player.destroy();parent.player.setScene({screen:'title'});parent.player.resume();await flush();assert.equal(audio.paused,false);assert.equal(parent.audios.length,1);parent.player.destroy();});
test('a newer track selection cancels an older fade without briefly playing the abandoned track',async()=>{const f=fixture({fadeMs:120});f.player.setScene({screen:'title'});await f.player.unlock();f.timers.advance(120);f.player.setScene({screen:'select'});f.timers.advance(30);f.player.setScene({screen:'online'});f.timers.advance(400);await flush();f.timers.advance(120);assert.equal(f.audios[0].src,'https://game.test/assets/audio/music/online.mp3');assert(!f.audios[0].assignments.some(value=>value.endsWith('/select.mp3')));assert.equal(f.timers.jobs.size,0);f.player.destroy();});
test('blocked autoplay remains nonblocking and retries on a later real gesture',async()=>{const f=fixture({blocked:true});f.player.setScene({screen:'title'});assert.equal(await f.player.unlock(),false);assert.equal(f.audios[0].paused,true);f.doc.emit('pointerdown',{isTrusted:false});await flush();assert.equal(f.audios[0].plays,1);f.doc.emit('pointerdown',{isTrusted:true});await flush();assert.equal(f.audios[0].plays,2);f.player.destroy();});
test('music rejects external, traversal and unregistered track references',async()=>{for(const file of ['https://foreign.test/song.mp3','../song.mp3','assets/audio/music/../../song.mp3']){const bad={...manifest,tracks:{title:{file}}},f=fixture({catalog:bad});f.player.setScene({screen:'title'});await f.player.unlock();assert.equal(f.audios.length,0);f.player.destroy();}});
test('every retained soundtrack derivative has a unique safe file, stable source credit and exact bytes',async()=>{const file=new URL('assets/audio/music/manifest.mjs',root);assert(existsSync(file),'Processed soundtrack manifest exists');const {MUSIC_MANIFEST:m}=await import(file.href);assert.equal(Object.keys(m.tracks).length,24);assert.equal(Object.keys(m.fighters).length,13);assert.equal(m.fighters.lyra.length,2);assert.equal(Object.keys(m.stages).length,6);assert.equal(Object.keys(m.menus).length,4);const paths=new Set();for(const [id,track]of Object.entries(m.tracks)){assert.match(id,/^[a-z0-9-]+$/);assert.match(track.file,/^assets\/audio\/music\/[a-z0-9-]+\.mp3$/);assert(!paths.has(track.file));paths.add(track.file);const data=readFileSync(new URL(track.file,root));assert.equal(data.length,track.bytes);assert.equal(createHash('sha256').update(data).digest('hex'),track.sha256);assert.match(track.source,/^https:\/\/drive\.google\.com\/file\/d\/[A-Za-z0-9_-]+\/view$/);assert(track.duration>30);assert(track.loudness>=-19&&track.loudness<=-15);assert(track.truePeak<=-1);assert(statSync(new URL(track.file,root)).isFile());}});

test('render updates cannot keep restarting a pending track transition',async()=>{const f=fixture({fadeMs:120});f.player.setScene({screen:'title'});await f.player.unlock();f.timers.advance(120);f.player.setScene({screen:'select'});for(let i=0;i<4;i++){f.timers.advance(30);await flush();f.player.setScene({screen:'select'});}assert.equal(f.audios[0].src,'https://game.test/assets/audio/music/select.mp3');f.timers.advance(240);await flush();assert.equal(f.timers.jobs.size,0);f.player.destroy();});

test('the actual match audio pause hook pauses music alongside combat effects',async()=>{const f=fixture();f.player.setScene({screen:'fight',fighter:'6-bit'});await f.player.unlock();const source=readFileSync(new URL('fight.js',root),'utf8'),body=source.match(/function syncAudioPause\(\) \{([\s\S]*?)\n\}/)?.[1];assert(body);const calls=[],run=new Function('ready','screenSuspended','paused','inspectTime','motionTime','document','effects','music',body);run(true,false,true,null,null,{hidden:false},{setPaused:value=>calls.push(value)},f.player);assert.deepEqual(calls,[true]);assert.equal(f.audios[0].paused,true);run(true,false,false,null,null,{hidden:false},{setPaused(){}},f.player);await flush();assert.equal(f.audios[0].paused,false);f.player.destroy();});
