import test from 'node:test';
import assert from 'node:assert/strict';
const base='../public/games/system-clash/play/';
const protocol=await import(base+'online-protocol.mjs');
const transport=await import(base+'online-transport.mjs');
const bridgeModule=await import(base+'fight-online-bridge.mjs');
const lobby=await import(base+'online.mjs');
class Events {listeners=new Map();addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,new Set());this.listeners.get(type).add(fn);}removeEventListener(type,fn){this.listeners.get(type)?.delete(fn);}emit(type,props={}){for(const fn of [...(this.listeners.get(type)??[])])fn({type,...props});}}
class Timers {now=0;id=0;jobs=new Map();setTimeout=(fn,ms)=>{const id=++this.id;this.jobs.set(id,{fn,at:this.now+ms});return id;};clearTimeout=id=>this.jobs.delete(id);setInterval=(fn,ms)=>{const id=++this.id;this.jobs.set(id,{fn,at:this.now+ms,ms});return id;};clearInterval=id=>this.jobs.delete(id);advance(ms){this.now+=ms;for(const [id,j]of [...this.jobs])if(j.at<=this.now){if(j.ms)j.at=this.now+j.ms;else this.jobs.delete(id);j.fn();}}}
class Channel extends Events {constructor(label,options={}){super();this.label=label;this.ordered=options.ordered??true;this.maxRetransmits=options.maxRetransmits??null;this.readyState='connecting';this.bufferedAmount=0;this.sent=[];}send(data){this.sent.push(data);this.remote?.emit('message',{data});}open(){this.readyState='open';this.emit('open');}close(){this.readyState='closed';this.emit('close');}}
class Peer extends Events {channels=[];iceGatheringState='complete';connectionState='new';localDescription=null;remoteDescription=null;createDataChannel(label,options){const c=new Channel(label,options);this.channels.push(c);return c;}async createOffer(){return {type:'offer',sdp:'v=0\nhost'};}async createAnswer(){return {type:'answer',sdp:'v=0\nguest'};}async setLocalDescription(value){this.localDescription=value;}async setRemoteDescription(value){this.remoteDescription=value;}close(){this.connectionState='closed';}}
function peerPair({hostVersion,guestVersion}={}){const a=new Peer(),b=new Peer(),timers=new Timers(),received=[[],[]],disconnected=[[],[]],statuses=[[],[]],signals=[[],[]];const host=transport.createOnlinePeer({role:'host',room:'ABC123',peer:a,timers,now:()=>timers.now,version:hostVersion,onPacket:p=>received[0].push(p),onDisconnect:r=>disconnected[0].push(r),onStatus:s=>statuses[0].push(s),sendSignal:d=>signals[0].push(d)});const guest=transport.createOnlinePeer({role:'guest',room:'ABC123',peer:b,timers,now:()=>timers.now,version:guestVersion,onPacket:p=>received[1].push(p),onDisconnect:r=>disconnected[1].push(r),onStatus:s=>statuses[1].push(s),sendSignal:d=>signals[1].push(d)});for(const c of a.channels){const remote=new Channel(c.label,{ordered:c.ordered,maxRetransmits:c.maxRetransmits});c.remote=remote;remote.remote=c;b.emit('datachannel',{channel:remote});}function open(){for(const c of a.channels){c.remote.open();c.open();}}return {host,guest,a,b,timers,received,disconnected,statuses,signals,open};}
const input={move:1,crouch:false,block:true};
test('control schema rejects forged movement, unknown attacks and oversized snapshots',()=>{assert.equal(typeof protocol.validPayload,'function');assert.equal(protocol.validPayload({type:'input',input}),true);for(const packet of [{type:'input',input:{...input,move:20}},{type:'action',action:'steal-seat',input},{type:'pause',paused:'false'},{type:'snapshot',snapshot:{large:'x'.repeat(70000)}}])assert.equal(protocol.validPayload(packet),false);});
test('coordinator starts only after both loaded and starts once per match',()=>{const starts=[];const c=protocol.createFrameCoordinator({onStart:p=>starts.push(p),random:()=>.5});c.loaded('local');c.loaded('local');assert.equal(starts.length,0);c.loaded('remote');c.loaded('remote');assert.equal(starts.length,1);assert.equal(starts[0].type,'start');assert.ok(Number.isInteger(starts[0].seed));c.reset();c.loaded('remote');assert.equal(starts.length,1);c.loaded('local');assert.equal(starts.length,2);assert.notEqual(starts[0].matchId,starts[1].matchId);});
test('parent rejects messages from another window or origin',()=>{const source={};const router=protocol.createFrameRouter({origin:'https://game.test',source:()=>source,onPacket:p=>seen.push(p)}),seen=[];const data={scope:'system-clash-online-v1',payload:{type:'loaded'}};router({origin:'https://evil.test',source,data});router({origin:'https://game.test',source:{},data});router({origin:'https://game.test',source,data});assert.deepEqual(seen,[{type:'loaded'}]);});
test('child bridge stays disabled without an explicit online frame launch',()=>{const w=new Events();w.parent={postMessage(){throw new Error('must not send');}};const b=bridgeModule.createOnlineFightBridge({url:'https://game.test/fight.html',window:w});assert.equal(b.enabled,false);assert.equal(b.send({type:'loaded'}),false);b.destroy();});
test('child bridge admits only its matching parent and clears once on leave',()=>{const w=new Events(),sent=[],received=[],closed=[];w.parent={postMessage:(p,o)=>sent.push([p,o])};const b=bridgeModule.createOnlineFightBridge({url:'https://game.test/fight.html?online=1&seat=1',window:w,onPacket:p=>received.push(p),onDisconnect:r=>closed.push(r)});assert.equal(b.seat,1);b.send({type:'loaded'});assert.equal(sent[0][1],'https://game.test');const data={scope:'system-clash-online-v1',matchId:1,payload:{type:'pause',paused:true}};w.emit('message',{source:{},origin:'https://game.test',data});w.emit('message',{source:w.parent,origin:'https://evil.test',data});assert.equal(received.length,0);w.emit('message',{source:w.parent,origin:'https://game.test',data});assert.deepEqual(received,[{type:'pause',paused:true}]);w.emit('message',{source:w.parent,origin:'https://game.test',data:{scope:data.scope,matchId:1,payload:{type:'leave'}}});assert.equal(closed.length,1);b.destroy();});
test('host gathers an offer and guest answers each distinct offer once',async()=>{const p=peerPair();await p.host.start();assert.equal(p.signals[0][0].type,'offer');await Promise.all([p.guest.receiveDescription(p.signals[0][0]),p.guest.receiveDescription(p.signals[0][0])]);assert.equal(p.signals[1].length,1);await p.host.receiveDescription(p.signals[1][0]);assert.equal(p.a.remoteDescription.type,'answer');p.host.close();p.guest.close();});
test('peer readiness requires channels and matching version handshake',()=>{const p=peerPair();assert.equal(p.host.send({type:'input',input}),false);p.open();assert.ok(p.statuses.every(s=>s.includes('connected')));p.host.setMatchId(1);p.guest.setMatchId(1);assert.equal(p.guest.send({type:'input',input}),true);assert.deepEqual(p.received[0],[{type:'input',input}]);p.host.close();p.guest.close();});
test('an incompatible game version disconnects before gameplay',()=>{const p=peerPair({guestVersion:'old-engine'});p.open();assert.ok(p.disconnected.flat().some(r=>/version|refresh/i.test(r)));assert.equal(p.guest.send({type:'input',input}),false);p.host.close();p.guest.close();});
test('replayed reliable packets and old match inputs are discarded',()=>{const p=peerPair();p.open();p.host.setMatchId(1);p.guest.setMatchId(1);p.guest.send({type:'action',action:'punch',input});const c=p.a.channels.find(c=>c.label==='clash-control'),data=c.remote.sent.at(-1);c.emit('message',{data});assert.equal(p.received[0].length,1);p.host.setMatchId(2);c.emit('message',{data:JSON.stringify({...JSON.parse(data),seq:999})});assert.equal(p.received[0].length,1);p.host.close();p.guest.close();});
test('guest cannot publish authority snapshots and stale state is dropped',()=>{const p=peerPair();p.open();p.host.setMatchId(1);p.guest.setMatchId(1);assert.equal(p.guest.send({type:'snapshot',snapshot:{hp:999}}),false);p.host.send({type:'snapshot',snapshot:{hp:90}});const c=p.a.channels.find(c=>c.label==='clash-state');c.remote.emit('message',{data:c.sent.at(-1)});assert.deepEqual(p.received[1],[{type:'snapshot',snapshot:{hp:90}}]);p.host.close();p.guest.close();});
test('state backpressure drops a frame without an unbounded queue',()=>{const p=peerPair();p.open();const c=p.a.channels.find(c=>c.label==='clash-state');c.bufferedAmount=300000;const before=c.sent.length;assert.equal(p.host.send({type:'snapshot',snapshot:{hp:90}}),false);assert.equal(c.sent.length,before);assert.equal(p.disconnected.flat().length,0);p.host.close();p.guest.close();});
test('reliable backpressure ends the match instead of silently dropping controls',()=>{const p=peerPair();p.open();p.a.channels.find(c=>c.label==='clash-control').bufferedAmount=300000;assert.equal(p.host.send({type:'pause',paused:true}),false);assert.equal(p.disconnected[0].length,1);p.host.close();p.guest.close();});
test('closed channel or heartbeat loss clears the session once',()=>{const p=peerPair();p.open();const c=p.a.channels[0];c.close();c.emit('close');assert.equal(p.disconnected[0].length,1);p.guest.close();const q=peerPair();q.open();for(const c of q.a.channels){c.remote.remote=null;c.remote=null;}q.timers.advance(20000);assert.ok(q.disconnected[0].length);q.host.close();q.guest.close();});
test('room client keeps seat tokens in headers and never in GET room lists',async()=>{const calls=[];const client=lobby.createRoomClient({fetch:async(url,options)=>{calls.push([url,options]);return {ok:true,json:async()=>({ok:true})};}});client.setSeat({code:'ABC123',role:'host',token:'private-token'});await client.request('poll');await client.list();assert.deepEqual(JSON.parse(calls[0][1].body),{action:'poll',code:'ABC123'});assert.equal(calls[0][1].headers.Authorization,'Bearer private-token');assert.ok(!calls[1][1].headers?.Authorization);assert.equal(calls[1][1].body,undefined);});
test('room error preserves usable local play and JSON failures are bounded',async()=>{const client=lobby.createRoomClient({fetch:async()=>({ok:false,json:async()=>({error:'This session expired.'})})});await assert.rejects(client.request('join',{code:'ABC123',name:'Player'}),/expired/);});
test('fight frame URL carries chosen fighters/settings and omits credentials',()=>{const url=lobby.onlineFightURL('https://game.test/online.html',{role:'guest',token:'SECRET',code:'ABC123'},{host:{fighter:'6-bit',name:'A'},guest:{fighter:'9-bit',name:'B'}},{muted:true,reducedMotion:true,controllerSeats:[3,null],stage:'containment'});assert.equal(url.searchParams.get('seat'),'1');assert.equal(url.searchParams.get('pad1'),'3');assert.equal(url.searchParams.get('p2'),'9-bit');assert.equal(url.searchParams.get('sound'),'0');assert.equal(url.searchParams.get('stage'),'containment');assert.ok(!url.href.includes('SECRET'));assert.ok(!url.searchParams.has('code'));});
test('parent session starts authority only after both frames load and coordinates rematch',()=>{const sent=[],frames=[],loads=[];const fake={setMatchId:v=>sent.push({set:v}),send:p=>{sent.push(p);return true;}};const session=lobby.createOnlineSession({seat:{role:'host'},roomState:{host:{fighter:'6-bit',name:'A'},guest:{fighter:'9-bit',name:'B'}},peer:fake,postFrame:p=>frames.push(p),loadFrame:id=>loads.push(id)});session.connected();session.receiveFrame({type:'loaded'});assert.equal(frames.some(p=>p.type==='start'),false);session.receivePeer({type:'loaded'});assert.equal(frames.filter(p=>p.type==='start').length,1);session.receivePeer({type:'loaded'});assert.equal(frames.filter(p=>p.type==='start').length,1);session.receivePeer({type:'pause',paused:true});assert.deepEqual(frames.at(-1),{type:'pause',paused:true});session.receiveFrame({type:'snapshot',snapshot:{state:{phase:'over'}}});session.receivePeer({type:'rematch'});assert.deepEqual(loads,[1,2]);assert.ok(sent.some(p=>p.type==='rematch'&&p.matchId===2));session.receiveFrame({type:'loaded'});assert.equal(frames.filter(p=>p.type==='start').length,1);session.receivePeer({type:'loaded'});assert.equal(frames.filter(p=>p.type==='start').length,2);});
test('guest waits for host setup, then sends its own controls without authority state',()=>{const sent=[],frames=[],loads=[];const session=lobby.createOnlineSession({seat:{role:'guest'},roomState:{host:{fighter:'6-bit'},guest:{fighter:'9-bit'}},peer:{setMatchId(){},send:p=>sent.push(p)},postFrame:p=>frames.push(p),loadFrame:id=>loads.push(id)});session.connected();assert.deepEqual(loads,[]);session.receivePeer({type:'setup',stage:'containment'});assert.deepEqual(loads,[1]);session.receiveFrame({type:'loaded'});session.receivePeer({type:'start',matchId:1,seed:123});session.receiveFrame({type:'input',input});assert.deepEqual(sent.at(-1),{type:'input',input});session.receiveFrame({type:'snapshot',snapshot:{hp:99}});assert.equal(sent.at(-1).type,'input');session.receivePeer({type:'snapshot',snapshot:{hp:90}});assert.deepEqual(frames.at(-1),{type:'snapshot',snapshot:{hp:90}});});
test('old iframe messages cannot satisfy the new rematch loaded gate',()=>{const source={},seen=[];const router=protocol.createFrameRouter({origin:'https://game.test',source:()=>source,matchId:()=>2,onPacket:p=>seen.push(p)});const data={scope:'system-clash-online-v1',matchId:1,payload:{type:'loaded'}};router({origin:'https://game.test',source,data});assert.equal(seen.length,0);router({origin:'https://game.test',source,data:{...data,matchId:2}});assert.equal(seen.length,1);});
test('ICE gathering finishes after its bounded wait without hanging the offer',async()=>{const p=new Peer(),timers=new Timers(),signals=[];p.iceGatheringState='gathering';const t=transport.createOnlinePeer({role:'host',room:'ABC123',peer:p,timers,now:()=>timers.now,sendSignal:d=>signals.push(d)});const started=t.start();await Promise.resolve();await Promise.resolve();assert.equal(signals.length,0);timers.advance(8000);await started;assert.equal(signals.length,1);t.close();});

test('stage setup admits the six approved arenas and rejects unknown identifiers',()=>{assert.equal(protocol.validPayload({type:'setup',stage:'radio-studio'}),true);assert.equal(protocol.validPayload({type:'setup',stage:'witty-wasteland'}),true);assert.equal(protocol.validPayload({type:'setup',stage:'anything-else'}),false);const url=lobby.onlineFightURL('https://game.test/online.html',{role:'host'},{host:{fighter:'6-bit'},guest:{fighter:'9-bit'}},{stage:'anything-else'});assert.equal(url.searchParams.get('stage'),'radio-studio');});
test('leaving before frame readiness cannot later start a match',()=>{const sent=[],frames=[];const session=lobby.createOnlineSession({seat:{role:'host'},roomState:{host:{fighter:'6-bit'},guest:{fighter:'9-bit'}},peer:{setMatchId(){},send:p=>sent.push(p)},postFrame:p=>frames.push(p),loadFrame(){}});session.connected();session.receiveFrame({type:'loaded'});session.end('Gone');session.receivePeer({type:'loaded'});assert.equal(frames.some(p=>p.type==='start'),false);});
class Element extends Events {constructor(tagName='BUTTON'){super();this.tagName=tagName;this.children=[];this.dataset={};this.hidden=false;this.disabled=false;this.value='';this.checked=false;this.attributes={};this.contentWindow={postMessage(){},focus(){this.focused=true;}};}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=[...items];}querySelectorAll(selector){return this.children.filter(c=>selector==='button'&&c.tagName==='BUTTON');}closest(){return null;}focus(){this.focused=true;}click(){this.emit('click');}}
async function mountedLobby({listWait,createWait,pollWait,createSeats,selectWait,pollStates}={}){const timers=new Timers(),elements=new Map(),peers=[],calls=[],requests=[],rafs=new Map();let rafId=0;for(const id of ['online-lobby','online-status','sound-setting','motion-setting','stage-choice','fight-frame','match-actions','ready-button','fighter-grid','room-panel','entry-panel','room-code','seat-label','players','selected-fighter','screen-name','create-room','join-room','join-code','room-list','join-form','entry-form','refresh-rooms','leave-room','rematch-button'])elements.set(id,new Element(id.includes('form')?'FORM':id==='screen-name'?'INPUT':'BUTTON'));elements.get('fight-frame').hidden=true;elements.get('screen-name').value='A';const doc={getElementById:id=>elements.get(id),createElement:tag=>new Element(tag.toUpperCase()),querySelectorAll:()=>[...elements.values()],hasFocus:()=>true,hidden:false,activeElement:null};class BrowserPeer extends Peer{constructor(){super();peers.push(this);}}const w=new Events();Object.assign(w,{location:{href:'https://game.test/online.html'},matchMedia:()=>({matches:false}),navigator:{},RTCPeerConnection:BrowserPeer,sessionStorage:{setItem(){},removeItem(){}},requestAnimationFrame:callback=>{rafs.set(++rafId,callback);return rafId;},cancelAnimationFrame:id=>rafs.delete(id),setTimeout:timers.setTimeout,clearTimeout:timers.clearTimeout});const fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):null;const created=body?.action==='create'?createSeats?.shift():null;requests.push({body,options});if(body?.action==='create'&&createWait){const waiting=typeof createWait==='function'?createWait():createWait;if(waiting)await waiting;}if(body?.action==='select'&&selectWait){const waiting=typeof selectWait==='function'?selectWait(body):selectWait;if(waiting)await waiting;}if(body?.action==='poll'&&pollWait)await pollWait;calls.push(String(url).includes('roster.json')?'roster':body?.action??'GET');if(!body&&!String(url).includes('roster.json')&&listWait)await listWait;const json=String(url).includes('roster.json')?{fighters:[{id:'6-bit',name:'6 Bit',portrait:'assets/menu/6-bit-portrait.webp'},{id:'9-bit',name:'9 Bit',portrait:'assets/menu/9-bit-portrait.webp'}]}:body?.action==='create'?created??{code:'ABC123',role:'host',token:'private-seat',expiresAt:Date.now()+1200000}:body?.action==='poll'?pollStates?.shift()??{host:{name:'A',fighter:'6-bit',ready:true},guest:{name:'B',fighter:'9-bit',ready:true}}:{rooms:[],ok:true};return {ok:true,json:async()=>json};};const mounted=await lobby.mountOnlineLobby({document:doc,window:w,fetch});return {mounted,timers,elements,peers,calls,requests,rafs,w};}
const flushTasks=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
test('a failed connection stays ended rather than being restarted by lobby polling',async()=>{const f=await mountedLobby();f.elements.get('create-room').click();await flushTasks();assert.equal(f.peers.length,1);f.peers[0].connectionState='failed';f.peers[0].emit('connectionstatechange');f.timers.advance(1500);await flushTasks();assert.equal(f.peers.length,1);assert.equal(f.elements.get('ready-button').disabled,true);assert.equal(f.elements.get('fight-frame').hidden,true);f.mounted.destroy();});


test('keyboard and controller navigation moves through rows without losing focus',()=>{const items=['a','b','c','d','e','f'];assert.equal(lobby.nextLobbyFocus(items,0,'ArrowRight',3),'b');assert.equal(lobby.nextLobbyFocus(items,0,'ArrowDown',3),'d');assert.equal(lobby.nextLobbyFocus(items,1,'ArrowUp',3),'e');assert.equal(lobby.nextLobbyFocus(items,-1,'ArrowDown',3),'a');assert.equal(lobby.nextLobbyFocus(items,0,'Escape',3),null);});
test('repeated manual room refreshes cannot multiply active polling loops',async()=>{let release;const wait=new Promise(resolve=>{release=resolve;});const f=await mountedLobby({listWait:wait});try{for(let i=0;i<5;i++)f.elements.get('refresh-rooms').click();assert.equal(f.calls.filter(v=>v==='GET').length,1);release();await flushTasks();}finally{f.mounted.destroy();}});

test('both-loaded kickoff focuses the game frame for keyboard and controller play',async()=>{const f=await mountedLobby();try{f.elements.get('create-room').click();await flushTasks();const pc=f.peers[0],control=pc.channels.find(c=>c.label==='clash-control');for(const c of pc.channels)c.open();control.emit('message',{data:JSON.stringify({scope:'system-clash-online-v1',version:'system-clash-20261008-1',seq:1,matchId:1,payload:{type:'hello',version:'system-clash-20261008-1',room:'ABC123',role:'guest'}})});const frame=f.elements.get('fight-frame');f.w.emit('message',{origin:'https://game.test',source:frame.contentWindow,data:{scope:'system-clash-online-v1',matchId:1,payload:{type:'loaded'}}});control.emit('message',{data:JSON.stringify({scope:'system-clash-online-v1',version:'system-clash-20261008-1',seq:2,matchId:1,payload:{type:'loaded'}})});assert.equal(frame.focused,true);assert.equal(frame.contentWindow.focused,true);}finally{f.mounted.destroy();}});

test('only the host may resume and rematch requires the host result state',()=>{const sent=[],frames=[],loads=[];const host=lobby.createOnlineSession({seat:{role:'host'},peer:{setMatchId(){},send:p=>sent.push(p)},postFrame:p=>frames.push(p),loadFrame:id=>loads.push(id)});host.connected();host.receiveFrame({type:'loaded'});host.receivePeer({type:'loaded'});host.receivePeer({type:'pause',paused:false});assert.equal(frames.some(p=>p.type==='pause'&&!p.paused),false);host.receiveFrame({type:'rematch'});host.receivePeer({type:'rematch'});assert.deepEqual(loads,[1]);host.receiveFrame({type:'snapshot',snapshot:{state:{phase:'over'}}});host.receivePeer({type:'rematch'});assert.deepEqual(loads,[1,2]);const guest=lobby.createOnlineSession({seat:{role:'guest'},peer:{setMatchId(){},send:p=>sent.push(p)},postFrame:p=>frames.push(p),loadFrame(){}});guest.connected();guest.receivePeer({type:'setup'});guest.receiveFrame({type:'loaded'});guest.receivePeer({type:'start',matchId:1,seed:1});const before=sent.length;guest.receiveFrame({type:'pause',paused:false});assert.equal(sent.length,before);});


test('a seat returned after lobby disposal is released without reopening UI or timers',async()=>{let release;const wait=new Promise(resolve=>release=resolve);const f=await mountedLobby({createWait:wait});f.elements.get('create-room').click();await flushTasks();f.mounted.destroy();release();await flushTasks();assert.equal(f.peers.length,0);assert.equal(f.elements.get('room-panel').hidden,true);assert.equal(f.timers.jobs.size,0);const leave=f.requests.find(r=>r.body?.action==='leave');assert.equal(leave?.body.code,'ABC123');assert.equal(leave?.options.headers.Authorization,'Bearer private-seat');assert.equal(leave?.options.keepalive,true);});
test('pagehide clears the old room and pageshow starts one fresh lobby loop',async()=>{const f=await mountedLobby();try{f.elements.get('create-room').click();await flushTasks();assert.equal(f.peers.length,1);f.w.emit('pagehide',{persisted:true});assert.equal(f.peers[0].connectionState,'closed');assert.equal(f.timers.jobs.size,0);assert.equal(f.rafs.size,0);assert.equal(f.elements.get('room-panel').hidden,true);assert.equal(f.elements.get('entry-panel').hidden,false);f.w.emit('pageshow',{persisted:true});f.w.emit('pageshow',{persisted:true});await flushTasks();assert.equal(f.rafs.size,1);assert.equal(f.timers.jobs.size,1);f.elements.get('create-room').click();await flushTasks();assert.equal(f.peers.length,2);}finally{f.mounted.destroy();}});
test('a late create after page restoration releases only its own old token',async()=>{let release,calls=0;const wait=new Promise(resolve=>release=resolve),expiresAt=Date.now()+1200000;const f=await mountedLobby({createWait:()=>++calls===1?wait:null,createSeats:[{code:'ABC123',role:'host',token:'OLD-SEAT',expiresAt},{code:'DEF456',role:'host',token:'NEW-SEAT',expiresAt}]});try{f.elements.get('create-room').click();await flushTasks();f.w.emit('pagehide',{persisted:true});f.w.emit('pageshow',{persisted:true});f.elements.get('create-room').click();await flushTasks();assert.equal(f.elements.get('room-code').textContent,'DEF456');release();await flushTasks();const oldLeave=f.requests.find(r=>r.body?.action==='leave'&&r.body.code==='ABC123');assert.equal(oldLeave?.options.headers.Authorization,'Bearer OLD-SEAT');assert.equal(f.elements.get('room-code').textContent,'DEF456');assert.equal(f.elements.get('room-panel').hidden,false);assert.equal(f.peers.length,1);}finally{release();f.mounted.destroy();}});
test('a pending poll cannot resurrect an old peer after pagehide',async()=>{let release;const wait=new Promise(resolve=>release=resolve);const f=await mountedLobby({pollWait:wait});try{f.elements.get('create-room').click();await flushTasks();f.w.emit('pagehide',{persisted:true});release();await flushTasks();assert.equal(f.peers.length,0);assert.equal(f.timers.jobs.size,0);assert.equal(f.elements.get('room-panel').hidden,true);}finally{release();f.mounted.destroy();}});
test('restoring while a room list is pending eventually resumes one list loop',async()=>{let release;const wait=new Promise(resolve=>release=resolve);const f=await mountedLobby({listWait:wait});try{f.w.emit('pagehide',{persisted:true});f.w.emit('pageshow',{persisted:true});release();await flushTasks();f.timers.advance(5000);await flushTasks();assert.equal(f.calls.filter(v=>v==='GET').length,2);assert.equal(f.timers.jobs.size,1);assert.equal(f.rafs.size,1);}finally{release();f.mounted.destroy();}});


test('an old fighter-choice response cannot change a newly entered room or its frame identity',async()=>{let release;const wait=new Promise(resolve=>release=resolve),expiresAt=Date.now()+1200000;const f=await mountedLobby({selectWait:wait,pollStates:[{host:{name:'A',fighter:'6-bit',ready:false},guest:null},{host:{name:'C',fighter:'6-bit',ready:true},guest:{name:'D',fighter:'9-bit',ready:true}}],createSeats:[{code:'ABC123',role:'host',token:'OLD-SEAT',expiresAt},{code:'DEF456',role:'host',token:'NEW-SEAT',expiresAt}]});try{f.elements.get('create-room').click();await flushTasks();f.elements.get('fighter-grid').children.find(b=>b.dataset.fighter==='9-bit').click();await flushTasks();f.w.emit('pagehide',{persisted:true});f.w.emit('pageshow',{persisted:true});f.elements.get('create-room').click();await flushTasks();release();await flushTasks();assert.equal(f.elements.get('room-code').textContent,'DEF456');assert.equal(f.elements.get('selected-fighter').textContent,'6 Bit');const pc=f.peers[0],control=pc.channels.find(c=>c.label==='clash-control');for(const c of pc.channels)c.open();control.emit('message',{data:JSON.stringify({scope:'system-clash-online-v1',version:'system-clash-20261008-1',seq:1,matchId:1,payload:{type:'hello',version:'system-clash-20261008-1',room:'DEF456',role:'guest'}})});assert.equal(new URL(f.elements.get('fight-frame').src).searchParams.get('p1'),'6-bit');}finally{release();f.mounted.destroy();}});
test('an old ready response cannot unlock a newer room while its fighter request is pending',async()=>{let oldRelease,newRelease;const oldWait=new Promise(resolve=>oldRelease=resolve),newWait=new Promise(resolve=>newRelease=resolve),waiting={host:{name:'A',fighter:'6-bit',ready:false},guest:null};const f=await mountedLobby({selectWait:body=>body.ready?oldWait:newWait,pollStates:[structuredClone(waiting),structuredClone(waiting),structuredClone(waiting)]});try{f.elements.get('create-room').click();await flushTasks();f.elements.get('ready-button').click();await flushTasks();f.w.emit('pagehide',{persisted:true});f.w.emit('pageshow',{persisted:true});f.elements.get('create-room').click();await flushTasks();f.elements.get('fighter-grid').children.find(b=>b.dataset.fighter==='9-bit').click();await flushTasks();f.timers.advance(1500);await flushTasks();assert.equal(f.elements.get('ready-button').disabled,true);oldRelease();await flushTasks();assert.equal(f.elements.get('ready-button').disabled,true);assert.ok(f.elements.get('fighter-grid').children.every(b=>b.disabled));}finally{oldRelease();newRelease();await flushTasks();f.mounted.destroy();}});
