import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import path from 'node:path';import sharp from 'sharp';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {poseFrameIndex,poseScale} from '../public/games/system-clash/play/fight-attachments.mjs';
const root=fileURLToPath(new URL('../public/games/system-clash/play/',import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex');

function unchangedNativeGeometry(actual,old,currentFrame,oldFrame,currentAsset,oldAsset){
 const cs=poseScale(currentAsset,currentFrame),os=poseScale(oldAsset,oldFrame);assert.equal(cs,os,'The complete original native source retains one uniform scale');
 const co=currentFrame.offset??[0,0],oo=oldFrame.offset??[0,0],dx=(co[0]-currentFrame.anchor[0]-oo[0]+oldFrame.anchor[0])*cs,dy=(co[1]-currentFrame.anchor[1]-oo[1]+oldFrame.anchor[1])*cs;
 const point=p=>({x:p.x+dx,y:p.y+dy}),close=(a,b)=>assert(Math.abs(a-b)<.0001,'Original source landmarks and actual strike reach change only by whole-pose root registration');
 for(const site of ['head','torso','legs','grip']){const want=point(old.sites[site]);close(actual.sites[site].x,want.x);close(actual.sites[site].y,want.y);}
 for(const site of ['strike','strikeStart']){if(!oldFrame.attachments?.[site]&&currentFrame.attachments?.[site]){assert.equal(currentFrame.strikeProfile?.kind,'native-active-leading-foot-alpha','A newly measured foot replaces the old generic crop-edge approximation');const p=currentFrame.attachments[site];close(actual[site].x,(p[0]+co[0]-currentFrame.anchor[0])*cs);close(actual[site].y,(p[1]+co[1]-currentFrame.anchor[1])*cs);}else{const want=point(old[site]);close(actual[site].x,want.x);close(actual[site].y,want.y);}}
 for(const edge of ['left','right','top','bottom'])close(actual.bounds[edge],old.bounds[edge]+(['left','right'].includes(edge)?dx:dy));assert.equal(actual.strikeRadius,old.strikeRadius);
 if(currentFrame.combatHurt){assert.equal(actual.measuredHurt,true);assert.equal(actual.hurt.length,currentFrame.combatHurt.length);for(const r of actual.hurt)assert(r.left>=actual.bounds.left-.001&&r.right<=actual.bounds.right+.001&&r.top>=actual.bounds.top-.001&&r.bottom<=actual.bounds.bottom+.001,'Fine native alpha bands remain inside the original intact body');}else assert.deepEqual(actual.hurt,old.hurt);
}
const targets=[['mr-nice-guy','arcade','crouch-kick'],['mac-modem','arcade','crouch-kick'],['stolz','arcade','crouch-kick'],['dj-floppydisc','deletions','brace'],['dj-floppydisc','deletions','pull'],['cache-back','deletions','brace'],['cache-back','deletions','shove']];
for(const[id,bank,name]of targets)test(id+' '+name+': whole-body motion keys keep actual native contacts and timing',async()=>{
 const dir=path.join(root,'assets',bank,id),m=JSON.parse(await readFile(path.join(dir,'manifest.json'),'utf8')),base=JSON.parse(await readFile(path.join(root,'assets/fighters',id,'manifest.json'),'utf8')),clip=m.clips[name],p=clip.animationPolish;
 assert.equal(p?.kind,'native-full-body-action-inbetweens');assert.equal(p.generatedKeysPerFacing,2);
 const file=path.join(dir,clip.file),bytes=await readFile(file),meta=await sharp(bytes).metadata(),runtimeName=bank==='deletions'?'delete-'+name:name,asset=compileFightClip(clip,meta,m,runtimeName),md=combatMetadata([{manifest:base,clips:{[runtimeName]:asset}}])[0][runtimeName];
 assert.deepEqual(clip.sourceSize,[meta.width,meta.height]);assert.equal(clip.sourceSha256,sha(bytes));assert.equal(asset.timeline.duration,p.approvedTiming.duration);
 assert.equal(clip.contactMs,p.approvedTiming.contactMs);assert.equal(md.activeEndMs,p.approvedTiming.activeEndMs);
 const oldImage=await sharp(path.join(dir,p.approvedFile)).metadata(),oldAsset=compileFightClip(p.approvedClip,oldImage,m,runtimeName),oldMd=combatMetadata([{manifest:base,clips:{[runtimeName]:oldAsset}}])[0][runtimeName];
 for(const facing of ['right','left']){
  assert.equal(clip.frames[facing].length,4);assert.equal(clip.frames[facing].filter(f=>f.motionKeyOrigin==='generated').length,2);assert.deepEqual(clip.frames[facing].filter(f=>f.motionKeyOrigin==='approved').map(f=>f.poseSource.originalIndex),[0,1]);const hashes=[];
  for(const[index,frame]of clip.frames[facing].entries()){const[left,top,width,height]=frame.rect,raw=await sharp(bytes).extract({left,top,width,height}).ensureAlpha().raw().toBuffer();hashes.push(sha(raw));assert.equal(sha(raw),frame.canonicalPixelSha256);if(frame.strikeProfile){const [x,y]=frame.attachments.strike,range=Math.ceil(5/poseScale(asset,frame));let nearest=Infinity;for(let yy=Math.max(0,Math.floor(y)-range);yy<Math.min(height,Math.ceil(y)+range);yy++)for(let xx=Math.max(0,Math.floor(x)-range);xx<Math.min(width,Math.ceil(x)+range);xx++)if(raw[(yy*width+xx)*4+3]>48)nearest=Math.min(nearest,Math.hypot(xx-x,yy-y));assert(nearest*poseScale(asset,frame)<=5,'Authored new foot contact actually lies on decoded native opaque pixels within documented five-pixel alpha quantization');}
   if(frame.motionKeyOrigin==='approved'){const source=frame.poseSource,old=await sharp(path.join(dir,p.approvedFile)).extract({left:source.originalRect[0],top:source.originalRect[1],width,height}).ensureAlpha().raw().toBuffer();for(let i=0;i<raw.length;i+=4){assert.equal(raw[i+3],old[i+3]);if(old[i+3]>0)for(let c=0;c<3;c++)assert.equal(raw[i+c],old[i+c]);}unchangedNativeGeometry(md.combatPoses.frames[facing][index],oldMd.combatPoses.frames[facing][source.originalIndex],frame,p.approvedClip.frames[facing][source.originalIndex],asset,oldAsset);}
   else {assert.equal(frame.poseSource.kind,'generated');assert.equal(frame.poseSource.sourceFile,name+'-between-source.png');assert.match(frame.poseSource.sourceSha256,/^[a-f0-9]{64}$/);}
  }
  assert.equal(new Set(hashes).size,4,'Four real whole-character source images, without duplicated padding');
  if(Number.isFinite(clip.contactMs)){for(const t of [clip.contactMs,md.activeEndMs-.001]){const index=poseFrameIndex(asset,{facing,elapsed:t}),oldIndex=poseFrameIndex(oldAsset,{facing,elapsed:t});unchangedNativeGeometry(md.combatPoses.frames[facing][index],oldMd.combatPoses.frames[facing][oldIndex],clip.frames[facing][index],p.approvedClip.frames[facing][oldIndex],asset,oldAsset);}}
  const end=poseFrameIndex(asset,{facing,elapsed:asset.timeline.duration-.001}),oldEnd=poseFrameIndex(oldAsset,{facing,elapsed:oldAsset.timeline.duration-.001});unchangedNativeGeometry(md.combatPoses.frames[facing][end],oldMd.combatPoses.frames[facing][oldEnd],clip.frames[facing][end],p.approvedClip.frames[facing][oldEnd],asset,oldAsset);
 }
});
