import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import path from 'node:path';import sharp from 'sharp';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {poseFrameIndex,poseScale,poseTransform} from '../public/games/system-clash/play/fight-attachments.mjs';
const root=fileURLToPath(new URL('../public/games/system-clash/play/',import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex');

function unchangedNativeGeometry(actual,old,currentFrame,oldFrame,currentAsset,oldAsset){
 const cs=poseScale(currentAsset,currentFrame),os=poseScale(oldAsset,oldFrame);assert.equal(cs,os,'The original native source retains its existing vertical scale');
 const current=poseTransform(currentAsset,currentFrame),previous=poseTransform(oldAsset,oldFrame);
 // Compare the retained native landmark through both crop transforms: current source width calibration and root registration apply once.
 const point=p=>current.point(previous.inverse(p)),close=(a,b)=>assert(Math.abs(a-b)<.0001,'Original source landmarks and strike reach use the shared calibrated crop transform');
 for(const site of ['head','torso','legs','grip']){const want=point(old.sites[site]);close(actual.sites[site].x,want.x);close(actual.sites[site].y,want.y);}
 for(const site of ['strike','strikeStart']){if(!oldFrame.attachments?.[site]&&currentFrame.attachments?.[site]){assert.equal(currentFrame.strikeProfile?.kind,'native-active-leading-foot-alpha','A newly measured foot replaces the old generic crop-edge approximation');const p=currentFrame.attachments[site];const want=current.point(p);close(actual[site].x,want.x);close(actual[site].y,want.y);}else{const want=point(old[site]);close(actual[site].x,want.x);close(actual[site].y,want.y);}}
 const topLeft=point({x:old.bounds.left,y:old.bounds.top}),bottomRight=point({x:old.bounds.right,y:old.bounds.bottom});for(const [edge,want]of Object.entries({left:topLeft.x,top:topLeft.y,right:bottomRight.x,bottom:bottomRight.y}))close(actual.bounds[edge],want);assert.equal(actual.strikeRadius,old.strikeRadius);
 if(currentFrame.combatHurt){assert.equal(actual.measuredHurt,true);assert.equal(actual.hurt.length,currentFrame.combatHurt.length);for(const r of actual.hurt)assert(r.left>=actual.bounds.left-.001&&r.right<=actual.bounds.right+.001&&r.top>=actual.bounds.top-.001&&r.bottom<=actual.bounds.bottom+.001,'Fine native alpha bands remain inside the original intact body');}else assert.deepEqual(actual.hurt,old.hurt);
}
const targets=[['mr-nice-guy','arcade','crouch-kick'],['mac-modem','arcade','crouch-kick'],['stolz','arcade','crouch-kick'],['dj-floppydisc','deletions','brace'],['dj-floppydisc','deletions','pull'],['cache-back','deletions','brace'],['cache-back','deletions','shove']];
for(const[id,bank,name]of targets)test(id+' '+name+': whole-body motion keys keep actual native contacts and timing',async()=>{
 const dir=path.join(root,'assets',bank,id),m=JSON.parse(await readFile(path.join(dir,'manifest.json'),'utf8')),base=JSON.parse(await readFile(path.join(root,'assets/fighters',id,'manifest.json'),'utf8')),clip=m.clips[name],p=clip.animationPolish;
 assert.equal(p?.kind,'native-full-body-action-inbetweens');assert.equal(p.generatedKeysPerFacing,2);
 const file=path.join(dir,clip.file),bytes=await readFile(file),meta=await sharp(bytes).metadata(),runtimeName=bank==='deletions'?'delete-'+name:name,asset=compileFightClip(clip,meta,m,runtimeName),md=combatMetadata([{manifest:base,clips:{[runtimeName]:asset}}])[0][runtimeName];
 assert.deepEqual(clip.sourceSize,[meta.width,meta.height]);assert.equal(clip.sourceSha256,sha(bytes));assert.equal(asset.timeline.duration,p.approvedTiming.duration);
 assert.equal(clip.contactMs,p.approvedTiming.contactMs);assert.equal(md.activeEndMs,p.approvedTiming.activeEndMs);
 const oldImage=await sharp(path.join(dir,p.approvedFile)).metadata(),oldAsset=compileFightClip(p.approvedClip,oldImage,m,runtimeName),oldMd=combatMetadata([{manifest:base,clips:{[runtimeName]:oldAsset}}])[0][runtimeName];
 if(id==='mac-modem'){
  assert.equal(clip.nativeIdentityTransfer.kind,'partial-approved-whole-body');
  assert.deepEqual(clip.order,[0, 1, 2, 2, 3, 0]);assert.deepEqual(clip.frameMs,[80, 80, 80, 40, 40, 160]);
  for(const facing of ['right','left']){const hashes=[];assert.equal(Object.keys(clip.nativeIdentityTransfer.phaseLineage).length,8);
   assert.deepEqual(clip.frames[facing].map((_,index)=>clip.nativeIdentityTransfer.phaseLineage[`${facing}/${index}`].originalPhaseOrigin),['approved','generated','approved','generated']);
   for(const[index,frame]of clip.frames[facing].entries()){const[left,top,width,height]=frame.rect,raw=await sharp(bytes).extract({left,top,width,height}).ensureAlpha().raw().toBuffer();hashes.push(sha(raw));verifyMacTransfer(frame,raw,clip,index,facing,sha);}
   assert.equal(new Set(hashes).size,4);for(const t of [clip.contactMs,md.activeEndMs-.001]){const index=poseFrameIndex(asset,{facing,elapsed:t});assert.ok(clip.frames[facing][index].attachments.strike);assert.ok(clip.frames[facing][index].attachments.strikeStart);assert.equal(md.combatPoses.frames[facing][index].measuredHurt,true);}
  }return;
 }
 for(const facing of ['right','left']){
  assert.equal(clip.frames[facing].length,4);assert.equal(clip.frames[facing].filter(f=>f.motionKeyOrigin==='generated').length,2);assert.deepEqual(clip.frames[facing].filter(f=>f.motionKeyOrigin==='approved').map(f=>f.poseSource.originalIndex),[0,1]);const hashes=[];
  for(const[index,frame]of clip.frames[facing].entries()){const[left,top,width,height]=frame.rect,raw=await sharp(bytes).extract({left,top,width,height}).ensureAlpha().raw().toBuffer();hashes.push(sha(raw));assert.equal(sha(raw),frame.canonicalPixelSha256);if(frame.strikeProfile){const [x,y]=frame.attachments.strike,range=Math.ceil(5/poseScale(asset,frame));let nearest=Infinity;for(let yy=Math.max(0,Math.floor(y)-range);yy<Math.min(height,Math.ceil(y)+range);yy++)for(let xx=Math.max(0,Math.floor(x)-range);xx<Math.min(width,Math.ceil(x)+range);xx++)if(raw[(yy*width+xx)*4+3]>48)nearest=Math.min(nearest,Math.hypot(xx-x,yy-y));assert(nearest*poseScale(asset,frame)<=5,'Authored new foot contact actually lies on decoded native opaque pixels within documented five-pixel alpha quantization');}
   if(frame.motionKeyOrigin==='approved'){const source=frame.poseSource,old=await sharp(path.join(dir,p.approvedFile)).extract({left:source.originalRect[0],top:source.originalRect[1],width,height}).ensureAlpha().raw().toBuffer();for(let i=0;i<raw.length;i+=4){assert.equal(raw[i+3],old[i+3]);if(old[i+3]>0)for(let c=0;c<3;c++)assert.equal(raw[i+c],old[i+c]);}unchangedNativeGeometry(md.combatPoses.frames[facing][index],oldMd.combatPoses.frames[facing][source.originalIndex],frame,p.approvedClip.frames[facing][source.originalIndex],asset,oldAsset);}
   else {assert.equal(frame.poseSource.kind,'generated');assert.equal(frame.poseSource.sourceFile,name+'-between-source.png');assert.match(frame.poseSource.sourceSha256,/^[a-f0-9]{64}$/);}
  }
  assert.equal(new Set(hashes).size,4,'Four real whole-character source images, without duplicated padding');
  if(Number.isFinite(clip.contactMs)){for(const t of [clip.contactMs,md.activeEndMs-.001]){const index=poseFrameIndex(asset,{facing,elapsed:t}),oldIndex=poseFrameIndex(oldAsset,{facing,elapsed:t});unchangedNativeGeometry(md.combatPoses.frames[facing][index],oldMd.combatPoses.frames[facing][oldIndex],clip.frames[facing][index],p.approvedClip.frames[facing][oldIndex],asset,oldAsset);}}
  const end=poseFrameIndex(asset,{facing,elapsed:asset.timeline.duration-.001}),oldEnd=poseFrameIndex(oldAsset,{facing,elapsed:oldAsset.timeline.duration-.001});unchangedNativeGeometry(md.combatPoses.frames[facing][end],oldMd.combatPoses.frames[facing][oldEnd],clip.frames[facing][end],p.approvedClip.frames[facing][oldEnd],asset,oldAsset);
 }
});

// Mac's accepted identity correction retains phase provenance, not the old wrong pixels.
const macAcceptedSources={"right":[["native-batch-34-v3.png",2,"c64e46e3662fa891f0917b50b7a9f9dde439de729be1a0b3748de82e76359e24","16ad3f94cd5b70cec9a2b1eb53da6da6e19857d3ca162f8aa2e58714453e671c"],["native-batch-34-v3.png",3,"c64e46e3662fa891f0917b50b7a9f9dde439de729be1a0b3748de82e76359e24","032e4fec40287232ad140f794945169ed5bacf3638d031abbf11adc7ac79495c"],["native-batch-35-v3.png",0,"68c8ac7ffeb63c6b1c7d94b1dffd2b180103fa7acec129d5dac61a325a913c7c","2157fbdf410011a549ca9e0925fbd977687c1b19955435c293f76e75b61e0567"],["native-batch-35-v3.png",1,"68c8ac7ffeb63c6b1c7d94b1dffd2b180103fa7acec129d5dac61a325a913c7c","c6bbf6f6a409afc8f0d0ed9b15112a56434950bed058b812beb12afe5119ca84"]],"left":[["native-batch-35-v3.png",2,"68c8ac7ffeb63c6b1c7d94b1dffd2b180103fa7acec129d5dac61a325a913c7c","4ed5592ed9a0f9cff60ec86defdb69e9e3f4330ff87e86ebcd82d3e4fbe0e9f7"],["native-batch-35-v3.png",3,"68c8ac7ffeb63c6b1c7d94b1dffd2b180103fa7acec129d5dac61a325a913c7c","d43d02f918296922f4fb633d1ecfad62d1c0503c499c9b26e24185cc229d85ca"],["native-batch-36-v3.png",0,"2ad9d437e546d5531be640071108207be91fca4254e2e792716bfafd56bcacd4","cb87be7246693c09565a0985f697d02f47493a3d2b6d91ad844c83065cf0fec4"],["native-batch-36-v3.png",1,"2ad9d437e546d5531be640071108207be91fca4254e2e792716bfafd56bcacd4","820a1695a02a0f6b7dd6581f24b5ce893c23d59f0cf4dbd122bd65e576dde59d"]]};
function verifyMacTransfer(frame,raw,clip,index,facing,hash){
 const source=frame.poseSource,lineage=clip.nativeIdentityTransfer.phaseLineage[`${facing}/${index}`];
 assert.equal(source.kind,'native-identity-transfer');assert.deepEqual([source.sourceFile,source.cell,source.sourceSha256,frame.canonicalPixelSha256],macAcceptedSources[facing][index]);
 assert.equal(hash(raw),frame.canonicalPixelSha256);assert.equal(frame.pixelSha256,frame.canonicalPixelSha256);assert.notEqual(frame.pixelSha256,source.retainedOriginalRgbaSha256,'The approved correction is new art, never mislabeled unchanged original pixels');
 assert.equal(lineage.originalPhaseIndex,index);assert.equal(lineage.originalFile,source.retainedOriginalFile);assert.deepEqual(lineage.originalRect,source.retainedOriginalRect);assert.equal(lineage.originalRgbaSha256,source.retainedOriginalRgbaSha256);
 assert.ok(Number.isFinite(source.uniformResample)&&source.uniformResample>0);assert.equal(frame.bodyCalibration,1);assert.equal(frame.combatProfile.kind,'native-alpha-bands');assert.equal(frame.combatProfile.sourceSha256,clip.sourceSha256);assert.equal(frame.combatProfile.sourceRgbaSha256,frame.canonicalPixelSha256);
 const width=frame.rect[2],height=frame.rect[3];for(const site of ['grip','strike','strikeStart'])if(frame.attachments[site]){const[x,y]=frame.attachments[site];let alpha=0;for(let yy=Math.max(0,Math.floor(y)-1);yy<=Math.min(height-1,Math.ceil(y)+1);yy++)for(let xx=Math.max(0,Math.floor(x)-1);xx<=Math.min(width-1,Math.ceil(x)+1);xx++)alpha=Math.max(alpha,raw[(yy*width+xx)*4+3]);assert(alpha>=128,site+' must lie on decoded own native opaque hand/shoe within integer resample rounding');}
}
