import test from 'node:test';
import assert from 'node:assert/strict';
const walkModule=await import('../public/games/system-clash/play/fight-walk-rig.mjs').catch(error=>{if(error.code==='ERR_MODULE_NOT_FOUND')return {};throw error;});
const frame={rect:[0,0,100,100],anchor:[50,100],opaqueBounds:[0,0,100,100],attachments:{head:[50,15],torso:[50,40],legs:[50,80],grip:[80,35]},combatHurt:[['legs',15,90,35,100],['legs',65,90,85,100]]};
const asset={fighterId:'test',name:'walk',scale:1,character:'fixture',data:{loop:true,frames:{right:[frame],left:[frame]}},timeline:{duration:600,entries:[{index:0,start:0,end:600}]}};
const get=(elapsed,facing='right',clip='walk')=>walkModule.walkRig?.(asset,{elapsed,facing,clip},frame);
test('walking creates a real alternating planted and lifted foot while head and torso remain rigid',()=>{assert.equal(typeof walkModule.walkRig,'function','Walking still displays the unchanged native stance');const rig=get(150);assert.ok(rig);assert.deepEqual(rig.map({x:50,y:15}),{x:0,y:-85});assert.deepEqual(rig.map({x:50,y:40}),{x:0,y:-60});assert.ok(Math.abs(rig.map({x:25,y:100}).y+6)<.001,'The swing foot must visibly clear the floor');assert.ok(Math.abs(rig.map({x:75,y:100}).y)<.001,'The support foot must stay on the floor');const other=get(450);assert.ok(Math.abs(other.map({x:25,y:100}).y)<.001);assert.ok(Math.abs(other.map({x:75,y:100}).y+6)<.001);});
test('walk motion loops smoothly and uses its actual facing rather than flipping source art',()=>{assert.equal(typeof walkModule.walkRig,'function');const first=get(600),next=get(1200);assert.deepEqual(first.map({x:25,y:100}),next.map({x:25,y:100}));assert.equal(first.cacheKey,next.cacheKey);const right=get(300),left=get(300,'left');assert.ok(right.map({x:25,y:100}).x>-25);assert.ok(left.map({x:25,y:100}).x<-25);});
test('idle, held choreography and the bodiless digital construct never acquire synthetic legs',()=>{assert.equal(typeof walkModule.walkRig,'function');assert.equal(get(150,'right','idle'),null);assert.equal(walkModule.walkRig(asset,{clip:'walk',elapsed:150,facing:'right',frameIndex:0},frame),null);assert.equal(walkModule.walkRig({...asset,fighterId:'bnl'},{clip:'walk',elapsed:150,facing:'right'},frame),null);});
test('walking hurt bands move with the visible lifted foot while torso remains exact',()=>{assert.equal(typeof walkModule.compileWalkGeometry,'function');assert.equal(typeof walkModule.warpWalkCombatPose,'function');const walkGeometry=walkModule.compileWalkGeometry(asset,frame,'right'),torso={site:'torso',left:-10,right:10,top:-80,bottom:-50},pose={hurt:[torso,{site:'legs',left:-30,right:-20,top:-10,bottom:0}],bounds:{left:-50,right:50,top:-100,bottom:0},walkGeometry};const current=walkModule.warpWalkCombatPose(pose,150,600,'right');assert.deepEqual(current.hurt[0],torso);assert.ok(Math.abs(current.hurt[1].bottom+6)<.001,'A raised foot cannot retain an invisible hurtbox on the floor');assert.ok(current.hurt[1].top<-10);assert.deepEqual(pose.hurt[1],{site:'legs',left:-30,right:-20,top:-10,bottom:0},'Compiled native pose is immutable');});
test('the canonical BNL ID keeps its digital wisp rather than receiving a foot rig',()=>{assert.equal(walkModule.walkRig({...asset,fighterId:'bnl-01'},{clip:'walk',elapsed:150,facing:'right'},frame),null);});
test('the actual combat engine misses an ankle lifted above the attacking fist',async()=>{
 const {createMatch,performAction,advanceMatch,consumeEvents}=await import('../public/games/system-clash/play/fight-engine.mjs');
 const large={...asset,scale:4},walkGeometry=walkModule.compileWalkGeometry(large,frame,'left');
 const body={bounds:{left:-200,right:200,top:-400,bottom:0},sites:{head:{x:0,y:-340},torso:{x:0,y:-200},legs:{x:0,y:-80},grip:{x:10,y:-200}},hurt:[{site:'torso',left:-20,right:20,top:-300,bottom:-150},{site:'legs',left:-140,right:-60,top:-40,bottom:0},{site:'legs',left:60,right:140,top:-40,bottom:0}],measuredHurt:true,pushCore:{left:-20,right:20,top:-300,bottom:-150},pushLegs:[]};
 const bank=(p,loop=true,duration=600)=>({duration,loop,combatPoses:{frames:{left:[p],right:[p]},entries:[{index:0,start:0,end:duration}],duration,loop}});
 const strike={...body,strike:{x:300,y:-5},strikeStart:{x:280,y:-5},strikeRadius:9};
 const clips={idle:bank(body),walk:bank({...body,walkGeometry}),punch:{...bank(strike,false,300),contactMs:100,activeEndMs:150}};
 const match=createMatch({start:false,mode:'local',fighters:[{id:'6-bit',height:400},{id:'9-bit',height:400}],clips:[clips,clips]});match.phase='fight';const [attacker,victim]=match.fighters;attacker.x=1000;victim.x=1400;attacker.facing='right';victim.facing='left';assert.ok(performAction(match,0,'punch'));attacker._travel=null;attacker.actionTime=attacker._clips.punch.contactMs-1;victim.action='walk';victim.actionTime=149;consumeEvents(match);const health=victim.hp;advanceMatch(match,1,[{},{move:-1}]);assert.equal(victim.action,'walk');assert.equal(victim.hp,health,'An invisible old ankle box must not register a hit after the visible ankle rises');assert.equal(consumeEvents(match).filter(e=>e.type==='hit'&&e.attacker===0).length,0);
});
test('all native leg-band interiors remain inside the mapped contact bounds throughout both facing walks',async()=>{
 const {readFileSync}=await import('node:fs'),{poseTransform}=await import('../public/games/system-clash/play/fight-attachments.mjs'),{compileFightClip,combatMetadata}=await import('../public/games/system-clash/play/fight-assets.mjs'),root=new URL('../public/games/system-clash/play/',import.meta.url),ids=JSON.parse(readFileSync(new URL('assets/fight-roster.json',root),'utf8')).fighters.filter(f=>f.enabled&&f.id!=='bnl-01').map(f=>f.id);let checked=0,worst=0,failure='';
 for(const id of ids){const m=JSON.parse(readFileSync(new URL(`assets/fighters/${id}/manifest.json`,root),'utf8')),c=m.clips.walk,frames=Object.values(c.frames).flat(),image={width:Math.max(...frames.map(f=>f.rect[0]+f.rect[2])),height:Math.max(...frames.map(f=>f.rect[1]+f.rect[3]))},a=compileFightClip(c,image,m,'walk'),poses=combatMetadata([{manifest:m,clips:{walk:a}}])[0].walk.combatPoses;
  for(const facing of ['right','left'])for(let phase=0;phase<24;phase++){const elapsed=a.timeline.duration*(1+phase/24),time=elapsed%a.timeline.duration,entry=a.timeline.entries.find(e=>time>=e.start&&time<e.end)??a.timeline.entries[0],frame=c.frames[facing][entry.index],pose=poses.frames[facing][entry.index],warped=walkModule.warpWalkCombatPose(pose,elapsed,a.timeline.duration,facing),rig=walkModule.walkRig(a,{clip:'walk',facing,elapsed},frame),tr=pose.walkGeometry?.transform??poseTransform(a,frame);
   for(let index=0;index<pose.hurt.length;index++){const region=pose.hurt[index],box=warped.hurt[index];if(region.site!=='legs'){assert.equal(box,region,'Rigid torso/head contact objects remain exact');continue;}checked++;
    // Independent uneven interior probes exercise a curve missed by four corners.
    for(const fx of [0,.13,.37,.61,.89,1])for(const fy of [0,.19,.43,.71,1]){const x=region.left+(region.right-region.left)*fx,y=region.top+(region.bottom-region.top)*fy,p=(rig?.map??tr.point)({x:(x-tr.tx)/tr.sx,y:(y-tr.ty)/tr.sy}),escape=Math.max(box.left-p.x,p.x-box.right,box.top-p.y,p.y-box.bottom,0);if(escape>worst){worst=escape;failure=`${id}/${facing}/phase${phase}/key${entry.index}/band${index}`;}}
   }
  }
 }
 assert.equal(checked,41484);assert(worst<=.5,`${failure}: visible/contact leg interior escapes bounds by ${worst.toFixed(3)}px`);
});
test('reviewed articulated walk banks keep their native legs instead of acquiring a second counterphase gait',async()=>{
 const {readFileSync}=await import('node:fs'),{compileFightClip}=await import('../public/games/system-clash/play/fight-assets.mjs'),root=new URL('../public/games/system-clash/play/',import.meta.url),ids=JSON.parse(readFileSync(new URL('assets/fight-roster.json',root),'utf8')).fighters.filter(f=>f.enabled).map(f=>f.id);
 for(const id of ids){const m=JSON.parse(readFileSync(new URL(`assets/fighters/${id}/manifest.json`,root),'utf8')),c=m.clips.walk,ff=Object.values(c.frames).flat(),asset=compileFightClip(c,{width:Math.max(...ff.map(f=>f.rect[0]+f.rect[2])),height:Math.max(...ff.map(f=>f.rect[1]+f.rect[3]))},m,'walk');for(const facing of ['left','right'])for(const e of asset.timeline.entries){const frame=c.frames[facing][e.index],rig=walkModule.walkRig(asset,{clip:'walk',facing,elapsed:asset.timeline.duration+e.start+1},frame);if(['9-bit','ash-flowers'].includes(id))assert(rig,`${id} retains a restrained actual step`);else assert.equal(rig,null,`${id} already has native articulation or no physical legs`);}}
});
test('remaining stance gait neither folds measured leg texture nor jumps feet at native pose boundaries',async()=>{
 const {readFileSync}=await import('node:fs'),{compileFightClip}=await import('../public/games/system-clash/play/fight-assets.mjs'),root=new URL('../public/games/system-clash/play/',import.meta.url);let count=0;
 for(const id of ['9-bit','ash-flowers']){const m=JSON.parse(readFileSync(new URL(`assets/fighters/${id}/manifest.json`,root),'utf8')),c=m.clips.walk,ff=Object.values(c.frames).flat(),asset=compileFightClip(c,{width:Math.max(...ff.map(f=>f.rect[0]+f.rect[2])),height:Math.max(...ff.map(f=>f.rect[1]+f.rect[3]))},m,'walk');for(const facing of ['left','right']){const feetAt=t=>{const time=t%asset.timeline.duration,e=asset.timeline.entries.find(e=>time>=e.start&&time<e.end)??asset.timeline.entries[0],frame=c.frames[facing][e.index],rig=walkModule.walkRig(asset,{clip:'walk',facing,elapsed:t},frame);return rig.feet.map(foot=>rig.map(foot));};for(const e of asset.timeline.entries){const time=asset.timeline.duration+e.end,before=feetAt(time-.001),after=feetAt(time+.001);assert(Math.max(...before.map((p,i)=>Math.hypot(p.x-after[i].x,p.y-after[i].y)))<3.5,`${id}/${facing}: native key boundary must not teleport a foot`);}
  for(const e of asset.timeline.entries)for(let phase=0;phase<60;phase++){const f=c.frames[facing][e.index],rig=walkModule.walkRig(asset,{clip:'walk',facing,elapsed:asset.timeline.duration+phase*asset.timeline.duration/60},f);for(let y=6;y<12;y++)for(let x=0;x<10;x++)for(const triangle of [[[x,y],[x+1,y],[x,y+1]],[[x+1,y],[x+1,y+1],[x,y+1]]]){const p=triangle.map(([xx,yy])=>({x:f.rect[2]*xx/10,y:f.rect[3]*yy/12})),cx=p.reduce((s,p)=>s+p.x,0)/3,cy=p.reduce((s,p)=>s+p.y,0)/3;if(!(f.combatHurt??[]).some(r=>r[0]==='legs'&&cx>=r[1]&&cx<=r[3]&&cy>=r[2]&&cy<=r[4]))continue;const q=p.map(rig.map),area=(q[1].x-q[0].x)*(q[2].y-q[0].y)-(q[2].x-q[0].x)*(q[1].y-q[0].y);assert(area>0,`${id}/${facing}/key${e.index}/phase${phase}: leg texture triangle inverted`);count++;}}
 }}assert(count>1000);
});