import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {poseFrameIndex,poseScale,resolvePoseAttachments} from '../public/games/system-clash/play/fight-attachments.mjs';
import {createMatch,performAction,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import {registerNewDeletionViews,litterBoxGeometry} from '../public/games/system-clash/play/new-deletion-renderer.mjs';
import {deletionDefinition} from '../public/games/system-clash/play/deletion-library.mjs';
import {makeFightSnapshot,applyFightSnapshot} from '../public/games/system-clash/play/fight-network-state.mjs';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url));
function size(file){const bytes=Buffer.alloc(64),fd=fs.openSync(file,'r');try{fs.readSync(fd,bytes,0,64,0);}finally{fs.closeSync(fd);}if(bytes[0]===137)return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};const k=bytes.toString('ascii',12,16);assert.equal(k,'VP8X');return {width:1+bytes.readUIntLE(24,3),height:1+bytes.readUIntLE(27,3)};}
function native(id){const clips={};let manifest;for(const bank of ['fighters','arcade','deletions']){const folder=path.join(root,bank,id),data=JSON.parse(fs.readFileSync(path.join(folder,'manifest.json'),'utf8'));if(bank==='fighters')manifest=data;for(const [name,clip] of Object.entries(data.clips)){const key=bank==='deletions'?'delete-'+name:name;clips[key]=compileFightClip(clip,size(path.join(folder,clip.file)),data,key);}}return {manifest,clips};}
const nativeIds=['6-bit','9-bit','ash-flowers','cache-back','cliff','dj-floppydisc','doofnoobler','dr3wbaby','kaveman-brown','lyra','mac-modem','mr-nice-guy','ms-mayhem','papa-oak','stolz','wittyf0x'];
const art=Object.fromEntries(nativeIds.map(id=>[id,native(id)]));
function point(v,a,site){const c=a.clips[v.clip],i=poseFrameIndex(c,v),f=c.data.frames[v.facing][i],o=f.offset??[0,0],raw=f.attachments?.[site],p=raw?{x:raw[0],y:raw[1]}:resolvePoseAttachments(f,v.clip,i,v.facing,a.manifest.id)[site],s=poseScale(c,f);return {x:v.x+(p.x+o[0]-f.anchor[0])*s,y:620+(v.y??0)+(p.y+o[1]-f.anchor[1])*s};}
function scene(hero,victim,facing='right'){const source=[art[hero],art[victim]],match=createMatch({mode:'practice',fighters:source.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(source)});match.fighters[0].x=facing==='right'?210:2350;match.fighters[1].x=match.fighters[0].x+(facing==='right'?1:-1)*75;assert(performAction(match,0,'deletion'));return {match,source};}
function views(match,source,t){match.deletionElapsed=t;return registerNewDeletionViews(match,match.fighters.map((_,i)=>getFighterView(match,i)),source,point);}


const trayManifest=JSON.parse(fs.readFileSync(path.join(root,'deletions/litter-protocol/atlas.json'),'utf8')),tray={additional:{'litter-protocol':{manifest:trayManifest}}};
function fitted(match,source,t){match.deletionElapsed=t;return registerNewDeletionViews(match,match.fighters.map((_,i)=>getFighterView(match,i)),source,point,tray);}
function wholeBounds(v,a){const c=a.clips[v.clip],f=c.data.frames[v.facing][poseFrameIndex(c,v)],o=f.offset??[0,0],s=poseScale(c,f),b=f.opaqueBounds;return {left:v.x+(b[0]+o[0]-f.anchor[0])*s,right:v.x+(b[2]+o[0]-f.anchor[0])*s,bottom:620+v.y+(b[3]+o[1]-f.anchor[1])*s};}
for(const facing of ['right','left'])for(const id of nativeIds)test('Native basin fit, constant compact pose and clear hero spacing: '+id+' '+facing,()=>{
 const {match,source}=scene('lyra',id,facing),b=deletionDefinition('lyra').beats,settled=fitted(match,source,b.basinSettled),g=litterBoxGeometry(match,tray,source),body=wholeBounds(settled[1],source[1]),reference=trayManifest.frames.open;
 assert(Math.abs(g.left-(g.centre+(reference.aperture[0]-reference.anchor[0])*g.scale))<.001,'Mask follows the actual authored opening');assert(Math.abs(g.right-g.left-reference.aperture[2]*g.scale)<.001,'No separate wider mask');assert(body.left>=g.left+7.5&&body.right<=g.right-7.5,'Complete asymmetric native pose fits with clearance');assert(Math.abs(body.bottom-g.basinFloor)<.001,'Native bottom rests on the actual litter plane');
 const expected=['lyra','papa-oak','doofnoobler'].includes(id)?2:source[1].clips['delete-crumpled'].timeline.entries.at(-1).index;assert.equal(poseFrameIndex(source[1].clips['delete-crumpled'],settled[1]),expected,'Existing compact full-body key is selected without timeline mutation');
 const identity=v=>[v.clip,v.elapsed,v.facing,v.frameIndex];for(const t of [b.basinContact,b.basinSettled,b.kick,b.litterImpact,b.buried]){const v=fitted(match,source,t)[1];assert.deepEqual(identity(v),identity(settled[1]));assert.equal(v.rotation??0,0);assert(!v.halfMask&&!v.splitBody);}
 const base=g.scale;for(const t of [b.boxReach,b.boxSet,b.fallStart,b.basinContact,b.kick,b.buried,b.complete]){fitted(match,source,t);assert.equal(litterBoxGeometry(match,tray,source).scale,base,'Scale is fixed before entry through victory');}
 for(const t of [b.kick,b.complete]){const v=fitted(match,source,t)[0],box=litterBoxGeometry(match,tray,source),f=box.frame,outerLeft=box.x+f.opaqueBounds[0]*box.scale,outerRight=box.x+f.opaqueBounds[2]*box.scale,h=wholeBounds(v,source[0]);assert(facing==='right'?h.right<=outerLeft-11.5:h.left>=outerRight+11.5,'Full native hero clears the tray at kick/victory');}
 const before=fitted(match,source,b.fallStart-.001)[1],start=fitted(match,source,b.fallStart)[1];assert(Math.hypot(point(before,source[1],'torso').x-point(start,source[1],'torso').x,point(before,source[1],'torso').y-point(start,source[1],'torso').y)<2);assert(point(settled[1],source[1],'torso').y>point(start,source[1],'torso').y+31.5,'Every native size has a visible downward fall before settling');let previous=point(start,source[1],'torso');for(let t=b.fallStart;t<=b.basinContact;t+=10){const v=fitted(match,source,t)[1],p=point(v,source[1],'torso');assert(Math.hypot(p.x-previous.x,p.y-previous.y)<15,'One smooth native airborne path reaches the compact basin pose');previous=p;}
});
test('Explicit native frame selection validates indices and preserves legacy timelines',()=>{const a=art.lyra.clips['delete-crumpled'],v={clip:'delete-crumpled',facing:'right',elapsed:10000};const legacy=poseFrameIndex(a,v);assert.equal(legacy,1);assert.equal(poseFrameIndex(a,{...v,frameIndex:2}),2);for(const invalid of [-1,.5,99,'2',NaN,Infinity])assert.equal(poseFrameIndex(a,{...v,frameIndex:invalid}),legacy);assert.equal(poseFrameIndex(a,{...v,facing:'front',frameIndex:2}),legacy);assert.deepEqual(a.data.order,[0,1]);});

test('Fitted tray poses and spacing derive identically from guest snapshots',()=>{let seq=0;for(const id of nativeIds)for(const facing of ['right','left']){const {match,source}=scene('lyra',id,facing),b=deletionDefinition('lyra').beats,options={roster:nativeIds,clipIds:source.map(a=>Object.keys(a.clips)),matchId:1};match.mode='local';const guest=createMatch({mode:'local',fighters:source.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(source)});for(const t of [b.fallStart,b.basinContact,b.kick,b.buried,b.complete]){match.deletionElapsed=t;const raw=match.fighters.map((_,i)=>getFighterView(match,i)),wire=makeFightSnapshot(match,raw,{...options,seq:++seq,at:t});assert(wire);assert.deepEqual(registerNewDeletionViews(applyFightSnapshot(guest,wire),wire.views,source,point,tray),registerNewDeletionViews(match,raw,source,point,tray));}}});
