import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';import {join} from 'node:path';import {createHash} from 'node:crypto';import sharp from 'sharp';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {deletionDefinition} from '../public/games/system-clash/play/deletion-library.mjs';
import {newDeletionPose} from '../public/games/system-clash/play/new-deletion-library.mjs';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/deletions/',import.meta.url)),hash=b=>createHash('sha256').update(b).digest('hex'),read=id=>JSON.parse(readFileSync(join(root,id,'manifest.json'),'utf8'));
const sourceSha='5dd7b983728dde18fcfa74069321b909c64bb9d3641f192caf6093771d74178b';
const expected={doofnoobler:{clip:'hug-happy',regions:{right:[142,57,410,479],left:[687,57,408,479]},scale:220/471},'papa-oak':{clip:'rip',regions:{right:[21,555,580,675],left:[638,556,579,674]},scale:385/667}};
for(const [id,e]of Object.entries(expected))for(const facing of ['right','left'])test(`Approved whole attacker contact ${id} ${facing} keeps exact source and native alpha`,async()=>{
 const m=read(id),c=m.clips[e.clip];assert(c,'Approved contact bank is installed');const f=c.frames[facing][2],p=f.poseSource;
 assert.equal(p.sourceFile,'attacker-four-happy-opposed-source.png');assert.equal(p.sourceSha256,sourceSha);assert.deepEqual(p.sourceRect,e.regions[facing]);assert.equal(p.uniformResample,e.scale);assert.equal(f.bodyCalibration??1,1);assert.equal(f.offset,undefined,'Native key does not need anatomy or body-offset correction');assert.equal(c.contactMs,300);
 const bytes=readFileSync(join(root,id,c.file));assert.equal(hash(bytes),c.sourceSha256);const [left,top,width,height]=f.rect,raw=await sharp(bytes).extract({left,top,width,height}).ensureAlpha().raw().toBuffer();assert.equal(hash(raw),f.canonicalPixelSha256);
 for(const name of ['head','torso','legs','grip']){const [x,y]=f.attachments[name];assert(raw[(Math.round(y)*width+Math.round(x))*4+3]>128,`${name} is an actual opaque native surface`);}assert(f.anchor[1]>=f.opaqueBounds[3]-2);
 if(id==='doofnoobler')assert.equal(c.frames[facing][2].canonicalPixelSha256,c.frames[facing][3].canonicalPixelSha256,'The same exact happy whole body holds during the cuddle');
 else {assert.equal(f.ripGripContacts.length,2);const [upper,lower]=f.ripGripContacts;assert(lower[1]>upper[1],'Native palms preserve their unequal authored height');assert(f.anchor[1]-upper[1]>252.54,'Rooted native upper palm physically reaches the largest approved hanging body');assert(lower[1]-upper[1]<30.811,'Both actual palm surfaces fit even the shortest approved torso');for(const [x,y]of f.ripGripContacts)assert(raw[(Math.round(y)*width+Math.round(x))*4+3]>128);assert(f.frontOcclusion.length>=5,'Static native near forearm mask is authored, without body parts');}
});
for(const facing of ['right','left'])test(`Doof holds the approved happy whole key through the hug (${facing})`,()=>{const m=read('doofnoobler'),c=m.clips['hug-happy'];assert(c);const asset=compileFightClip(c,{width:c.sourceSize[0],height:c.sourceSize[1]},m,'delete-hug-happy'),clips=combatMetadata([{manifest:m,clips:{'delete-hug-happy':asset}}])[0],d=deletionDefinition('doofnoobler');for(const t of [d.beats.hugContact,1500,d.beats.release-.001])assert.deepEqual(newDeletionPose('attacker',t,d,clips,m.height),{clip:'delete-hug-happy',elapsed:300});});

import {createMatch,performAction,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import {registerNewDeletionViews,drawNativeRipForearm} from '../public/games/system-clash/play/new-deletion-renderer.mjs';
import {poseFrameIndex,poseScale,resolvePoseAttachments} from '../public/games/system-clash/play/fight-attachments.mjs';
const ids=['6-bit','9-bit','ash-flowers','cache-back','cliff','dj-floppydisc','doofnoobler','dr3wbaby','kaveman-brown','lyra','mac-modem','mr-nice-guy','ms-mayhem','papa-oak','stolz','wittyf0x'],assets=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url)),nativeCache=new Map(),pixelsCache=new Map();
function native(id){if(nativeCache.has(id))return nativeCache.get(id);const clips={};let manifest;for(const bank of ['fighters','arcade','deletions']){const folder=join(assets,bank,id),m=JSON.parse(readFileSync(join(folder,'manifest.json'),'utf8'));if(bank==='fighters')manifest=m;for(const [name,c]of Object.entries(m.clips)){const key=bank==='deletions'?'delete-'+name:name;const frames=Object.values(c.frames).flat(),size=c.sourceSize??[Math.max(...frames.map(f=>f.rect[0]+f.rect[2])),Math.max(...frames.map(f=>f.rect[1]+f.rect[3]))];clips[key]=compileFightClip(c,{width:size[0],height:size[1]},m,key);clips[key].file=join(folder,c.file);}}const a={manifest,clips};nativeCache.set(id,a);return a;}
function point(v,a,name){const asset=a.clips[v.clip],i=poseFrameIndex(asset,v),f=asset.data.frames[v.facing][i],p=f.attachments[name]??Object.values(resolvePoseAttachments(f,v.clip,i,v.facing,a.manifest.id))[0],s=poseScale(asset,f),o=f.offset??[0,0];return {x:v.x+(p[0]+o[0]-f.anchor[0])*s,y:620+(v.y??0)+(p[1]+o[1]-f.anchor[1])*s};}
async function pixels(asset,frame){const key=asset.file+':'+frame.rect;if(!pixelsCache.has(key)){const [left,top,width,height]=frame.rect;pixelsCache.set(key,sharp(asset.file).extract({left,top,width,height}).ensureAlpha().raw().toBuffer());}return pixelsCache.get(key);}
function opaqueDistance(p,v,asset,frame,rgba){const s=poseScale(asset,frame),o=frame.offset??[0,0],x=(p.x-v.x)/s-o[0]+frame.anchor[0],y=(p.y-620-(v.y??0))/s-o[1]+frame.anchor[1],radius=Math.ceil(6/s);let minimum=Infinity;for(let py=Math.max(0,Math.floor(y)-radius);py<Math.min(frame.rect[3],Math.ceil(y)+radius+1);py++)for(let px=Math.max(0,Math.floor(x)-radius);px<Math.min(frame.rect[2],Math.ceil(x)+radius+1);px++)if(rgba[(py*frame.rect[2]+px)*4+3]>128)minimum=Math.min(minimum,Math.hypot((px-x)*s,(py-y)*s));return minimum;}
for(const id of ids)for(const facing of ['right','left'])test(`Oak's two opaque native palm surfaces physically contact intact ${id} (${facing})`,async()=>{const art=[native('papa-oak'),native(id)],match=createMatch({mode:'practice',fighters:art.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(art)});match.fighters[0].x=300;match.fighters[1].x=300+(facing==='right'?75:-75);assert(performAction(match,0,'deletion'));match.deletionElapsed=1750;const bodyAsset=art[1].clips['delete-rip-front'],bodyFrame=bodyAsset.data.frames[match._deletionOrigin.victimFacing][0],bodyRgba=await pixels(bodyAsset,bodyFrame),alpha=new Uint8Array(bodyFrame.rect[2]*bodyFrame.rect[3]);for(let i=0;i<alpha.length;i++)alpha[i]=bodyRgba[i*4+3];const nativeMask=(a,f)=>a===bodyAsset&&f===bodyFrame?{width:f.rect[2],height:f.rect[3],alpha}:null;const v=registerNewDeletionViews(match,match.fighters.map((_,i)=>getFighterView(match,i)),art,point,{},nativeMask);assert.equal(v[0].y,0);assert(v[1].y<0);const a=art[1].clips[v[1].clip],f=a.data.frames[v[1].facing][poseFrameIndex(a,v[1])],rgba=await pixels(a,f);for(const name of ['grip','gripSecondary']){const palm=point(v[0],art[0],name),distance=opaqueDistance(palm,v[1],a,f,rgba);assert(distance<=6,`${name} contacts actual source alpha within6px, got${distance.toFixed(3)}`);}assert.equal(v[1].clip,'delete-rip-front');assert.equal(v[1].elapsed,0);});
for(const facing of ['right','left'])test(`Oak static native foreground replays the whole source key (${facing})`,()=>{const a=native('papa-oak'),v={clip:'delete-rip',elapsed:300,facing,x:430,y:0},asset=a.clips[v.clip],f=asset.data.frames[facing][2],calls=[],ctx=Object.fromEntries(['save','restore','translate','scale','beginPath','moveTo','lineTo','closePath','clip','drawImage'].map(k=>[k,(...args)=>calls.push([k,...args])]));assert(drawNativeRipForearm(ctx,v,a));const draw=calls.find(c=>c[0]==='drawImage');assert.deepEqual(draw.slice(2,6),f.rect);assert.deepEqual(draw.slice(8),f.rect.slice(2),'Whole native image dimensions are preserved through the mask');assert.deepEqual(calls.find(c=>c[0]==='scale'),['scale',1,1]);assert.equal(calls.filter(c=>c[0]==='lineTo').length,f.frontOcclusion.length-1);assert.equal(calls.filter(c=>c[0]==='drawImage').length,1);});
