import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';import {join} from 'node:path';import sharp from 'sharp';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url));const read=bank=>JSON.parse(fs.readFileSync(path.join(root,bank,'lyra/manifest.json'),'utf8'));function contactIndex(clip){const entries=clip.order.map((index,i)=>({index,start:clip.frameMs.slice(0,i).reduce((a,b)=>a+b,0),end:clip.frameMs.slice(0,i+1).reduce((a,b)=>a+b,0)}));return entries.find(e=>clip.contactMs>=e.start&&clip.contactMs<e.end).index;}
const hangingExpected={"scale":0.43,"region":[0,719,480,1536],"sourceSha256":"0d294672aeba9df840ebb6f04375c22268e9f8085cfd03078c252c1c2ba79978","originalBytes":2599121,"rgbaSha256":"9b18dfc5716d64868dbb26d86047eea74e19650b5754422f1c04958f1734a8d4","regionRgbaSha256":"c7ac128ffb07ec466b61b1d4120645bb54b686ce233a2422308bda68b7a278bb"};
const hangingHash=bytes=>createHash('sha256').update(bytes).digest('hex');
async function assertHangingSource(clip,dir){
 const source=clip.frontPoseSource,expected=hangingExpected;assert.equal(clip.poseRole,'airborne');assert.equal(clip.scale,expected.scale);assert.deepEqual(clip.order,[0]);assert.deepEqual(clip.frames.left,clip.frames.right);assert.equal(clip.frames.right.length,1);
 assert.equal(source.sourceKind,'approved-four-character-airborne-sheet');assert.equal(source.originalFile,'lift-four-airborne-approved-sheet-4-v1.png');assert.equal(source.originalBytes,expected.originalBytes);assert.deepEqual(source.originalSize,[1024,1536]);assert.equal(source.originalSha256,expected.sourceSha256);assert.deepEqual(source.sourceRegion,expected.region);assert.equal(source.nativeAnatomy.resultScale,expected.scale);assert.match(source.nativeAnatomy.method,/skull, chest and limb widths/);
 const bytes=readFileSync(join(dir,clip.file));assert.equal(hangingHash(bytes),clip.sourceSha256);const image=sharp(bytes),metadata=await image.metadata();assert.deepEqual(clip.sourceSize,[metadata.width,metadata.height]);const rgba=await image.ensureAlpha().raw().toBuffer();assert.equal(hangingHash(rgba),expected.rgbaSha256);assert.equal(hangingHash(rgba),source.nativeRgbaSha256);
 const [left,top,right,bottom]=source.sourceRegion,crop=source.crop;const region=await sharp(rgba,{raw:{width:metadata.width,height:metadata.height,channels:4}}).extract({left:-crop[0],top:-crop[1],width:right-left,height:bottom-top}).raw().toBuffer();assert.equal(hangingHash(region),expected.regionRgbaSha256);assert.equal(hangingHash(region),source.regionRgbaSha256);
 for(const facing of ['right','left'])for(const frame of clip.frames[facing]){assert.equal(frame.nativeFacing,'front');assert.equal(frame.bodyCalibration,1);assert.deepEqual(frame.rect,[0,0,metadata.width,metadata.height]);assert.equal(frame.anchor[0],metadata.width/2);assert.deepEqual(frame.attachments.ripCut,frame.attachments.torso);assert.equal(frame.attachments.ripCut[0],metadata.width/2);assert.equal(frame.poseSource,undefined,'Sheet-derived complete pose retains clip frontPoseSource rather than invented legacy native-atlas provenance');for(const point of Object.values(frame.attachments))assert(point.every(Number.isFinite)&&point[0]>=0&&point[1]>=0&&point[0]<=frame.rect[2]&&point[1]<=frame.rect[3]);}
}

test('Lyra full native4-key attack contacts select the genuine extension rather than windup',()=>{const clips=read('arcade').clips;for(const name of ['crouch-punch','crouch-kick','jump-punch','jump-kick']){assert.equal(contactIndex(clips[name]),2,name);assert.equal(new Set(clips[name].order).size,4);}});
test('Lyra35 native clips retain320 scale and floor recovery seams plus one approved hanging source',async()=>{let total=0,hanging=0;for(const b of ['fighters','arcade','deletions']){const m=read(b);assert.equal(m.height,320);assert.equal(m.scale,1);for(const [name,c]of Object.entries(m.clips)){assert(fs.statSync(path.join(root,b,'lyra',c.file)).size>100);if(name==='rip-front'){assert.equal(b,'deletions');await assertHangingSource(c,path.join(root,b,'lyra'));hanging++;}else total++;}}assert.equal(total,35);assert.equal(hanging,1);const {knockdown,getup}=read('fighters').clips;assert.equal(knockdown.file,getup.file);for(const f of ['right','left'])assert.deepEqual(knockdown.frames[f].at(-1),getup.frames[f][0]);assert.equal(knockdown.frames.right.at(-1).poseSource.cell,8);assert.equal(knockdown.frames.left.at(-1).poseSource.cell,12);});
test('Lyra claws and rear-leg kick use six complete native bodies from actual layouts',()=>{const {claw,['litter-kick']:kick}=read('deletions').clips;for(const c of [claw,kick])for(const f of ['right','left'])assert.equal(c.frames[f].length,6);assert.equal(kick.contactMs,320);assert.equal(contactIndex(kick),3);assert.equal(claw.contactMs,280);assert.equal(contactIndex(claw),2);});
function fraction(frame,site){const [l,t,r,b]=frame.opaqueBounds,p=frame.attachments[site];return [(p[0]-l)/(r-l),(p[1]-t)/(b-t)];}
test('Lyra contact landmarks stay on measured guard hands, paws and actual crouching head',()=>{const clips={...read('fighters').clips,...read('arcade').clips};for(const facing of ['right','left']){const low=fraction(clips['low-punch'].frames[facing][2],'strike'),toe=fraction(clips['low-kick'].frames[facing][2],'strike'),power=fraction(clips['power-kick'].frames[facing][2],'strike'),head=fraction(clips['crouch-high-kick'].frames[facing][2],'head'),grip=fraction(clips.kick.frames[facing][2],'grip');assert(low[1]>.34&&low[1]<.42);assert(toe[1]>.46&&toe[1]<.56);assert(power[1]>.27&&power[1]<.35);assert(head[1]>.34&&head[1]<.44);assert(Math.abs(grip[0]-(facing==='right'?.26:.74))<.015);for(const n of ['kick','low-kick','crouch-kick','jump-kick','crouch-high-kick','power-kick']){const a=clips[n].frames[facing][2].attachments;assert(Math.hypot(a.grip[0]-a.strike[0],a.grip[1]-a.strike[1])>35,`${n} weapon grip remains on hand, separate from attacking paw`);}}});
test('Lyra backward bury contact replaces exactly one genuine native key per facing',()=>{const c=read('deletions').clips['litter-kick'];for(const [facing,cell] of [['left',0],['right',1]]){for(let i=0;i<6;i++)assert.equal(c.frames[facing][i].poseSource.sourceFile,i===3?'deletions-backward-bury-contact.png':'deletions-litter-kick-six.png');assert.equal(c.frames[facing][3].poseSource.cell,cell);assert.equal(c.frames[facing][3].poseSource.kind,'generated');assert(c.frames[facing][3].poseSource.uniformResample>.39&&c.frames[facing][3].poseSource.uniformResample<.41);assert.equal(new Set(c.frames[facing].map(f=>f.canonicalPixelSha256)).size,6);}});
