import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {poseFrameIndex,poseScale,resolvePoseAttachments} from '../public/games/system-clash/play/fight-attachments.mjs';
import {createMatch,performAction,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import {registerNewDeletionViews,litterBoxGeometry} from '../public/games/system-clash/play/new-deletion-renderer.mjs';
import {deletionDefinition} from '../public/games/system-clash/play/deletion-library.mjs';
import {makeFightSnapshot,applyFightSnapshot} from '../public/games/system-clash/play/fight-network-state.mjs';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url));
function size(file){const bytes=Buffer.alloc(64),fd=fs.openSync(file,'r');try{fs.readSync(fd,bytes,0,64,0);}finally{fs.closeSync(fd);}if(bytes[0]===137)return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};const k=bytes.toString('ascii',12,16);assert.equal(k,'VP8X');return {width:1+bytes.readUIntLE(24,3),height:1+bytes.readUIntLE(27,3)};}
function native(id){const clips={};let manifest;for(const bank of ['fighters','arcade','deletions']){const folder=path.join(root,bank,id),data=JSON.parse(fs.readFileSync(path.join(folder,'manifest.json'),'utf8'));if(bank==='fighters')manifest=data;for(const [name,clip] of Object.entries(data.clips)){const key=bank==='deletions'?'delete-'+name:name;clips[key]=compileFightClip(clip,size(path.join(folder,clip.file)),data,key);}}return {manifest,clips};}
const nativeIds=['6-bit','9-bit','ash-flowers','cache-back','cliff','dj-floppydisc','doofnoobler','dr3wbaby','kaveman-brown','lyra','mac-modem','mr-nice-guy','ms-mayhem','papa-oak','stolz','wittyf0x'];
const art=Object.fromEntries(nativeIds.map(id=>[id,native(id)]));
const nativeTray={additional:{'litter-protocol':{manifest:JSON.parse(fs.readFileSync(path.join(root,'deletions/litter-protocol/atlas.json'),'utf8'))}}};
function point(v,a,site){const c=a.clips[v.clip],i=poseFrameIndex(c,v),f=c.data.frames[v.facing][i],o=f.offset??[0,0],raw=f.attachments?.[site],p=raw?{x:raw[0],y:raw[1]}:resolvePoseAttachments(f,v.clip,i,v.facing,a.manifest.id)[site],s=poseScale(c,f);return {x:v.x+(p.x+o[0]-f.anchor[0])*s,y:620+(v.y??0)+(p.y+o[1]-f.anchor[1])*s};}
function scene(hero,victim,facing='right'){const source=[art[hero],art[victim]],match=createMatch({mode:'practice',fighters:source.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(source)});match.fighters[0].x=facing==='right'?210:2350;match.fighters[1].x=match.fighters[0].x+(facing==='right'?1:-1)*75;assert(performAction(match,0,'deletion'));return {match,source};}
function views(match,source,t){match.deletionElapsed=t;return registerNewDeletionViews(match,match.fighters.map((_,i)=>getFighterView(match,i)),source,point,nativeTray);}

function nativePose(match,source,view,index){return match.fighters[index]._clips[view.clip].combatPoses.frames[view.facing][poseFrameIndex(source[index].clips[view.clip],view)];}
function regionDistance(point,view,region){return Math.hypot(Math.max(view.x+region.left-point.x,0,point.x-view.x-region.right),Math.max(620+(view.y??0)+region.top-point.y,0,point.y-620-(view.y??0)-region.bottom));}
function worldHalfBounds(piece,a){const asset=a.clips[piece.clip],frame=asset.data.frames[piece.facing][poseFrameIndex(asset,piece)],scale=poseScale(asset,frame),offset=frame.offset??[0,0],b=frame.opaqueBounds,cut=piece.cutX,pivot=piece.rotationPivotPoint,angle=piece.rotation??0,world={x:piece.x+(pivot.x+offset[0]-frame.anchor[0])*scale,y:620+piece.y+(pivot.y+offset[1]-frame.anchor[1])*scale},left=piece.halfMask<0?b[0]:cut,right=piece.halfMask<0?cut:b[2];return [[left,b[1]],[right,b[1]],[left,b[3]],[right,b[3]]].map(([x,y])=>({x:world.x+((x-pivot.x)*Math.cos(angle)-(y-pivot.y)*Math.sin(angle))*scale,y:world.y+((x-pivot.x)*Math.sin(angle)+(y-pivot.y)*Math.cos(angle))*scale}));}
for(const facing of ['right','left'])for(const id of nativeIds){
 test(`Doof hugs the upright native ${id} upper torso and escapes peacefully (${facing})`,()=>{const {match,source}=scene('doofnoobler',id,facing),b=deletionDefinition('doofnoobler').beats,v=views(match,source,b.hugContact),grip=point(v[0],source[0],'grip'),torso=point(v[1],source[1],'torso'),head=point(v[1],source[1],'head');assert.equal(v[1].clip,'high');assert.equal(v[1].y,0);assert(Math.abs(grip.x-torso.x)<2);assert(Math.abs(grip.y-(torso.y+(head.y-torso.y)*.65))<2);assert.equal(views(match,source,b.escaped)[1].opacity,0);assert.equal(views(match,source,b.escaped)[0].y,0);});
 test(`Oak contacts then lifts native ${id}, preserving one source through the whole tear (${facing})`,()=>{const {match,source}=scene('papa-oak',id,facing),b=deletionDefinition('papa-oak').beats,start=views(match,source,b.gripContact);assert.equal(start[1].y,0);assert.equal(start[1].splitBody,undefined);const held=views(match,source,b.strain);assert(held[1].y<0);assert.equal(held[0].y,0);const palm=point(held[0],source[0],'grip'),centre=point(held[1],source[1],'torso');if(id==='papa-oak'&&facing==='left'){const native=source[1].clips['delete-rip-front'].data.frames[held[1].facing][0],offset=native.offset??[0,0],waistY=620+held[1].y+(357.12+offset[1]-native.anchor[1])*poseScale(source[1].clips['delete-rip-front'],native);assert(Math.abs(palm.y-waistY)<.01,'The real left palm meets the independently measured opaque lower torso');assert(Math.abs(held[1].y+26.7642)<.01,'Actual waist contact lifts the complete approved body26.7642px');}else assert(Math.abs(palm.y-centre.y)<2,'The real closed native hand meets the source torso vertically');const body=nativePose(match,source,held[1],1),front=body.hurt.find(r=>r.site==='torso');assert(Math.abs(point(held[0],source[0],'grip').x-(held[1].x+(match._deletionOrigin.direction>0?front.right:front.left)))<2,'Front bark palm touches the real outer torso edge, so it remains visible while the victim covers the rear hand');assert.equal(poseFrameIndex(source[0].clips['delete-rip'],held[0]),2);const frozen=views(match,source,b.rip)[1].splitPieces;assert.equal(frozen.length,2);const hanging=source[1].clips['delete-rip-front'],native=hanging.data.frames[start[1].facing][0];for(const piece of frozen){assert.equal(piece.clip,'delete-rip-front');assert.equal(piece.elapsed,0);assert.equal(piece.cutX,native.attachments.ripCut[0]);assert.equal(piece.cutX,native.rect[2]/2,'The accepted whole-body source tears along its unchanged vertical middle');assert.deepEqual(piece.rotationPivotPoint,{x:native.attachments.ripCut[0],y:native.attachments.ripCut[1]});}
 for(const t of [b.rip,b.rip+200,b.separated]){const capture=views(match,source,t),asset=source[0].clips['delete-rip'],frame=asset.data.frames[capture[0].facing][poseFrameIndex(asset,capture[0])],scale=poseScale(asset,frame),offset=frame.offset??[0,0],hands=frame.attachments?.ripHands??(capture[0].facing==='right'?[[27,110],[391,109]]:[[28,100],[397,89]]);for(const [i,piece]of capture[1].splitPieces.entries()){const body=source[1].clips[piece.clip],bodyFrame=body.data.frames[piece.facing][poseFrameIndex(body,piece)],bodyScale=poseScale(body,bodyFrame),bodyOffset=bodyFrame.offset??[0,0],pivot=piece.rotationPivotPoint,cut={x:piece.x+(pivot.x+bodyOffset[0]-bodyFrame.anchor[0])*bodyScale,y:620+piece.y+(pivot.y+bodyOffset[1]-bodyFrame.anchor[1])*bodyScale},hand={x:capture[0].x+(hands[i][0]+offset[0]-frame.anchor[0])*scale,y:620+capture[0].y+(hands[i][1]+offset[1]-frame.anchor[1])*scale};assert(Math.hypot(cut.x-hand.x,cut.y-hand.y)<2,'Every real cut edge meets its separately authored spread hand');}}
for(let t=b.rip;t<=b.settled;t+=50)for(const piece of views(match,source,t)[1].splitPieces){assert.equal(piece.clip,frozen[0].clip);assert.equal(piece.elapsed,frozen[0].elapsed);assert.equal(piece.facing,frozen[0].facing);assert.equal(piece.cutX,frozen[0].cutX);assert(worldHalfBounds(piece,source[1]).every(p=>p.y<=628),'Every rotated source half stays above the floor');}const settled=views(match,source,b.settled)[1];for(const piece of settled.splitPieces){assert(Math.abs(Math.max(...worldHalfBounds(piece,source[1]).map(p=>p.y))-620)<2,'The original rigid source half lies on the floor');assert(worldHalfBounds(piece,source[1]).every(p=>p.x>=0&&p.x<=1280),'Full native half remains in the ending viewport');}for(const t of [b.present,b.complete])assert.deepEqual(views(match,source,t)[1].splitPieces,settled.splitPieces);});
 test(`Lyra slashes intersect native ${id} upper body before native basin fall (${facing})`,()=>{const {match,source}=scene('lyra',id,facing),b=deletionDefinition('lyra').beats;assert(views(match,source,b.boxSet)[1].y===0);for(const t of [b.scratch1,b.scratch2]){const v=views(match,source,t),paw=point(v[0],source[0],'strike'),body=nativePose(match,source,v[1],1),attack=nativePose(match,source,v[0],0);assert.equal(v[0].y,0);assert(v[1].y<=0);assert(body.bounds.top+620+v[1].y>=140);assert(body.hurt.filter(r=>r.site!=='legs').some(r=>regionDistance(paw,v[1],r)<=attack.strikeRadius));}assert.equal(views(match,source,b.retreat+100)[0].clip,'walk');assert.equal(views(match,source,b.turn)[1].clip,'delete-rip-front');assert.equal(views(match,source,b.litterImpact+100)[1].clip,'delete-crumpled');assert.equal(views(match,source,b.buried)[1].y,190);assert(views(match,source,b.complete)[0].y>0);});
}
test('All repaired captures, masks and endings recompute identically from public guest state',()=>{let seq=0;for(const id of ['doofnoobler','lyra','papa-oak'])for(const victim of nativeIds)for(const facing of ['right','left']){const {match,source}=scene(id,victim,facing),b=deletionDefinition(id).beats,options={roster:nativeIds,clipIds:source.map(a=>Object.keys(a.clips)),matchId:1};match.mode='local';const guest=createMatch({mode:'local',fighters:source.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(source)});for(const t of [b.contact,b.final,b.complete]){match.deletionElapsed=t;const raw=match.fighters.map((_,i)=>getFighterView(match,i)),wire=makeFightSnapshot(match,raw,{...options,seq:++seq,at:t});assert(wire);assert.deepEqual(registerNewDeletionViews(applyFightSnapshot(guest,wire),wire.views,source,point),registerNewDeletionViews(match,raw,source,point));}}});

for(const facing of ['right','left'])for(const id of nativeIds)test(`Lyra completes native ${id} airborne-to-basin fall before litter kick (${facing})`,()=>{
 const {match,source}=scene('lyra',id,facing),b=deletionDefinition('lyra').beats;
 assert(b.fallStart>=b.scratch3&&b.basinContact<b.basinSettled&&b.basinSettled<b.kick,'Scratch, visible fall and settled basin precede the kick');
 const before=views(match,source,b.fallStart-.001)[1],start=views(match,source,b.fallStart)[1],beforeTorso=point(before,source[1],'torso'),startTorso=point(start,source[1],'torso');
 assert.equal(start.clip,'delete-rip-front');assert.equal(poseFrameIndex(source[1].clips[start.clip],start),0,'One accepted hanging key starts the drop');assert(Math.hypot(startTorso.x-beforeTorso.x,startTorso.y-beforeTorso.y)<2,'No whole-body teleport at release');
 let previous=startTorso;for(let t=b.fallStart;t<b.basinContact;t+=10){const v=views(match,source,t)[1],torso=point(v,source[1],'torso');assert.equal(v.clip,'delete-rip-front');assert.equal(v.elapsed,0);assert.equal(poseFrameIndex(source[1].clips[v.clip],v),0,'The exact whole hanging source stays frozen before basin impact');assert.equal(v.facing,match._deletionOrigin.victimFacing);const tray=litterBoxGeometry(match,nativeTray,source);assert(torso.x>tray.left&&torso.x<tray.right,'Continuous native torso trajectory reaches the authored opening');assert(Math.abs(torso.y-previous.y)<15,'Native frame changes keep the body path continuous');assert(!v.splitBody&&!v.halfMask&&!(v.rotation??0));previous=torso;}
 const landed=views(match,source,b.basinContact)[1],settled=views(match,source,b.basinSettled)[1],kick=views(match,source,b.kick)[1],body=nativePose(match,source,settled,1);
 assert.equal(landed.clip,'delete-crumpled');assert.equal(settled.clip,'delete-crumpled');assert.equal(poseFrameIndex(source[1].clips['delete-crumpled'],settled),['lyra','papa-oak','doofnoobler'].includes(id)?2:source[1].clips['delete-crumpled'].timeline.entries.at(-1).index,'Whole native compact floor key is already settled before the kick');
 assert(Math.abs(620+settled.y+body.bounds.bottom-litterBoxGeometry(match,nativeTray,source).basinFloor)<2,'Native bottom lands on the authored litter plane rather than the stage floor');assert(point(settled,source[1],'torso').y>startTorso.y+15,'A visible downward fall enters the basin');assert.deepEqual([kick.clip,kick.elapsed,kick.x,kick.y,kick.facing],[settled.clip,settled.elapsed,settled.x,settled.y,settled.facing],'Settled victim remains stable until litter arrives');
 const atBurial=views(match,source,b.buried)[1];assert.equal(atBurial.opacity,0);assert.equal(atBurial.clip,'delete-crumpled');
});

test('Oak left self capture uses actual opaque lower-torso pixels while preserving the accepted whole-body source',async()=>{
 const {match,source}=scene('papa-oak','papa-oak','left'),b=deletionDefinition('papa-oak').beats,v=views(match,source,b.strain),asset=source[1].clips['delete-rip-front'],frame=asset.data.frames[v[1].facing][0],sharp=(await import('sharp')).default;
 const pixels=await sharp(path.join(root,'deletions/papa-oak',asset.data.file)).extract({left:frame.rect[0],top:frame.rect[1],width:frame.rect[2],height:frame.rect[3]}).ensureAlpha().raw().toBuffer();
 for(const [x,y]of [[296,357],[170,357]])assert(pixels[(y*frame.rect[2]+x)*4+3]>=128,'Measured native lower-torso centre and contacted left edge are opaque source pixels');
 assert.equal(v[1].clip,'delete-rip-front');assert.equal(v[1].elapsed,0);assert(Math.abs(v[1].y+26.7642)<.01);
});