import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url));
const read=(bank)=>JSON.parse(fs.readFileSync(path.join(root,bank,'papa-oak/manifest.json'),'utf8'));
const index=clip=>{let ms=0;for(let i=0;i<clip.order.length;i++){if(ms>=clip.contactMs)return clip.order[i];ms+=clip.frameMs[i];}return clip.order.at(-1);};
test('Papa retains30 whole-body native clips at385 with8 genuine punch keys and correct chronology',()=>{
 let count=0;for(const bank of ['fighters','arcade','deletions']){const manifest=read(bank);assert.equal(manifest.height,385);assert.equal(manifest.scale,1);for(const [name,clip] of Object.entries(manifest.clips)){count++;assert(fs.statSync(path.join(root,bank,'papa-oak',clip.file)).size>100);for(const facing of ['right','left'])for(const frame of clip.frames[facing]){assert(frame.poseSource.sourceFile.endsWith('-source.png'));assert(!frame.poseSource.sourceFile.includes('6-bit'));assert(frame.anchor[1]>=frame.opaqueBounds[3]-2);for(const point of Object.values(frame.attachments))assert(point[0]>=0&&point[1]>=0&&point[0]<=frame.rect[2]&&point[1]<=frame.rect[3]);}}}
 assert.equal(count,30);const punch=read('fighters').clips.punch;assert.equal(index(punch),4);assert.equal(punch.contactMs,170);assert.equal(punch.activeEndMs,280);for(const facing of ['right','left']){assert.equal(punch.frames[facing].length,8);assert.equal(new Set(punch.frames[facing].map(f=>f.canonicalPixelSha256)).size,8);}
});
test('Papa knockdown/getup share the exact same floor pose and encoded atlas',()=>{const {knockdown,getup}=read('fighters').clips;assert.equal(knockdown.file,getup.file);for(const facing of ['right','left'])assert.deepEqual(knockdown.frames[facing].at(-1),getup.frames[facing][0]);});
test('Every Papa kick keeps the actual hand grip distinct from its toe strike for held weapons',()=>{const clips={...read('fighters').clips,...read('arcade').clips};for(const name of ['kick','low-kick','crouch-kick','jump-kick','crouch-high-kick','power-kick']){const clip=clips[name];for(const facing of ['right','left']){const {grip,strike}=clip.frames[facing][index(clip)].attachments;assert(Math.hypot(grip[0]-strike[0],grip[1]-strike[1])>60,name+': weapon must stay on a hand, separate from the striking foot');}}});
test('Lyra real litter prop has4 distinct native states, floor anchors and authored foreground rim',()=>{const dir=path.join(root,'deletions/litter-protocol'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'atlas.json'),'utf8'));assert.equal(manifest.drawWidth,460);assert(fs.statSync(path.join(dir,manifest.file)).size>100);assert.deepEqual(Object.keys(manifest.frames),['open','captured','impact','dead']);assert.equal(new Set(Object.values(manifest.frames).map(f=>f.canonicalPixelSha256)).size,4);for(const f of Object.values(manifest.frames)){assert(f.anchor[1]<=f.rect[3]);assert(f.rimY>0&&f.rimY<f.anchor[1]);assert(f.opaqueBounds[3]-f.anchor[1]<=3);}});
