import test from 'node:test';import assert from 'node:assert/strict';
import {createTournamentClient,tournamentBattleURL,ORDINARY_FIGHTERS} from '../public/games/system-clash/play/tournament-online.mjs';
const base='https://www.barcode-network.com/games/system-clash/play/tournament-online.html';
test('assigned players enter the same event/bout with the correct room role',()=>{const event={code:'ABC123',selfEntrantId:'one'},bout={id:'bout1',p1:'one',p2:'two',roomCode:'ROOM12'};const url=tournamentBattleURL(base,event,bout);assert.equal(url.pathname,'/games/system-clash/play/online.html');assert.equal(url.searchParams.get('event'),'ABC123');assert.equal(url.searchParams.get('room'),'ROOM12');assert.equal(url.searchParams.get('role'),'host');assert.equal(tournamentBattleURL(base,{...event,selfEntrantId:'two'},bout).searchParams.get('role'),'guest');assert.throws(()=>tournamentBattleURL(base,{...event,selfEntrantId:'audience'},bout),/belongs/);assert.throws(()=>tournamentBattleURL(base,{code:'ABC123'},bout),/belongs/);});
test('ordinary tournament selection preserves locked bosses',()=>{assert.equal(ORDINARY_FIGHTERS.size,17);assert.equal(ORDINARY_FIGHTERS.has('bnl-01'),false);assert.equal(ORDINARY_FIGHTERS.has('9-bit'),false);});
test('client uses site cookies, private reads and unique mutation receipts',async()=>{const calls=[],client=createTournamentClient({uuid:()=> '11111111-1111-4111-8111-111111111111',fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({code:'ABC123'})};}});await client.list();await client.get('ABC123');await client.action('approve',{code:'ABC123',entrantId:'seat-2'});assert.equal(calls[0].options.credentials,'same-origin');assert.equal(calls[0].options.cache,'no-store');assert.equal(calls[1].url,'/api/games/system-clash/tournaments?code=ABC123');const body=JSON.parse(calls[2].options.body);assert.equal(body.requestId,'11111111-1111-4111-8111-111111111111');assert.equal(body.entrantId,'seat-2');assert.equal(body.action,'approve');});
test('expired website account produces a clear gate instead of a guest room',async()=>{const client=createTournamentClient({fetch:async()=>({ok:false,status:401,json:async()=>({error:'Sign in to play online.'})})});await assert.rejects(client.list(),e=>e.status===401&&e.message==='Sign in to play online.');});

test('an uncertain create retry reuses its receipt and a known response starts a fresh command',async()=>{const bodies=[];let attempt=0,nonce=0;const client=createTournamentClient({uuid:()=>String(++nonce),fetch:async(url,options)=>{bodies.push(JSON.parse(options.body));if(++attempt===1)throw new Error('Connection closed after request');return{ok:true,json:async()=>({code:'ABC123'})};}});const fields={title:'Private fixture',settings:{maxPlayers:16}};await assert.rejects(client.action('create',fields));await client.action('create',fields);assert.equal(bodies[0].requestId,bodies[1].requestId);await client.action('create',fields);assert.notEqual(bodies[1].requestId,bodies[2].requestId);});
test('unknown mutation retry keeps its original revision even after a later refresh',async()=>{const bodies=[];let fail=true;const client=createTournamentClient({uuid:()=>Math.random().toString(),fetch:async(url,options)=>{bodies.push(JSON.parse(options.body));if(fail){fail=false;throw new Error('timeout');}return{ok:true,json:async()=>({code:'ABC123'})};}});await assert.rejects(client.action('approve',{code:'ABC123',entrantId:'seat-2',expectedRevision:2}));await client.action('approve',{code:'ABC123',entrantId:'seat-2',expectedRevision:3});assert.deepEqual(bodies[0],bodies[1]);});
test('featured viewer stays a spectator and mirrors source pause before each snapshot',async()=>{const {featuredFightURL,featuredSnapshotPackets}=await import('../public/games/system-clash/play/tournament-watch.mjs');const url=featuredFightURL(base,{fighters:[{id:'6-bit',name:'Fixture One'},{id:'cache-back',name:'Fixture Two'}],stage:'radio-studio',matchId:1});assert.equal(url.searchParams.get('seat'),'1');assert.equal(url.searchParams.get('spectator'),'1');assert.equal(url.searchParams.has('token'),false);assert.throws(()=>featuredFightURL(base,{fighters:[],stage:'foreign',matchId:1}));for(const paused of[true,false]){const snapshot={seq:10,state:{paused,pauseReason:paused?'manual':null}},packets=featuredSnapshotPackets(snapshot);assert.equal(packets[0].type,'pause');assert.equal(packets[0].paused,paused);assert.equal(packets[0].snapshotSeq,9);assert.equal(packets[1].snapshot,snapshot);}});
test('spectator scheduling maintains a bounded fast cadence and backs off measured slow or failed requests',async()=>{
 const {featuredPollDelay}=await import('../public/games/system-clash/play/tournament-watch.mjs');
 assert.equal(featuredPollDelay(0),125);assert.equal(featuredPollDelay(70),55);assert.equal(featuredPollDelay(120),25);
 assert.equal(featuredPollDelay(250),250);assert.equal(featuredPollDelay(900),900);assert.equal(featuredPollDelay(6000),1500);
 assert.equal(featuredPollDelay(20,{failed:true}),1000);assert.equal(featuredPollDelay(10000,{failed:true}),5000);assert.equal(featuredPollDelay(0,{hidden:true}),1000);
});

test('featured replay identity includes its source generation even with the same bout and match number',async()=>{
 const {featuredBroadcastIdentity}=await import('../public/games/system-clash/play/tournament-watch.mjs'),first={tournament:{currentBoutId:'same-bout',broadcastId:'a'.repeat(64)},match:{matchId:1}},replay={...first,tournament:{...first.tournament,broadcastId:'b'.repeat(64)}};
 assert.notEqual(featuredBroadcastIdentity(first),featuredBroadcastIdentity(replay));assert.equal(featuredBroadcastIdentity({...first,match:null}),null);assert.throws(()=>featuredBroadcastIdentity({...first,tournament:{currentBoutId:'same-bout'}}));
});
