import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {compilePoseRenderTimeline,samplePoseTween,poseTweenMesh,drawPoseMesh,drawPoseTween,poseTweenCacheSize} from '../public/games/system-clash/play/fight-pose-tween.mjs';
import {poseFrameIndex,poseTransform} from '../public/games/system-clash/play/fight-attachments.mjs';
import {walkRig} from '../public/games/system-clash/play/fight-walk-rig.mjs';
import {createFightRenderer} from '../public/games/system-clash/play/fight-renderer.mjs';
import {createOnlineCombatController,makeFightSnapshot} from '../public/games/system-clash/play/fight-network-state.mjs';
import {createMatch,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
const ROOT=new URL('../public/games/system-clash/play/',import.meta.url);
const read=(bank,id)=>JSON.parse(readFileSync(new URL(`assets/${bank}/${id}/manifest.json`,ROOT),'utf8'));
const fake=c=>({width:Math.max(...Object.values(c.frames).flat().map(f=>f.rect[0]+f.rect[2])),height:Math.max(...Object.values(c.frames).flat().map(f=>f.rect[1]+f.rect[3]))});
const ids=JSON.parse(readFileSync(new URL('assets/fight-roster.json',ROOT),'utf8')).fighters.filter(f=>f.enabled).map(f=>f.id);
test('every native animation gains distinct visual intermediates without changing authoritative keys or timeline',()=>{
 let total=0,four=0,eight=0;
 for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const before=JSON.stringify(c),a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name),original=JSON.stringify(a.timeline),r=a.renderTimeline??compilePoseRenderTimeline(a),n=c.frames.right.length,active=new Set(a.timeline.entries.map(e=>e.index)).size;assert.equal(JSON.stringify(c),before);assert.equal(JSON.stringify(a.timeline),original);assert.equal(r.poseCount,active>1?n+2:active,`${id}/${bank}/${name}`);assert.equal(r.duration,a.timeline.duration);assert.equal(new Set(r.poses.map(p=>p.kind==='native'?`n${p.index}`:`t${p.from}/${p.to}/${p.amount}`)).size,r.poseCount);if(n===4)four++;if(n===8)eight++;total++;}}
 assert.equal(total,683);assert.equal(four,424);assert.equal(eight,27);
});
test('inserted visual poses leave exact native contact, impact hold, recovery endpoints and explicit choreography untouched',()=>{
 for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name);for(const facing of ['left','right']){assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:0}),null);assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:a.timeline.duration-.001}),null);assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:100,frameIndex:0}),null);for(const t of [c.contactMs,c.activeEndMs,c.liftMs,c.releaseMs,c.alignMs].filter(Number.isFinite))assert.equal(samplePoseTween(a,{clip:a.name,facing,elapsed:t}),null,`${id}/${name}/${facing}@${t}`);}}}
});
test('native width and rigid head mesh stay exact while a true transition changes lower pixels',()=>{
 const m=read('fighters','6-bit'),c=m.clips.walk,a=compileFightClip(c,fake(c),m,'walk');let sampled=null;for(const entry of a.renderTimeline.entries){sampled=samplePoseTween(a,{clip:'walk',facing:'right',elapsed:(entry.start+entry.end)/2});if(sampled)break;}assert(sampled);const mesh=poseTweenMesh(a,{clip:'walk',facing:'right'},sampled);const f=c.frames.right[sampled.from],tr=poseTransform(a,f),head=f.attachments.head,headY=head[1]*.5;const p=mesh.map({x:head[0]-8,y:headY}),q=mesh.map({x:head[0]+8,y:headY});assert(Math.abs(q.x-p.x-16*tr.sx)<1e-9,'Rigid skull width cannot change');assert.equal(p.y,q.y);assert(mesh.vertices.some(v=>Math.hypot(v.destination.x-tr.point(v.source).x,v.destination.y-tr.point(v.source).y)>.1),'Intermediate is a changed pose, not a held crop');
});
test('reduced motion, explicit frame and masked/body-cut composition retain native rendering',()=>{
 const m=read('fighters','6-bit'),c=m.clips.walk,a=compileFightClip(c,fake(c),m,'walk'),ctx={canvas:{},drawImage(){throw Error('No raster should be drawn');}};for(const view of [{reducedMotion:true},{frameIndex:1},{halfMask:1},{rotation:1},{eraseProgress:.5},{aftermath:{region:{}}}])assert.equal(drawPoseTween(ctx,a,{clip:'walk',facing:'right',elapsed:60,...view}),false);
});
test('combat metadata derives only original native poses when the visual timeline is present',()=>{
 const m=read('fighters','9-bit'),c=m.clips.punch,a=compileFightClip(c,fake(c),m,'punch'),withVisual=combatMetadata([{manifest:m,clips:{punch:a}}]);delete a.renderTimeline;const native=combatMetadata([{manifest:m,clips:{punch:a}}]);assert.deepEqual(withVisual,native);
});

test('a visual transition never rolls back to its source pose before its next native key',()=>{
 for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name),r=a.renderTimeline;for(let i=0;i<r.entries.length;i++){const pose=r.poses[r.entries[i].pose];if(pose.kind!=='tween')continue;let last=pose.amount;for(let j=i+1;j<r.entries.length;j++){const next=r.poses[r.entries[j].pose];if(next.kind==='native'){assert.equal(next.index,pose.to,`${id}/${bank}/${name}: future pose cannot return to original before key boundary`);break;}assert.equal(next.from,pose.from);assert.equal(next.to,pose.to);assert(next.amount>last);last=next.amount;}}}}
});
test('all inserted facing poses deform measured native geometry rather than padding the holds',()=>{
 let added=0;for(const id of ids)for(const bank of ['fighters','arcade','deletions']){const m=read(bank,id);for(const[name,c]of Object.entries(m.clips)){const a=compileFightClip(c,fake(c),m,bank==='deletions'?'delete-'+name:name);for(const facing of ['left','right'])for(const pose of a.renderTimeline.poses){if(pose.kind!=='tween')continue;const mesh=poseTweenMesh(a,{facing},pose),tr=poseTransform(a,mesh.frame),maximum=Math.max(...mesh.vertices.map(v=>Math.hypot(v.destination.x-tr.point(v.source).x,v.destination.y-tr.point(v.source).y)));assert(maximum>.01,`${id}/${bank}/${name}/${facing} must add real source geometry, not a duplicate hold`);for(const v of mesh.vertices)assert(Number.isFinite(v.destination.x)&&Number.isFinite(v.destination.y),'Every rendered mesh vertex is finite');for(let y=0;y<mesh.rows;y++)for(let x=0;x<mesh.columns;x++){const i=y*(mesh.columns+1)+x;for(const triple of [[i,i+1,i+mesh.columns+1],[i+1,i+mesh.columns+2,i+mesh.columns+1]]){const [p,q,r]=triple.map(k=>mesh.vertices[k].destination);assert((q.x-p.x)*(r.y-p.y)-(r.x-p.x)*(q.y-p.y)>0,`${id}/${bank}/${name}/${facing}: native texture triangle cannot fold`);}}added++;}}}assert.equal(added,2702);
});
const require=createRequire(import.meta.url);let nativeCanvas=null;try{nativeCanvas=require(process.env.SYSTEM_CLASH_CANVAS_MODULE??'@napi-rs/canvas');}catch{}
test('32 actual native raster intermediates remain single opaque bodies and reuse bounded lazy caches',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas;let scenes=0;const hash=b=>createHash('sha256').update(b).digest('hex');
 for(const id of ids.filter(id=>id!=='bnl-01').slice(0,16)){const m=read('fighters',id),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL(`assets/fighters/${id}/${c.file}`,ROOT))),a=compileFightClip(c,image,m,'walk');for(const facing of ['left','right']){const e=a.renderTimeline.entries.find(e=>a.renderTimeline.poses[e.pose].kind==='tween'),view={clip:'walk',facing,elapsed:(e.start+e.end)/2},sample=samplePoseTween(a,view),frame=c.frames[facing][sample.from],tr=poseTransform(a,frame),canvas=createCanvas(640,600),ctx=canvas.getContext('2d'),native=createCanvas(640,600),n=native.getContext('2d');n.drawImage(image,...frame.rect,320+tr.tx,560+tr.ty,frame.rect[2]*tr.sx,frame.rect[3]*tr.sy);assert(drawPoseTween(ctx,a,view,{frame,transform:tr,dx:320+tr.tx,dy:560+tr.ty,canvasFactory:createCanvas}));const pixels=ctx.getImageData(0,0,640,600).data;assert.notEqual(hash(pixels),hash(n.getImageData(0,0,640,600).data),`${id}/${facing} adds a raster pose`);let occupied=0,bottom=0;for(let y=0;y<600;y++)for(let x=0;x<640;x++)if(pixels[(y*640+x)*4+3]>48){occupied++;bottom=Math.max(bottom,y);}assert(occupied>500);assert(bottom<=561,'Interpolated native feet cannot fall through the stage');const before=hash(pixels),cacheCount=poseTweenCacheSize(a);ctx.clearRect(0,0,640,600);assert(drawPoseTween(ctx,a,view,{frame,transform:tr,dx:320+tr.tx,dy:560+tr.ty,canvasFactory(){throw Error('Warm rendering must reuse the cached native raster');}}));assert.equal(hash(ctx.getImageData(0,0,640,600).data),before);assert.equal(poseTweenCacheSize(a),cacheCount);assert(cacheCount<=32);scenes++;}}assert.equal(scenes,32);
});
test('a native mesh cache stays bounded even across many source phases',{skip:!nativeCanvas},()=>{
 const {createCanvas}=nativeCanvas,image=createCanvas(20,30),ic=image.getContext('2d');ic.fillStyle='#f0f';ic.fillRect(3,2,14,28);const frame={rect:[0,0,20,30],anchor:[10,30],opaqueBounds:[3,2,17,30]},asset={image,scale:1,name:'idle',fighterId:'test',data:{frames:{right:[frame],left:[frame]}},timeline:{entries:[{index:0,start:0,end:100}],duration:100}},ctx=createCanvas(100,100).getContext('2d'),tr=poseTransform(asset,frame);for(let k=0;k<40;k++)assert(drawPoseMesh(ctx,asset,frame,p=>tr.point(p),{x:50,y:60,canvasFactory:createCanvas,cacheKey:String(k)}));assert.equal(poseTweenCacheSize(asset),32);
});
test('guest walks retain absolute time and full articulation across consecutive native loops',()=>{
 const m=read('fighters','9-bit'),c=m.clips.walk,a=compileFightClip(c,fake(c),m,'walk'),duration=a.timeline.duration,schema={roster:['6-bit','9-bit'],clipIds:[['idle','walk'],['idle','walk']],matchId:1};let time=0;
 const guest=createOnlineCombatController({...schema,seat:1,now:()=>time,clipTimings:[{walk:{duration,loop:true}},{}]});assert(guest.receive({type:'start',matchId:1,seed:77}));
 const match=createMatch({mode:'local',stage:'radio-studio',start:false});match.phase='fight';const views=match.fighters.map((_,i)=>getFighterView(match,i));views[0]={...views[0],clip:'walk',elapsed:duration-20,facing:'right'};
 const snapshot=makeFightSnapshot(match,views,{...schema,seq:1,at:0});assert(snapshot);assert(guest.receive({type:'snapshot',snapshot}));
 let previous=0,first=null;for(const age of [30,duration+30,2*duration+30]){time=age;const view=guest.views()[0];assert.equal(view.elapsed,duration-20+age);assert.equal(view.nativeElapsed,view.elapsed);assert(view.elapsed>previous);previous=view.elapsed;const index=poseFrameIndex(a,view),rig=walkRig(a,view,c.frames.right[index]);assert.equal(rig.strength,1,'A later step must not repeat the initial 100ms strength ramp');if(first){assert.equal(index,first.index);assert.equal(rig.cacheKey,first.rig.cacheKey);assert.deepEqual(rig.feet,first.rig.feet);}else first={index,rig};}
});

test('essential leg articulation remains visible under reduced motion while decorative pose tweening stops',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas,m=read('fighters','9-bit'),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL(`assets/fighters/9-bit/${c.file}`,ROOT))),a=compileFightClip(c,image,m,'walk'),view={clip:'walk',facing:'right',elapsed:150},frame=c.frames.right[poseFrameIndex(a,view)],tr=poseTransform(a,frame),rig=walkRig(a,view,frame),options={frame,transform:tr,dx:320+tr.tx,dy:560+tr.ty,rig,canvasFactory:createCanvas},normal=createCanvas(640,600),reduced=createCanvas(640,600),native=createCanvas(640,600);
 assert(drawPoseTween(normal.getContext('2d'),a,view,options));assert.equal(samplePoseTween(a,{...view,reducedMotion:true}),null);assert(drawPoseTween(reduced.getContext('2d'),a,{...view,reducedMotion:true},options));native.getContext('2d').drawImage(image,...frame.rect,320+tr.tx,560+tr.ty,frame.rect[2]*tr.sx,frame.rect[3]*tr.sy);
 const pixels=canvas=>canvas.getContext('2d').getImageData(0,0,640,600).data;assert.deepEqual(pixels(reduced),pixels(normal),'Preference cannot alter visible leg contact');assert.notDeepEqual(pixels(reduced),pixels(native),'The raised foot remains visible');
});

test('the actual articulated walking renderer preserves upper hair exclusions and draws its added leg pose',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas,m=read('fighters','dj-floppydisc'),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL(`assets/fighters/dj-floppydisc/${c.file}`,ROOT))),a=compileFightClip(c,image,m,'walk'),entry=a.renderTimeline.entries.find(e=>a.renderTimeline.poses[e.pose].kind==='tween'),view={clip:'walk',facing:'right',elapsed:(entry.start+entry.end)/2,x:640,y:0,opacity:1},index=poseFrameIndex(a,view),frame=c.frames.right[index];frame.sourceExclusions=[[0,0,frame.rect[2],40]];assert.equal(walkRig(a,view,frame),null,'Native passing steps never receive an added counterphase');
 const art={manifest:m,clips:{walk:a}},metadata=combatMetadata([art])[0],fighter={id:m.id,name:m.character,height:m.height,hp:100,maxHp:100,action:'walk',actionTime:view.elapsed,_clips:metadata},match={phase:'fight',combatTime:view.elapsed,fighters:[fighter,{id:'9-bit',name:'Nine',hp:100,maxHp:100}],stagePickups:[],projectiles:[],roundRemaining:90000},canvas=createCanvas(1280,720),renderer=createFightRenderer(canvas);
 renderer.draw({match,views:[view],art:[art],presentationTimeMs:150});assert(poseTweenCacheSize(a)>0,'Upper hair exclusions cannot suppress the added lower-body pose');const drawn=canvas.getContext('2d').getImageData(400,480,480,145).data,head=canvas.getContext('2d').getImageData(480,200,320,120).data;
 renderer.draw({match,views:[{...view,frameIndex:index}],art:[art],presentationTimeMs:150});const native=canvas.getContext('2d').getImageData(400,480,480,145).data;let moved=0;for(let i=0;i<drawn.length;i++)if(Math.abs(drawn[i]-native[i])>6)moved++;assert(moved>100,'The added pose changes actual leg pixels');const final=canvas.getContext('2d').getImageData(480,200,320,120).data;let max=0;for(let i=0;i<head.length;i++)max=Math.max(max,Math.abs(final[i]-head[i]));assert(max<=2,'Head and existing upper exclusion permit only native resampling rounding');
});
test('reviewed idle guard playback excludes native attack-like arm outliers without shortening the loop',()=>{
 for(const [id,excluded]of [['papa-oak',[2]],['lost-marbles',[2,3]]]){const m=read('fighters',id),c=m.clips.idle,original=JSON.stringify(c),a=compileFightClip(c,fake(c),m,'idle');assert.equal(a.timeline.duration,1080);assert.equal(a.renderTimeline.poseCount,6);assert.equal(JSON.stringify(c),original);for(const facing of ['left','right'])for(let t=0;t<2160;t+=1000/60){const view={clip:'idle',facing,elapsed:t},index=poseFrameIndex(a,view),tween=samplePoseTween(a,view);assert(!excluded.includes(index),`${id}/${facing}@${t}: attack-like idle source key returned`);if(tween){assert(!excluded.includes(tween.from));assert(!excluded.includes(tween.to));}}}
});
test('walking tween lower mesh joins its rigid hip continuously through every facing transition',()=>{
 let transitions=0;for(const id of ids){const m=read('fighters',id),a=compileFightClip(m.clips.walk,fake(m.clips.walk),m,'walk');for(const facing of ['left','right'])for(const sample of a.renderTimeline.poses){if(sample.kind!=='tween')continue;const mesh=poseTweenMesh(a,{clip:'walk',facing},sample),f=mesh.frame,sites=f.attachments,hip=sites.torso[1]+(sites.legs[1]-sites.torso[1])*.52;for(const x of [sites.torso[0],sites.legs[0]]){const top=mesh.map({x,y:hip-1e-6}),bottom=mesh.map({x,y:hip+1e-6});assert(Math.hypot(bottom.x-top.x,bottom.y-top.y)<.001,id+'/'+facing+'/'+sample.from+'→'+sample.to+': rigid hip handoff must not jump');}transitions++;}}
 assert(transitions>=70);
});

test('actual Mac and Mutilator opaque leg pixels keep every visual-only walk intermediate within six world pixels',{skip:!nativeCanvas},async()=>{
 const {createCanvas,loadImage}=nativeCanvas;let poses=0,opaqueSamples=0;
 for(const id of ['mac-modem','mutilator']){const m=read('fighters',id),c=m.clips.walk,image=await loadImage(fileURLToPath(new URL('assets/fighters/'+id+'/'+(c.clarityFile??c.runtimeFile??c.file),ROOT))),a=compileFightClip(c,image,m,'walk');
 for(const facing of ['left','right'])for(const sample of a.renderTimeline.poses){if(sample.kind!=='tween')continue;const mesh=poseTweenMesh(a,{clip:'walk',facing},sample),f=mesh.frame,tr=poseTransform(a,f),crop=createCanvas(f.rect[2],f.rect[3]),cropCtx=crop.getContext('2d');cropCtx.drawImage(image,...f.rect,0,0,f.rect[2],f.rect[3]);const rgba=cropCtx.getImageData(0,0,crop.width,crop.height).data,leg=f.combatHurt.filter(b=>b[0]==='legs');let changed=0;
 for(let y=0;y<crop.height;y+=3)for(let x=0;x<crop.width;x+=3){if(rgba[(y*crop.width+x)*4+3]<128||!leg.some(b=>x>=b[1]&&x<b[3]&&y>=b[2]&&y<b[4]))continue;const p=tr.point([x,y]),q=mesh.map([x,y]),travel=Math.hypot(q.x-p.x,q.y-p.y);assert(travel<=6.000001,id+'/'+facing+'/'+sample.from+'→'+sample.to+': visible source leg exceeds the walking interpolation tolerance');if(travel>.01)changed++;opaqueSamples++;}
 assert(changed>10,'The bounded inserted pose must still move real opaque leg pixels');
 const before=createCanvas(640,600),after=createCanvas(640,600),options={frame:f,transform:tr,dx:320+tr.tx,dy:560+tr.ty,canvasFactory:createCanvas};before.getContext('2d').drawImage(image,...f.rect,options.dx,options.dy,f.rect[2]*tr.sx,f.rect[3]*tr.sy);assert(drawPoseMesh(after.getContext('2d'),a,f,mesh.map,{x:320,y:560,canvasFactory:createCanvas}));assert.notDeepEqual(after.getContext('2d').getImageData(0,0,640,600).data,before.getContext('2d').getImageData(0,0,640,600).data,'A real raster pose remains distinct');poses++;
 }}
 assert(poses>=8);assert(opaqueSamples>10000);
});
