import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';
import {poseFrameIndex,poseScale,resolvePoseAttachments} from '../public/games/system-clash/play/fight-attachments.mjs';
import {createMatch,performAction,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import {registerNewDeletionViews} from '../public/games/system-clash/play/new-deletion-renderer.mjs';
import {deletionDefinition} from '../public/games/system-clash/play/deletion-library.mjs';
import {makeFightSnapshot,applyFightSnapshot} from '../public/games/system-clash/play/fight-network-state.mjs';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url));
function size(file){const bytes=Buffer.alloc(64),fd=fs.openSync(file,'r');try{fs.readSync(fd,bytes,0,64,0);}finally{fs.closeSync(fd);}if(bytes[0]===137)return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};const k=bytes.toString('ascii',12,16);assert.equal(k,'VP8X');return {width:1+bytes.readUIntLE(24,3),height:1+bytes.readUIntLE(27,3)};}
function native(id){const clips={};let manifest;for(const bank of ['fighters','arcade','deletions']){const folder=path.join(root,bank,id),data=JSON.parse(fs.readFileSync(path.join(folder,'manifest.json'),'utf8'));if(bank==='fighters')manifest=data;for(const [name,clip] of Object.entries(data.clips)){const key=bank==='deletions'?'delete-'+name:name;clips[key]=compileFightClip(clip,size(path.join(folder,clip.file)),data,key);}}return {manifest,clips};}
const nativeIds=['6-bit','9-bit','ash-flowers','cache-back','cliff','dj-floppydisc','doofnoobler','dr3wbaby','kaveman-brown','lyra','mac-modem','mr-nice-guy','ms-mayhem','papa-oak','stolz','wittyf0x'];
const art=Object.fromEntries(nativeIds.map(id=>[id,native(id)]));
function point(v,a,site){const c=a.clips[v.clip],i=poseFrameIndex(c,v),f=c.data.frames[v.facing][i],o=f.offset??[0,0],raw=f.attachments?.[site],p=raw?{x:raw[0],y:raw[1]}:resolvePoseAttachments(f,v.clip,i,v.facing,a.manifest.id)[site],s=poseScale(c,f);return {x:v.x+(p.x+o[0]-f.anchor[0])*s,y:620+(v.y??0)+(p.y+o[1]-f.anchor[1])*s};}
function scene(hero,victim,facing='right'){const source=[art[hero],art[victim]],match=createMatch({mode:'practice',fighters:source.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(source)});match.fighters[0].x=facing==='right'?210:2350;match.fighters[1].x=match.fighters[0].x+(facing==='right'?1:-1)*75;assert(performAction(match,0,'deletion'));return {match,source};}
function views(match,source,t){match.deletionElapsed=t;return registerNewDeletionViews(match,match.fighters.map((_,i)=>getFighterView(match,i)),source,point);}
for(const facing of ['right','left']){
 for(const id of ['9-bit','papa-oak'])test(`native tall ${id} lowers into Doof's planted embrace before contact (${facing})`,()=>{const {match,source}=scene('doofnoobler',id,facing),b=deletionDefinition('doofnoobler').beats,v=views(match,source,b.hugContact),c=source[1].clips.crouch;assert.equal(v[1].clip,'crouch');assert.equal(poseFrameIndex(c,v[1]),poseFrameIndex(c,{clip:'crouch',elapsed:10000}));assert(Math.abs(point(v[0],source[0],'grip').x-point(v[1],source[1],'torso').x)<2);assert(Math.abs(point(v[0],source[0],'grip').y-point(v[1],source[1],'torso').y)<45);assert.equal(v[0].y,0);assert.equal(v[1].y,0);});
 test(`native short victim is visibly lifted into Oak's real bark hands, then halves settle (${facing})`,()=>{const {match,source}=scene('papa-oak','doofnoobler',facing),b=deletionDefinition('papa-oak').beats,v=views(match,source,b.gripContact);assert.equal(v[1].clip,'delete-brace');assert.equal(poseFrameIndex(source[1].clips['delete-brace'],v[1]),0);assert(v[1].y<-100,'Complete short braced body must be lifted to the hand');assert.equal(v[0].y,0);assert(Math.abs(point(v[0],source[0],'grip').x-point(v[1],source[1],'torso').x)<2);assert(Math.abs(point(v[0],source[0],'grip').y-point(v[1],source[1],'torso').y)<2);const held=views(match,source,b.rip-1)[0];assert.equal(poseFrameIndex(source[0].clips['delete-rip'],held),2,'Closed native grip remains intact until cut');const atRip=views(match,source,b.rip);assert.equal(poseFrameIndex(source[0].clips['delete-rip'],atRip[0]),3,'First native arm spread coincides with tear');const split=atRip[1];assert(split.splitBody);assert(split.splitBody.gap>=80,'The already spread native arms coincide with visible separation');assert(split.y<0);const settled=views(match,source,b.settled)[1];assert.equal(settled.y,0);assert.equal(settled.clip,'knockdown','Separated halves use the actual grounded floor pose');});
 test(`Lyra's genuine claw reaches the held victim before a native walking retreat (${facing})`,()=>{const {match,source}=scene('lyra','9-bit',facing),b=deletionDefinition('lyra').beats,v=views(match,source,b.scratch1);assert.equal(poseFrameIndex(source[0].clips['delete-claw'],v[0]),2);assert(Math.abs(point(v[0],source[0],'strike').x-point(v[1],source[1],'head').x)<2,'Claw reaches the victim rather than empty air');assert.equal(views(match,source,b.retreat+100)[0].clip,'walk');const kick=views(match,source,b.kick)[0],later=views(match,source,b.buried-1)[0];assert.equal(kick.x,later.x);assert.equal(kick.y,0);assert.equal(later.y,0);const paw=point(kick,source[0],'strike');assert(paw.x>match._deletionOrigin.target-190&&paw.x<match._deletionOrigin.target+190,'Actual rear paw reaches the tray');assert(paw.y>530&&paw.y<590,'Native paw reaches litter just above the front rim');const frame=source[0].clips['delete-litter-kick'].data.frames[kick.facing][3];assert.equal(frame.poseSource.sourceFile,'deletions-backward-bury-contact.png');const slash=views(match,source,b.scratch2);assert.equal(poseFrameIndex(source[0].clips['delete-claw'],slash[0]),3);const body=match.fighters[1]._clips[slash[1].clip].combatPoses.frames[slash[1].facing][poseFrameIndex(source[1].clips[slash[1].clip],slash[1])].hurt.find(r=>r.site==='head'),hit=point(slash[0],source[0],'strike');assert(hit.x>=slash[1].x+body.left&&hit.x<=slash[1].x+body.right,'Second actual slash reaches the native head width');});
}
test('compiled native deletion metadata retains measured hand and strike origins without pixel queries',()=>{const [hug]=combatMetadata([art.doofnoobler]);assert(hug['delete-hug'].contactGripOrigins?.right);assert(hug['delete-brace'].combatPoses.frames.right[0].sites.torso);const [claw]=combatMetadata([art.lyra]);assert(claw['delete-claw'].contactStrikeOrigins?.left);});for(const facing of ['right','left'])test(`Lyra visibly captures and lifts the short native victim into real claw reach (${facing})`,()=>{const {match,source}=scene('lyra','doofnoobler',facing),b=deletionDefinition('lyra').beats,v=views(match,source,b.scratch1);assert.equal(v[1].clip,'delete-suspended');assert(v[1].y<-100);assert.equal(v[0].y,0);assert(Math.abs(point(v[0],source[0],'strike').y-point(v[1],source[1],'torso').y)<2);assert.equal(views(match,source,b.turn)[1].y,0);assert.equal(views(match,source,b.turn)[1].clip,'delete-brace');});
function nativePose(match,source,view,index){return match.fighters[index]._clips[view.clip].combatPoses.frames[view.facing][poseFrameIndex(source[index].clips[view.clip],view)];}
function regionDistance(point,view,region){return Math.hypot(Math.max(view.x+region.left-point.x,0,point.x-view.x-region.right),Math.max(620+(view.y??0)+region.top-point.y,0,point.y-620-(view.y??0)-region.bottom));}
for(const facing of ['right','left'])for(const id of nativeIds){
 test(`Oak captures the actual ${id} torso and settles whole-source halves (${facing})`,()=>{
  const {match,source}=scene('papa-oak',id,facing),b=deletionDefinition('papa-oak').beats;
  const start=views(match,source,b.gripWindup);assert.equal(start[1].clip,'delete-brace','The native capture pose appears before lifting');assert(start[1].y===0);
  for(const t of [b.gripContact,b.rip-1]){const v=views(match,source,t);assert.equal(v[1].clip,'delete-brace');assert.equal(v[0].y,0);assert(v[1].y<0,'Lift must use the actual low braced torso, regardless of standing height');assert(Math.abs(point(v[0],source[0],'grip').x-point(v[1],source[1],'torso').x)<2);assert(Math.abs(point(v[0],source[0],'grip').y-point(v[1],source[1],'torso').y)<2,'Bark hands visibly hold the measured native torso');assert.equal(poseFrameIndex(source[0].clips['delete-rip'],v[0]),2);assert.equal(v[1].splitBody,undefined);}
  const v=views(match,source,b.settled),body=nativePose(match,source,v[1],1);assert.equal(v[1].y,0);assert.equal(v[1].clip,'knockdown');assert(v[1].splitBody?.settled);assert(Math.abs(body.bounds.bottom)<8,'Separated native floor pose stays on the existing floor anchor');
 });
 test(`Both genuine Lyra slashes intersect ${id}'s actual captured upper body (${facing})`,()=>{
  const {match,source}=scene('lyra',id,facing),b=deletionDefinition('lyra').beats;assert(views(match,source,b.boxSet)[1].y===0,'Complete body starts grounded before capture');
  for(const t of [b.scratch1,b.scratch2]){const v=views(match,source,t),paw=point(v[0],source[0],'strike'),body=nativePose(match,source,v[1],1),attack=nativePose(match,source,v[0],0);assert.equal(v[0].y,0);assert(v[1].y<=0);assert(body.bounds.top+620+v[1].y>=140,'Capture keeps the complete body beneath the HUD');assert(body.hurt.filter(r=>r.site!=='legs').some(r=>regionDistance(paw,v[1],r)<=attack.strikeRadius),'Actual claw must intersect the native head or torso rather than empty air');}
  assert.equal(views(match,source,b.turn)[1].y,0,'Captured body returns into the tray before burial');assert.equal(views(match,source,b.buried)[1].y,190,'Existing burial depth is preserved');
 });
}
test('All new finisher captures, masks and floor endings recompute identically from public guest state',()=>{
 let seq=0;
 for(const id of ['doofnoobler','lyra','papa-oak'])for(const victim of nativeIds)for(const facing of ['right','left']){
  const {match,source}=scene(id,victim,facing),b=deletionDefinition(id).beats,options={roster:nativeIds,clipIds:source.map(a=>Object.keys(a.clips)),matchId:1};match.mode='local';
  const guest=createMatch({mode:'local',fighters:source.map(a=>({id:a.manifest.id,height:a.manifest.height})),clips:combatMetadata(source)});
  for(const t of [b.contact,b.final,b.complete]){match.deletionElapsed=t;const raw=match.fighters.map((_,i)=>getFighterView(match,i)),wire=makeFightSnapshot(match,raw,{...options,seq:++seq,at:t});assert(wire,`${id}/${victim}/${facing}/${t} must be a valid public snapshot`);const remote=applyFightSnapshot(guest,wire);assert.deepEqual(registerNewDeletionViews(remote,wire.views,source,point),registerNewDeletionViews(match,raw,source,point),'Guest capture and corpse state comes from the same authoritative clock and local native landmarks');}
 }
});

const measuredSpreadHands={right:[[27,110],[391,109]],left:[[28,100],[397,89]]};
function measuredHands(v,a){const c=a.clips[v.clip],f=c.data.frames[v.facing][poseFrameIndex(c,v)],s=poseScale(c,f),o=f.offset??[0,0];return measuredSpreadHands[v.facing].map(([x,y])=>({x:v.x+(x+o[0]-f.anchor[0])*s,y:620+(v.y??0)+(y+o[1]-f.anchor[1])*s}));}
for(const facing of ['right','left'])for(const id of nativeIds)test(`Oak's two native spread fists hold ${id}'s actual mask edges, then release to the floor (${facing})`,()=>{
 const {match,source}=scene('papa-oak',id,facing),b=deletionDefinition('papa-oak').beats;assert.equal(views(match,source,b.rip-1)[1].splitPieces,undefined,'Intact body remains a single native pose before tearing');
 for(const t of [b.rip,2650,b.separated]){const v=views(match,source,t);assert.equal(poseFrameIndex(source[0].clips['delete-rip'],v[0]),3);assert.equal(v[1].splitPieces?.length,2,'Separate masked pieces must be attached to the two real native fists');const grips=measuredHands(v[0],source[0]);for(const [i,piece] of v[1].splitPieces.entries()){assert.equal(piece.halfMask,i===0?-1:1);const cut=point({...v[1],...piece},source[1],'torso');assert(Math.hypot(cut.x-grips[i].x,cut.y-grips[i].y)<2,'Each cut edge physically meets its corresponding fist');assert.equal(piece.clip,'delete-brace','The held victim remains the actual intact braced source split by masks');}}
 const released=views(match,source,b.separated)[1].splitPieces,falling=views(match,source,3200)[1].splitPieces,settled=views(match,source,b.settled)[1];
 for(const [i,piece] of falling.entries()){const start=point({...settled,...released[i]},source[1],'torso'),air=point({...settled,...piece},source[1],'torso'),end=point({...settled,...settled.splitPieces[i]},source[1],'torso');assert(air.y>start.y&&air.y<end.y,'Released whole-source half falls between native hand and native floor pose');assert.equal(piece.clip,'knockdown','The fall uses the real native whole-body knockdown frames');}
 for(const piece of settled.splitPieces){assert.equal(piece.y,0);assert.equal(piece.x,settled.x+piece.halfMask*110);assert.equal(piece.clip,'knockdown');assert.equal(poseFrameIndex(source[1].clips.knockdown,piece),poseFrameIndex(source[1].clips.knockdown,{elapsed:10000}));}
 for(let t=b.rip;t<=b.settled;t+=50)for(const piece of views(match,source,t)[1].splitPieces){const pose=nativePose(match,source,piece,1),cut=point({...settled,...piece},source[1],'torso'),left=piece.halfMask<0?piece.x+pose.bounds.left:cut.x,right=piece.halfMask<0?cut.x:piece.x+pose.bounds.right;assert(pose.bounds.bottom+piece.y<8,'Complete native half never sinks through the floor during its fall');assert(left>=0&&right<=1280,'Both complete native halves remain inside the authored ending viewport');}
 for(const t of [b.settled+200,b.present,b.complete])assert.deepEqual(views(match,source,t)[1].splitPieces,settled.splitPieces,'Corpse pieces remain stable after the attacker changes presentation pose');
});
