import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {createMenuPreviews} from '../public/games/system-clash/play/menu-preview.mjs';

test('selected fighter previews reload from the cache after teardown and restore',async()=>{const originalFetch=globalThis.fetch,originalImage=globalThis.Image;let loads=0,draws=0;const data={id:'6-bit',file:'6-bit-idle.webp',atlasSize:[20,20],canvasSize:[320,440],groundY:430,heightScale:1,scale:1,order:[0],frameMs:[180],frames:{right:[{rect:[0,0,10,10],anchor:[5,10]}],left:[{rect:[10,0,10,10],anchor:[5,10]}]}};globalThis.fetch=async()=>{loads++;return {ok:true,json:async()=>data};};globalThis.Image=class{width=20;height=20;set src(value){queueMicrotask(()=>this.onload());}};const canvases=[0,1].map(()=>({hidden:false,style:{setProperty(){}},getContext:()=>({clearRect(){},drawImage(){draws++;}})})),fallbacks=[{hidden:false},{hidden:false}];const preview=createMenuPreviews({baseURL:'https://game.test/',canvases,fallbacks});try{preview.select(0,'6-bit');await new Promise(resolve=>setImmediate(resolve));assert.equal(draws,1);preview.destroy();preview.select(0,'6-bit');await new Promise(resolve=>setImmediate(resolve));preview.tick(200);assert.equal(draws,3);assert.equal(loads,1);assert.equal(canvases[0].hidden,false);assert.equal(fallbacks[0].hidden,true);}finally{preview.destroy();globalThis.fetch=originalFetch;globalThis.Image=originalImage;}});

test('menu page suspension cancels its frame and restoration renders exactly once',()=>{const source=readFileSync(new URL('../public/games/system-clash/play/demo.mjs',import.meta.url),'utf8'),tail=source.slice(source.indexOf('function menuTick(now)'));const listeners=new Map(),frames=new Map();let id=0,rendered=0,previewTicks=0,destroyed=0;const env={menuRAF:null,menuSuspended:false,windowActive:true,window:{addEventListener:(type,fn)=>listeners.set(type,fn)},document:{hidden:false,hasFocus:()=>true,addEventListener(){}},gamepads:{reset(){}},audio:{clear(){},setPaused(){}},previews:{tick(){previewTicks++;},destroy(){destroyed++;}},pollMenuGamepads(){},render(){rendered++;},settings(){},load(){},requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:frame=>frames.delete(frame)};vm.runInNewContext(tail,env);assert.equal(frames.size,1);listeners.get('pagehide')({persisted:true});assert.equal(frames.size,0);assert.equal(destroyed,1);assert.equal(typeof listeners.get('pageshow'),'function');listeners.get('pageshow')({persisted:true});listeners.get('pageshow')({persisted:true});assert.equal(rendered,1);assert.equal(frames.size,1);const [frame,callback]=frames.entries().next().value;frames.delete(frame);callback(200);assert.equal(previewTicks,1);assert.equal(frames.size,1);listeners.get('pagehide')({persisted:false});assert.equal(frames.size,0);});
