import test from 'node:test';import assert from 'node:assert/strict';
import {cleaverPiecePlan,cleaverPieceMotion} from '../public/games/system-clash/play/cleaver-native-pieces.mjs';
import {nativeCleaverPose,NEW_DELETIONS} from '../public/games/system-clash/play/new-deletion-library.mjs';
const frame={rect:[10,20,140,240],anchor:[70,240],opaqueBounds:[4,4,136,240],offset:[0,0]};
for(const direction of[-1,1])test('Every native source pixel survives four progressive cleaver cuts '+direction,()=>{const contacts=[{at:1150,site:'head',contact:{x:650,y:-205}},{at:1750,site:'torso',contact:{x:642,y:-135}},{at:2350,site:'legs',contact:{x:645,y:-48}},{at:3300,site:'torso',contact:{x:644,y:-125}}],pieces=cleaverPiecePlan(frame,{contacts,scale:1,originX:640,originY:620,direction});assert.equal(pieces.length,6);for(let y=0;y<240;y++)for(let x=0;x<140;x++)assert.equal(pieces.filter(p=>x>=p.rect[0]&&x<p.rect[0]+p.rect[2]&&y>=p.rect[1]&&y<p.rect[1]+p.rect[3]).length,1,'Source partition neither loses nor duplicates native pixels');for(const p of pieces){assert(contacts.some(c=>c.at===p.at));const before=cleaverPieceMotion(p,p.at-1),at=cleaverPieceMotion(p,p.at),after=cleaverPieceMotion(p,p.at+80);assert.deepEqual(before,at,'Piece is continuous at actual blade contact');assert.equal(at.rotation,0);assert(Math.hypot(after.x-at.x,after.y-at.y)>0);assert.equal(cleaverPieceMotion(p,6500).settled,true);}for(const c of contacts){assert(pieces.some(p=>p.at===c.at));if(c.at<3300)assert(pieces.some(p=>p.at>c.at),'Native body remains until later real cuts');}});
test('All four cleaver contacts have an existing whole native windup',()=>{const b=NEW_DELETIONS.mutilator.beats,contacts=[b.highCut,b.torsoCut,b.lowCut,b.finalCut].map((at,i)=>({at,elapsed:i*600,frameIndex:i})),match={winner:0,fighters:[{_clips:{'delete-cleaver-windup':{}}}],_deletionOrigin:{cleaverContacts:contacts}};for(const c of contacts){assert.equal(nativeCleaverPose(match,c.at-120).clip,'delete-cleaver-windup');assert.equal(nativeCleaverPose(match,c.at).clip,'delete-cleaver');assert.equal(nativeCleaverPose(match,c.at).frameIndex,c.frameIndex);}});
import {readFileSync} from 'node:fs';import sharp from 'sharp';
import {compileFightClip,combatMetadata} from '../public/games/system-clash/play/fight-assets.mjs';import {nativeCleaverContacts} from '../public/games/system-clash/play/new-deletion-library.mjs';import {poseScale,poseFrameIndex} from '../public/games/system-clash/play/fight-attachments.mjs';
const root=new URL('../public/games/system-clash/play/',import.meta.url),roster=JSON.parse(readFileSync(new URL('assets/fight-roster.json',root))).fighters,native={};
for(const entry of roster){const id=entry.id,clips={};let manifest;for(const bank of['fighters','arcade','deletions']){const m=JSON.parse(readFileSync(new URL(`assets/${bank}/${id}/manifest.json`,root)));if(bank==='fighters')manifest=m;for(const[name,data]of Object.entries(m.clips)){const key=bank==='deletions'?'delete-'+name:name;clips[key]=compileFightClip(data,{width:data.sourceSize?.[0]??10000,height:data.sourceSize?.[1]??10000},m,key);}}native[id]={art:{manifest,clips},metadata:combatMetadata([{manifest,clips}])[0]};}
for(const direction of[-1,1])for(const entry of roster)test(`Progressive native source pieces preserve body pixels and later real blade contacts ${entry.id} ${direction}`,async()=>{const hero=native.mutilator,v=native[entry.id],facing=direction>0?'right':'left',victimFacing=direction>0?'left':'right',match={winner:0,fighters:[{id:'mutilator',_clips:hero.metadata},{id:entry.id,_clips:v.metadata}],_deletionOrigin:{winner:400,originalVictim:640,target:640,direction,victimFacing}},contacts=nativeCleaverContacts(match),pose=contacts[0].victimPose,asset=v.art.clips[pose.clip],frame=asset.data.frames[victimFacing][poseFrameIndex(asset,{...pose,facing:victimFacing})],scale=poseScale(asset,frame),offset=frame.offset??[0,0],bank=pose.clip.startsWith('delete-')?'deletions':'fighters',source=new URL(`assets/${bank}/${entry.id}/${asset.data.runtimeFile??asset.data.file}`,root),[left,top,width,height]=frame.rect,raw=await sharp(readFileSync(source)).extract({left,top,width,height}).ensureAlpha().raw().toBuffer();const mask={width,height,alpha:Uint8Array.from({length:width*height},(_,i)=>raw[i*4+3])},parts=cleaverPiecePlan(frame,{contacts,scale,originX:640,direction,mask});assert.equal(parts.reduce((sum,p)=>sum+p.rect[2]*p.rect[3],0),width*height);for(let i=0;i<parts.length;i++)for(let j=i+1;j<parts.length;j++){const a=parts[i].rect,b=parts[j].rect;assert(Math.min(a[0]+a[2],b[0]+b[2])<=Math.max(a[0],b[0])||Math.min(a[1]+a[3],b[1]+b[3])<=Math.max(a[1],b[1]));}for(const p of parts){const motion=cleaverPieceMotion(p,6500),[x,y,w,h]=p.rect,cs=Math.cos(motion.rotation),sn=Math.sin(motion.rotation);let lowest=-Infinity;for(let sy=y;sy<y+h;sy++)for(let sx=x;sx<x+w;sx++)if(raw[(sy*width+sx)*4+3]>=48)lowest=Math.max(lowest,motion.y+((sx+.5-x-w/2)*sn+(sy+.5-y-h/2)*cs)*scale);if(Number.isFinite(lowest))assert(620-lowest>=-5&&620-lowest<=5,`Settled own opaque source piece stays within5px of floor, actual gap ${620-lowest}`);}for(const c of contacts){const blade=hero.metadata['delete-cleaver'].combatPoses.frames[facing][c.frameIndex],a={x:(c.winnerX+blade.strikeStart.x-640)/scale+frame.anchor[0]-offset[0],y:blade.strikeStart.y/scale+frame.anchor[1]-offset[1]},z={x:(c.winnerX+blade.strike.x-640)/scale+frame.anchor[0]-offset[0],y:blade.strike.y/scale+frame.anchor[1]-offset[1]},count=Math.ceil(Math.hypot(z.x-a.x,z.y-a.y)*4);let hits=0;for(let i=0;i<=count;i++){const x=a.x+(z.x-a.x)*i/count,y=a.y+(z.y-a.y)*i/count,ix=Math.floor(x),iy=Math.floor(y);if(ix<0||iy<0||ix>=width||iy>=height||raw[(iy*width+ix)*4+3]<128)continue;if(parts.some(p=>p.at>=c.at&&x>=p.rect[0]&&x<p.rect[0]+p.rect[2]&&y>=p.rect[1]&&y<p.rect[1]+p.rect[3]))hits++;}assert(hits>0,`Actual metal at cut${c.at} must meet an original opaque body pixel that has not already flown away`);}});
