import test from 'node:test';
import assert from 'node:assert/strict';
import Module,{createRequire} from 'node:module';
import fs from 'node:fs';
import ts from 'typescript';
const require=createRequire(import.meta.url);
Module._extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const source=new URL('../src/lib/system-clash-tournament.ts',import.meta.url);
if(!fs.existsSync(source))test('live tournament domain exists independently of the local CPU climb',()=>assert.ok(fs.existsSync(source),'Missing authoritative live tournament domain'));
else {
const {createSystemClashTournaments,TOURNAMENT_FIGHTERS,TOURNAMENT_TTL}=require(source.pathname.replace(/^\/([A-Za-z]:)/,'$1'));
function fixture(){let time=1000,id=0,code=0,request=0;const rows=new Map(),claims=new Map(),evidence=new Map();
 const store={async read(c){return rows.get(c)??null;},async list(){return [...rows.values()];},async cas(c,old,next,now,binding){if((rows.get(c)??null)!==old)return false;if(binding){const key=binding.roomCode+':'+binding.createdAt+':'+binding.matchId,owner=c+':'+binding.boutId;if(claims.has(key)&&claims.get(key)!==owner)return false;claims.set(key,owner);}rows.set(c,next);return true;}};
 const domain=createSystemClashTournaments({store,now:()=>time,id:()=>('entry-'+ ++id),code:()=>('LIVE'+ ++code).padEnd(6,'A'),reserveMatch:async value=>{evidence.get(value.code).tournament={code:value.eventCode,boutId:value.boutId,rules:value.rules};},bindMatch:async value=>{evidence.get(value.code).tournament={code:value.eventCode,boutId:value.boutId,rules:value.rules};},readRoom:async value=>{const found=evidence.get(value.code);if(!found)throw Object.assign(new Error('Room unavailable'),{status:404});return found;},readMatch:async value=>{const found=evidence.get(value.code);if(!found||found.matchId!==value.matchId||value.requireResult&&!found.result)throw Object.assign(new Error('Match unavailable'),{status:409});return {...found,hostFighter:found.hostFighter??[...rows.values()].flatMap(raw=>JSON.parse(raw).entrants).find(e=>e.memberId===found.hostMemberId)?.fighter,guestFighter:found.guestFighter??[...rows.values()].flatMap(raw=>JSON.parse(raw).entrants).find(e=>e.memberId===found.guestMemberId)?.fighter};}});
 const actor=n=>({id:'member-'+n,name:'Player '+n,sessionExpiresAt:100000000}),host=actor('host');
 const command=(who,body)=>domain.command(who,{requestId:'00000000-0000-4000-8000-'+String(++request).padStart(12,'0'),...body});
 const create=(settings={})=>command(host,{action:'create',title:'Live Clash',settings:{maxPlayers:16,strikes:1,time:60,rounds:1,preset:'custom',...settings}});
 return {domain,rows,claims,evidence,actor,host,command,create,setTime:n=>time=n};
}
async function entered(f,count,strikes=1){let event=await f.create({maxPlayers:count,strikes});const actors=[];
 for(let i=0;i<count;i++){const actor=f.actor(i);actors.push(actor);event=await f.command(actor,{action:'join',code:event.code,fighter:TOURNAMENT_FIGHTERS[i]});const entry=event.entrants.find(e=>e.id===event.selfEntrantId);await f.command(f.host,{action:'approve',code:event.code,entrantId:entry.id});await f.command(actor,{action:'ready',code:event.code,ready:true});}
 event=await f.command(f.host,{action:'start',code:event.code});return {event,actors};
}
test('presence polls batch writes without changing revision or expiry and heartbeats do not consume command receipts',async()=>{const f=fixture(),event=await f.create(),actor=f.actor(1);const joined=await f.command(actor,{action:'join',code:event.code,fighter:'6-bit'}),raw=f.rows.get(event.code),revision=joined.revision,expiry=joined.expiresAt;for(let n=1;n<=10;n++){f.setTime(1000+n*2500);await f.domain.view(event.code,actor);}assert.equal(f.rows.get(event.code),raw);f.setTime(31000);const reconnect=await f.domain.view(event.code,actor);assert.equal(reconnect.revision,revision);assert.equal(reconnect.expiresAt,expiry);assert.equal(reconnect.entrants[0].connected,true);const receipts=JSON.parse(f.rows.get(event.code)).receipts.length;f.setTime(121001);const stale=await f.domain.view(event.code,f.actor('spectator'));assert.equal(stale.entrants[0].connected,false);const alive=await f.command(actor,{action:'ping',code:event.code});assert.equal(alive.entrants[0].connected,true);assert.equal(alive.revision,revision);assert.equal(JSON.parse(f.rows.get(event.code)).receipts.length,receipts);});
test('capacity is sixteen, only seventeen ordinary fighters are eligible, and unsafe settings fail',async()=>{const f=fixture();assert.equal(TOURNAMENT_FIGHTERS.length,17);assert.ok(!TOURNAMENT_FIGHTERS.includes('bnl-01'));assert.ok(!TOURNAMENT_FIGHTERS.includes('9-bit'));for(const settings of [{maxPlayers:18},{maxPlayers:17},{strikes:6},{strikes:0},{time:120},{rounds:2}])await assert.rejects(()=>f.create(settings));const e=await f.create();await assert.rejects(()=>f.command(f.actor(1),{action:'join',code:e.code,fighter:'bnl-01'}));});
test('racing fighter reservations and capacity checks have exactly one winner',async()=>{const f=fixture(),e=await f.create({maxPlayers:2});const results=await Promise.allSettled([f.command(f.actor(1),{action:'join',code:e.code,fighter:'6-bit'}),f.command(f.actor(2),{action:'join',code:e.code,fighter:'6-bit'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);await f.command(f.actor(3),{action:'join',code:e.code,fighter:'cache-back'});await assert.rejects(()=>f.command(f.actor(4),{action:'join',code:e.code,fighter:'cliff'}));});
test('host approval, frozen settings, readiness and public projections preserve account boundaries',async()=>{const f=fixture(),e=await f.create(),actor=f.actor(1);let view=await f.command(actor,{action:'join',code:e.code,fighter:'6-bit'});await assert.rejects(()=>f.command(actor,{action:'approve',code:e.code,entrantId:view.selfEntrantId}),x=>x.status===403);assert.equal(view.entrants[0].status,'pending');assert.ok(!JSON.stringify(view).includes('member-'));assert.ok(!JSON.stringify(await f.domain.list(actor)).includes('member-'));await assert.rejects(()=>f.command(f.host,{action:'start',code:e.code}));});
test('exact command retry is idempotent and changed body nonce reuse conflicts',async()=>{const f=fixture(),e=await f.create(),actor=f.actor(1),body={action:'join',code:e.code,fighter:'6-bit',requestId:'12345678-1234-4123-8123-123456789012'};const a=await f.domain.command(actor,body),b=await f.domain.command(actor,body);assert.equal(a.revision,b.revision);assert.equal(a.selfEntrantId,b.selfEntrantId);await assert.rejects(()=>f.domain.command(actor,{...body,fighter:'cliff'}),x=>x.status===409);});
for(let count=2;count<=16;count++)for(let strikes=1;strikes<=5;strikes++)test('serial elimination terminates: '+count+' entrants / '+strikes+' strikes',async()=>{const f=fixture();let {event}=await entered(f,count,strikes);let completed=0,lastRound=0;
 while(event.status!=='complete'){event=await f.command(f.host,{action:'next',code:event.code});const active=event.bouts.filter(b=>['ready','live','decision'].includes(b.status));assert.equal(active.length,1);const bout=active[0];assert.ok(bout);assert.ok(bout.round>=lastRound);lastRound=bout.round;event=await f.command(f.host,{action:'adjudicate',code:event.code,boutId:bout.id,winnerEntrantId:bout.p1,reason:'Reviewed forfeit during bounded domain fixture'});completed++;assert.ok(completed<=count*strikes-1);}
 assert.equal(event.entrants.filter(p=>p.status==='active').length,1);assert.ok(event.championId);assert.ok(completed>=strikes*(count-1));assert.equal(event.currentBoutId,null);
});
test('byes never count as wins or strikes and rotate among the surviving odd roster',async()=>{const f=fixture();let {event}=await entered(f,5,5);const first=event.entrants.find(e=>e.byeCount===1);assert.ok(first);assert.equal(first.losses,0);for(let i=0;i<2;i++){event=await f.command(f.host,{action:'next',code:event.code});const bout=event.bouts.find(b=>b.id===event.currentBoutId);event=await f.command(f.host,{action:'adjudicate',code:event.code,boutId:bout.id,winnerEntrantId:bout.p1,reason:'Reviewed referee decision'});}event=await f.command(f.host,{action:'next',code:event.code});const old=event.entrants.find(e=>e.id===first.id);assert.equal(old.byeCount,1);assert.equal(event.entrants.filter(e=>e.byeCount===1).length,2);});
test('only committed assigned room evidence advances once; forged winners and foreign seats are rejected',async()=>{const f=fixture();let {event,actors}=await entered(f,2,2);event=await f.command(f.host,{action:'next',code:event.code});const bout=event.bouts.find(b=>b.id===event.currentBoutId),p1=actors.find(a=>event.entrants.find(e=>e.id===bout.p1).name===a.name),p2=actors.find(a=>event.entrants.find(e=>e.id===bout.p2).name===a.name);for(const actor of [p1,p2])await f.command(actor,{action:'ready',code:event.code,ready:true});
 const room={code:'ROOMAA',createdAt:1000,matchId:1,matchPhase:'match',hostMemberId:p1.id,guestMemberId:p2.id,result:null};f.evidence.set(room.code,room);await assert.rejects(()=>f.command(p2,{action:'bind',code:event.code,boutId:bout.id,roomCode:room.code,roomMatchId:1}),x=>x.status===403);
 event=await f.command(p1,{action:'bind',code:event.code,boutId:bout.id,roomCode:room.code,roomMatchId:1});await assert.rejects(()=>f.command(p1,{action:'advance',code:event.code,boutId:bout.id,winner:1}));await assert.rejects(()=>f.command(p1,{action:'advance',code:event.code,boutId:bout.id}));
 room.result={matchId:1,winner:1};room.matchPhase='over';const advanced=await f.command(p1,{action:'advance',code:event.code,boutId:bout.id});const retried=await f.command(f.host,{action:'advance',code:event.code,boutId:bout.id});assert.equal(retried.entrants.find(e=>e.id===bout.p1).losses,1);assert.equal(advanced.revision,retried.revision);assert.equal(advanced.bouts.find(b=>b.id===bout.id).winner,bout.p2);assert.ok(!JSON.stringify(advanced).includes(p1.id));
});
test('draws stop for a host decision; one replay is bounded and old transport cannot be rebound',async()=>{const f=fixture();let {event,actors}=await entered(f,2);event=await f.command(f.host,{action:'next',code:event.code});const bout=event.bouts.find(b=>b.id===event.currentBoutId),p1=actors.find(a=>a.name===event.entrants.find(e=>e.id===bout.p1).name),p2=actors.find(a=>a.name===event.entrants.find(e=>e.id===bout.p2).name);for(const a of [p1,p2])await f.command(a,{action:'ready',code:event.code,ready:true});const room={code:'DRAWAA',createdAt:1000,matchId:1,matchPhase:'match',hostMemberId:p1.id,guestMemberId:p2.id,result:null};f.evidence.set(room.code,room);await f.command(p1,{action:'bind',code:event.code,boutId:bout.id,roomCode:room.code,roomMatchId:1});room.result={matchId:1,winner:null};room.matchPhase='over';event=await f.command(p1,{action:'advance',code:event.code,boutId:bout.id});assert.equal(event.bouts.find(b=>b.id===bout.id).status,'decision');assert.ok(event.entrants.every(e=>e.losses===0));await assert.rejects(()=>f.command(f.host,{action:'next',code:event.code}));await f.command(f.host,{action:'replay',code:event.code,boutId:bout.id});await assert.rejects(()=>f.command(p1,{action:'bind',code:event.code,boutId:bout.id,roomCode:room.code,roomMatchId:1}));});
test('withdrawal, pause and fixed long event expiry preserve event history and halt competing starts',async()=>{const f=fixture();let {event,actors}=await entered(f,3,3);const expiry=event.expiresAt;event=await f.command(f.host,{action:'pause',code:event.code});await assert.rejects(()=>f.command(f.host,{action:'next',code:event.code}));event=await f.command(f.host,{action:'resume',code:event.code});event=await f.command(actors[0],{action:'withdraw',code:event.code});assert.equal(event.entrants.find(e=>e.name===actors[0].name).status,'withdrawn');assert.equal(event.expiresAt,expiry);f.setTime(1000+TOURNAMENT_TTL);await assert.rejects(()=>f.domain.view(event.code,f.host),x=>x.status===410);});

test('an assigned P1 offers one recoverable room before the guest joins and outsiders cannot replace it',async()=>{const f=fixture();let {event,actors}=await entered(f,2,2);event=await f.command(f.host,{action:'next',code:event.code});const bout=event.bouts.find(b=>b.id===event.currentBoutId),p1=actors.find(a=>a.name===event.entrants.find(e=>e.id===bout.p1).name),p2=actors.find(a=>a.name===event.entrants.find(e=>e.id===bout.p2).name);f.evidence.set('OFFERA',{code:'OFFERA',createdAt:1000,matchId:0,matchPhase:'selection',hostMemberId:p1.id,guestMemberId:null,result:null});event=await f.command(p1,{action:'offer',code:event.code,boutId:bout.id,roomCode:'OFFERA'});assert.equal(event.currentBout.roomCode,'OFFERA');await assert.rejects(()=>f.command(p2,{action:'offer',code:event.code,boutId:bout.id,roomCode:'OFFERA'}),x=>x.status===403);f.evidence.set('OFFERB',{code:'OFFERB',createdAt:1001,matchId:0,matchPhase:'selection',hostMemberId:p1.id,guestMemberId:null,result:null});await assert.rejects(()=>f.command(p1,{action:'offer',code:event.code,boutId:bout.id,roomCode:'OFFERB'}),x=>x.status===409);});
test('a foreign-account room and an incorrect reserved fighter cannot bind the called match',async()=>{const f=fixture();let {event,actors}=await entered(f,2,2);event=await f.command(f.host,{action:'next',code:event.code});const bout=event.bouts.find(b=>b.id===event.currentBoutId),p1=actors.find(a=>a.name===event.entrants.find(e=>e.id===bout.p1).name),p2=actors.find(a=>a.name===event.entrants.find(e=>e.id===bout.p2).name);for(const a of[p1,p2])await f.command(a,{action:'ready',code:event.code,ready:true});f.evidence.set('FOREIA',{code:'FOREIA',createdAt:1000,matchId:1,matchPhase:'match',hostMemberId:p1.id,guestMemberId:'wrong-account',hostFighter:TOURNAMENT_FIGHTERS[0],guestFighter:TOURNAMENT_FIGHTERS[1],result:null});await assert.rejects(()=>f.command(p1,{action:'bind',code:event.code,boutId:bout.id,roomCode:'FOREIA',roomMatchId:1}),x=>x.status===409);f.evidence.set('FOREIA',{...f.evidence.get('FOREIA'),guestMemberId:p2.id,hostFighter:'bnl-01'});await assert.rejects(()=>f.command(p1,{action:'bind',code:event.code,boutId:bout.id,roomCode:'FOREIA',roomMatchId:1}),x=>x.status===409);});
test('new round pairing avoids immediately repeating a full even-field first round',async()=>{const f=fixture();let {event}=await entered(f,4,5);const pairs=event.bouts.map(b=>[b.p1,b.p2].sort().join('|'));for(let n=0;n<2;n++){event=await f.command(f.host,{action:'next',code:event.code});const bout=event.bouts.find(b=>b.id===event.currentBoutId);event=await f.command(f.host,{action:'adjudicate',code:event.code,boutId:bout.id,winnerEntrantId:bout.p1,reason:'Reviewed referee decision'});}event=await f.command(f.host,{action:'next',code:event.code});assert.ok(event.bouts.filter(b=>b.round===2).every(b=>!pairs.includes([b.p1,b.p2].sort().join('|'))));});

}

