import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';import {join} from 'node:path';import sharp from 'sharp';
const root=fileURLToPath(new URL('../public/games/system-clash/play/assets/',import.meta.url));
const read=(bank)=>JSON.parse(fs.readFileSync(path.join(root,bank,'papa-oak/manifest.json'),'utf8'));
const index=clip=>{let ms=0;for(let i=0;i<clip.order.length;i++){if(ms>=clip.contactMs)return clip.order[i];ms+=clip.frameMs[i];}return clip.order.at(-1);};
const hangingExpected={"scale":0.46,"region":[480,672,1024,1536],"sourceSha256":"0d294672aeba9df840ebb6f04375c22268e9f8085cfd03078c252c1c2ba79978","originalBytes":2599121,"rgbaSha256":"aff7c2c601684e82c0bc80b6dd00d402f735083497a1684460a3e525fb46eddd","regionRgbaSha256":"403727c5aa410122c0ff729418f7eef4dc9564070ea1a947ac75986526630d30"};
const hangingHash=bytes=>createHash('sha256').update(bytes).digest('hex');
async function assertHangingSource(clip,dir){
 const source=clip.frontPoseSource,expected=hangingExpected;assert.equal(clip.poseRole,'airborne');assert.equal(clip.scale,expected.scale);assert.deepEqual(clip.order,[0]);assert.deepEqual(clip.frames.left,clip.frames.right);assert.equal(clip.frames.right.length,1);
 assert.equal(source.sourceKind,'approved-four-character-airborne-sheet');assert.equal(source.originalFile,'lift-four-airborne-approved-sheet-4-v1.png');assert.equal(source.originalBytes,expected.originalBytes);assert.deepEqual(source.originalSize,[1024,1536]);assert.equal(source.originalSha256,expected.sourceSha256);assert.deepEqual(source.sourceRegion,expected.region);assert.equal(source.nativeAnatomy.resultScale,expected.scale);assert.match(source.nativeAnatomy.method,/skull, chest and limb widths/);
 const bytes=readFileSync(join(dir,clip.file));assert.equal(hangingHash(bytes),clip.sourceSha256);const image=sharp(bytes),metadata=await image.metadata();assert.deepEqual(clip.sourceSize,[metadata.width,metadata.height]);const rgba=await image.ensureAlpha().raw().toBuffer();assert.equal(hangingHash(rgba),expected.rgbaSha256);assert.equal(hangingHash(rgba),source.nativeRgbaSha256);
 const [left,top,right,bottom]=source.sourceRegion,crop=source.crop;const region=await sharp(rgba,{raw:{width:metadata.width,height:metadata.height,channels:4}}).extract({left:-crop[0],top:-crop[1],width:right-left,height:bottom-top}).raw().toBuffer();assert.equal(hangingHash(region),expected.regionRgbaSha256);assert.equal(hangingHash(region),source.regionRgbaSha256);
 for(const facing of ['right','left'])for(const frame of clip.frames[facing]){assert.equal(frame.nativeFacing,'front');assert.equal(frame.bodyCalibration,1);assert.deepEqual(frame.rect,[0,0,metadata.width,metadata.height]);assert.equal(frame.anchor[0],metadata.width/2);assert.deepEqual(frame.attachments.ripCut,frame.attachments.torso);assert.equal(frame.attachments.ripCut[0],metadata.width/2);assert.equal(frame.poseSource,undefined,'Sheet-derived complete pose retains clip frontPoseSource rather than invented legacy native-atlas provenance');for(const point of Object.values(frame.attachments))assert(point.every(Number.isFinite)&&point[0]>=0&&point[1]>=0&&point[0]<=frame.rect[2]&&point[1]<=frame.rect[3]);}
}

test('Papa retains30 native clips at385, genuine punch chronology and one approved hanging source',async()=>{
 let count=0,hanging=0;for(const bank of ['fighters','arcade','deletions']){const manifest=read(bank);assert.equal(manifest.height,385);assert.equal(manifest.scale,1);for(const [name,clip] of Object.entries(manifest.clips)){assert(fs.statSync(path.join(root,bank,'papa-oak',clip.file)).size>100);if(name==='rip-front'){assert.equal(bank,'deletions');await assertHangingSource(clip,path.join(root,bank,'papa-oak'));hanging++;continue;}count++;for(const facing of ['right','left'])for(const frame of clip.frames[facing]){assert(frame.poseSource.sourceFile.endsWith('-source.png'));assert(!frame.poseSource.sourceFile.includes('6-bit'));assert(frame.anchor[1]>=frame.opaqueBounds[3]-2);for(const point of Object.values(frame.attachments))assert(point[0]>=0&&point[1]>=0&&point[0]<=frame.rect[2]&&point[1]<=frame.rect[3]);}}}
 assert.equal(count,30);assert.equal(hanging,1);const punch=read('fighters').clips.punch;assert.equal(index(punch),4);assert.equal(punch.contactMs,170);assert.equal(punch.activeEndMs,280);for(const facing of ['right','left']){assert.equal(punch.frames[facing].length,8);assert.equal(new Set(punch.frames[facing].map(f=>f.canonicalPixelSha256)).size,8);}
});
test('Papa knockdown/getup share the exact same floor pose and encoded atlas',()=>{const {knockdown,getup}=read('fighters').clips;assert.equal(knockdown.file,getup.file);for(const facing of ['right','left'])assert.deepEqual(knockdown.frames[facing].at(-1),getup.frames[facing][0]);});
test('Every Papa kick keeps the actual hand grip distinct from its toe strike for held weapons',()=>{const clips={...read('fighters').clips,...read('arcade').clips};for(const name of ['kick','low-kick','crouch-kick','jump-kick','crouch-high-kick','power-kick']){const clip=clips[name];for(const facing of ['right','left']){const {grip,strike}=clip.frames[facing][index(clip)].attachments;assert(Math.hypot(grip[0]-strike[0],grip[1]-strike[1])>60,name+': weapon must stay on a hand, separate from the striking foot');}}});
test('Lyra real litter prop has4 distinct native states, floor anchors and authored foreground rim',()=>{const dir=path.join(root,'deletions/litter-protocol'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'atlas.json'),'utf8'));assert.equal(manifest.drawWidth,460);assert(fs.statSync(path.join(dir,manifest.file)).size>100);assert.deepEqual(Object.keys(manifest.frames),['open','captured','impact','dead']);assert.equal(new Set(Object.values(manifest.frames).map(f=>f.canonicalPixelSha256)).size,4);for(const f of Object.values(manifest.frames)){assert(f.anchor[1]<=f.rect[3]);assert(f.rimY>0&&f.rimY<f.anchor[1]);assert(f.opaqueBounds[3]-f.anchor[1]<=3);}});
