import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createMatch,advanceMatch,getFighterView} from '../public/games/system-clash/play/fight-engine.mjs';
import * as protocol from '../public/games/system-clash/play/online-protocol.mjs';
import * as network from '../public/games/system-clash/play/fight-network-state.mjs';
const file=new URL('../public/games/system-clash/play/fight-online-rounds.mjs',import.meta.url);
if(!fs.existsSync(file))test('online round sets have an authoritative progression owner',()=>assert.ok(fs.existsSync(file),'Missing online round progression'));
else {
const {createOnlineRoundProgression}=await import(file.href);
test('trusted wire rules are strict and one coordinated kickoff carries both round/time values',()=>{for(const rules of [{rounds:3,time:60},{rounds:5,time:0},{rounds:1,time:99}]){assert.ok(protocol.validOnlineMatchRules(rules));const starts=[],coordinator=protocol.createFrameCoordinator({rules,onStart:p=>starts.push(p)});coordinator.loaded('local');coordinator.loaded('remote');assert.deepEqual(starts[0].rules,rules);assert.ok(protocol.validPayload(starts[0]));}for(const rules of [{rounds:2,time:60},{rounds:3,time:120},{rounds:'3',time:60},{rounds:3,time:60,admin:true}]){assert.equal(protocol.validOnlineMatchRules(rules),false);assert.equal(protocol.validPayload({type:'setup',rules}),false);assert.equal(protocol.validPayload({type:'start',matchId:1,seed:7,rules}),false);}});
for(const rounds of[1,3,5])test('best-of '+rounds+' commits only a set winner after the required wins',()=>{const run=createOnlineRoundProgression({rules:{rounds,time:60},seed:77}),target=(rounds+1)/2;let match=createMatch({mode:'local',roundTimeMs:60000}),round=1;
 for(let win=0;win<target;win++){match.phase='over';match.winner=0;run.observe(match);run.apply(match);assert.equal(match.setComplete,win===target-1);assert.equal(match.roundWins[0],win+1);run.observe(match);assert.equal(run.wins[0],win+1);if(win<target-1){assert.equal(run.tick(2499),null);const next=run.tick(1);assert.equal(next.round,++round);match=createMatch({mode:'local',roundNumber:next.round,roundTimeMs:60000,seed:next.seed});run.apply(match);assert.equal(match.roundRemaining,60000);assert.equal(match.setComplete,false);}}
 assert.equal(run.winner,0);assert.equal(run.tick(10000),null);
});
test('intermission freezes while paused, and a draw never awards a round or final set win',()=>{const run=createOnlineRoundProgression({rules:{rounds:3,time:99},seed:7}),m=createMatch({mode:'local'});m.phase='over';m.winner=null;run.observe(m);assert.deepEqual(run.wins,[0,0]);assert.equal(run.tick(10000,{paused:true}),null);assert.equal(run.tick(2500).round,2);});
test('ordinary single-round draw remains a final draw while repeated best-of ties stop at their bound',()=>{const one=createOnlineRoundProgression({rules:{rounds:1,time:99},seed:7}),m=createMatch({mode:'local'});m.phase='over';m.winner=null;one.observe(m);assert.equal(one.complete,true);assert.equal(one.winner,null);const many=createOnlineRoundProgression({rules:{rounds:3,time:60},seed:7});for(let round=1;round<=4;round++){many.observe(m);assert.equal(many.complete,round===4);if(round<4)assert.equal(many.tick(2500).round,round+1);}assert.equal(many.winner,null);assert.equal(many.tick(2500),null);});
test('four draws end a tied set before a decisive Deletion can ever be misreported as a draw',()=>{for(const rounds of[3,5]){const run=createOnlineRoundProgression({rules:{rounds,time:60},seed:7});for(let n=1;n<=3;n++){const draw=createMatch({mode:'local'});draw.phase='over';draw.winner=null;run.observe(draw);assert.equal(run.complete,false);run.tick(2500);}const finalDraw=createMatch({mode:'local'});finalDraw.phase='over';finalDraw.winner=null;run.observe(finalDraw);run.apply(finalDraw);assert.equal(run.complete,true);assert.equal(finalDraw.winner,null);assert.equal(finalDraw.deletionElapsed,0);assert.ok(network.makeFightSnapshot(finalDraw,finalDraw.fighters.map((_,i)=>getFighterView(finalDraw,i)),{seq:1,matchId:1,at:0,roster:['6-bit','9-bit'],clipIds:[['idle','walk'],['idle','walk']]}));}});
test('selected engine time handles60,99 and unlimited for every subsequent host round',()=>{for(const time of[0,60,99]){const run=createOnlineRoundProgression({rules:{rounds:3,time},seed:8}),first=createMatch({mode:'local',roundTimeMs:time*1000});first.phase='over';first.winner=0;run.observe(first);const next=run.tick(2500),m=createMatch({mode:'local',roundTimeMs:time*1000,roundNumber:next.round,seed:next.seed});run.apply(m);m.phase='fight';if(time){m.roundRemaining=10;advanceMatch(m,20,[{},{}]);assert.equal(m.phase,'over');}else{advanceMatch(m,100,[{},{}]);assert.equal(m.phase,'fight');assert.equal(m.roundRemaining,0);}assert.equal(m.roundNumber,2);}});
function controller(seat){let time=0;const sent=[],actions=[],c=network.createOnlineCombatController({seat,matchId:1,roster:['6-bit','9-bit'],clipIds:[['idle','walk'],['idle','walk']],send:p=>{sent.push(p);return true;},now:()=>time,onAction:p=>actions.push(p)});c.receive({type:'start',matchId:1,seed:7});return{c,sent,actions,time:v=>time=v};}
test('only the host starts a new round; old round controls cannot carry into fresh health',()=>{const host=controller(0),guest=controller(1);assert.equal(guest.c.startRound(2),false);assert.equal(host.c.startRound(2),true);assert.deepEqual(host.c.remoteInput,{move:0,crouch:false,block:false});assert.equal(host.c.receive({type:'action',action:'punch',input:{move:1,crouch:false,block:false},inputSeq:10}),false);assert.equal(host.c.receive({type:'action',action:'punch',round:1,input:{move:1,crouch:false,block:false},inputSeq:11}),false);assert.equal(host.c.receive({type:'input',round:2,input:{move:0,crouch:false,block:false},inputSeq:12}),true);assert.equal(host.c.receive({type:'action',action:'punch',round:2,input:{move:0,crouch:false,block:false},inputSeq:13}),true);assert.equal(host.actions.length,1);assert.equal(host.c.startRound(4),false);});
test('snapshot projection carries set completion/score and guest round changes clear stale input before sending',()=>{const m=createMatch({mode:'local',start:false}),run=createOnlineRoundProgression({rules:{rounds:3,time:60},seed:7});m.phase='over';m.winner=0;run.observe(m);run.tick(2500);m.phase='countdown';run.apply(m);const snap=network.makeFightSnapshot(m,m.fighters.map((_,i)=>getFighterView(m,i)),{seq:1,matchId:1,at:0,roster:['6-bit','9-bit'],clipIds:[['idle','walk'],['idle','walk']]});assert.ok(snap);assert.equal(snap.state.setComplete,false);assert.equal(snap.state.roundNumber,2);assert.deepEqual(snap.state.roundWins,[1,0]);const guest=controller(1);assert.equal(guest.c.receive({type:'snapshot',snapshot:snap}),true);guest.c.input({move:1,crouch:false,block:false});assert.equal(guest.sent.at(-1).round,2);const invalid=structuredClone(snap);invalid.seq=2;invalid.state.setComplete='yes';assert.equal(guest.c.receive({type:'snapshot',snapshot:invalid}),false);});

test('a dropped countdown snapshot cannot interpolate a fresh round against the previous round positions',()=>{const guest=controller(1),snapshot=(round,seq,x)=>{const m=createMatch({mode:'local'});m.phase='fight';m.roundNumber=round;m.fighters[0].x=x;return network.makeFightSnapshot(m,m.fighters.map((_,i)=>getFighterView(m,i)),{seq,matchId:1,at:seq*100,roster:['6-bit','9-bit'],clipIds:[['idle','walk'],['idle','walk']]});};guest.c.receive({type:'snapshot',snapshot:snapshot(1,1,700)});guest.time(100);guest.c.receive({type:'snapshot',snapshot:snapshot(2,2,440)});assert.equal(guest.c.views(100)[0].x,440);assert.equal(guest.c.receive({type:'snapshot',snapshot:snapshot(1,3,800)}),false);});
function runtimeFunction(name,args){const source=fs.readFileSync(new URL('../public/games/system-clash/play/fight.js',import.meta.url),'utf8'),pattern=new RegExp('function '+name+'\\([^)]*\\)\\s*\\{'),match=pattern.exec(source);assert.ok(match);let start=match.index+match[0].length,depth=1,end=start;for(;depth&&end<source.length;end++){if(source[end]==='{')depth++;else if(source[end]==='}')depth--;}return new Function('env','with(env){return function('+args+'){'+source.slice(start,end-1)+'}}');}
test('the real fight reset creates every online round with the frozen timer and preserves set progress',()=>{const run=createOnlineRoundProgression({rules:{rounds:3,time:60},seed:77}),first=createMatch({mode:'local'});first.phase='over';first.winner=0;run.observe(first);const next=run.tick(2500),elements=new Map(),env={ready:true,onlineBridge:{enabled:true},onlineCombat:{started:true},onlineRounds:run,motionPresentationEpoch:0,musicMatchNumber:0,match:first,matchRules:{rounds:3,time:60},roundSet:run.set,roundNumber:2,roundMenu:{close(){},reset(){}},pauseDialog:{open:false},clearInput(){},effects:{clear(){}},paused:false,accumulator:0,inspectTime:null,motionTime:null,weaponFeedback:'',weaponFeedbackUntil:0,previousTravelViews:null,previousTravelPhase:null,syncAudioPause(){},$:id=>{if(!elements.has(id))elements.set(id,{hidden:false,setAttribute(){},value:'local'});return elements.get(id);},createMatch,launchParams:new URLSearchParams('stage=radio-studio'),metadata:undefined,art:[{manifest:{id:'6-bit',character:'6 Bit',height:300}},{manifest:{id:'9-bit',character:'9 Bit',height:300}}],demoLaunch:{enabled:true},dispatchEvents(){},draw(){}};runtimeFunction('reset','start=true,seed,{newSet=true}={}')(env)(true,next.seed,{newSet:false});assert.equal(env.match.roundRemaining,60000);assert.equal(env.match._roundNumber,2);assert.equal(env.match.roundNumber,2);assert.equal(env.match.setComplete,false);assert.deepEqual(env.match.roundWins,[1,0]);assert.equal(env.roundSet.wins[0],1);});
test('real frame kickoff takes parent rules over any previously selected URL rules before resetting',()=>{const env={matchRules:{rounds:5,time:0},onlineRounds:null,createOnlineRoundProgression,reset(active,seed){assert.equal(active,true);assert.equal(seed,77);assert.deepEqual({rounds:env.matchRules.rounds,time:env.matchRules.time},{rounds:3,time:60});},effects:{startAudio(){}},canvas:{focus(){}},onlineBridge:{seat:0},onlineCombat:{}};runtimeFunction('startOnlineFight','packet')(env)({type:'start',matchId:1,seed:77,rules:{rounds:3,time:60}});assert.equal(env.onlineRounds.set.rules.rounds,3);assert.equal(env.onlineRounds.set.rules.time,60);});

}
