import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createMatch,advanceMatch,getFighterView,performAction} from '../public/games/system-clash/play/fight-engine.mjs';
import * as net from '../public/games/system-clash/play/fight-network-state.mjs';
const roster=['6-bit','9-bit'];
const clipIds=[['idle','walk','crouch','block','punch','kick','high','low','knockdown','jump','delete-present'],['idle','walk','crouch','block','punch','kick','high','low','knockdown','jump','delete-present']];
const options={roster,clipIds,matchId:1};
const input={move:1,crouch:false,block:false};
function match(){return createMatch({mode:'local',stage:'radio-studio',start:false});}
function snapshot(value=match(),seq=1){return net.makeFightSnapshot(value,value.fighters.map((_,i)=>getFighterView(value,i)),{...options,seq,at:100});}
function controller(seat=0){let time=0;const sent=[],starts=[],pauses=[],states=[],events=[],actions=[],disconnected=[];const control=net.createOnlineCombatController({...options,seat,now:()=>time,send:p=>{sent.push(p);return true;},onStart:p=>starts.push(p),onPause:p=>pauses.push(p),onState:s=>states.push(s),onEvents:e=>events.push(...e),onAction:a=>actions.push(a),onDisconnect:r=>disconnected.push(r)});return {control,sent,starts,pauses,states,events,actions,disconnected,setTime:v=>{time=v;}};}
const start={type:'start',matchId:1,seed:77};
test('wire snapshots contain public render state without metadata, styles or credentials',()=>{const m=match();m.token='SECRET';m.fighters[0]._clips.image={};m.fighters[0]._style={...m.fighters[0]._style,secret:'PRIVATE'};const s=snapshot(m);assert.ok(s);const text=JSON.stringify(s);for(const secret of ['SECRET','PRIVATE','_clips','_style','image'])assert.ok(!text.includes(secret));assert.equal(s.state.stage.id,'radio-studio');assert.equal(s.state.fighters[0].id,'6-bit');});
test('snapshot parser rejects unknown fighter/clip, invalid health and nonfinite coordinates',()=>{const good=snapshot();assert.ok(net.readFightSnapshot(good,options));for(const change of [s=>s.state.fighters[0].id='unknown',s=>s.views[1].clip='../../image',s=>s.state.fighters[0].hp=-1,s=>s.state.fighters[0].hp=101,s=>s.views[0].x=Infinity,s=>s.state.phase='admin']){const s=structuredClone(good);change(s);assert.equal(net.readFightSnapshot(s,options),null);}});
test('snapshot limits reject oversized state and projectile spam',()=>{const s=snapshot();s.state.projectiles=Array.from({length:9},()=>({x:0,y:0}));assert.equal(net.readFightSnapshot(s,options),null);const large=snapshot();large.views[0].data='x'.repeat(70000);assert.equal(net.readFightSnapshot(large,options),null);});
test('guest consumes only newer current-match snapshots and cannot publish authority',()=>{const h=controller(1);h.control.receive(start);h.control.receive({type:'snapshot',snapshot:snapshot(match(),2)});h.control.receive({type:'snapshot',snapshot:snapshot(match(),1)});const old=snapshot(match(),3);old.matchId=2;h.control.receive({type:'snapshot',snapshot:old});assert.equal(h.states.length,1);assert.equal(h.control.publish(match(),[]),false);assert.equal(h.control.publishEvents([{type:'hit'}]),false);});
test('guest input is seat mapped and bounded to ten sends per second',()=>{const h=controller(1);h.control.receive(start);for(let i=0;i<100;i++){h.setTime(i*10);h.control.input({...input,airborne:true});}assert.equal(h.sent.filter(p=>p.type==='input').length,10);assert.deepEqual(h.sent[0].input,input);h.control.action('punch',{...input,airborne:true});assert.deepEqual(h.sent.at(-1),{type:'action',action:'punch',input});assert.equal(h.actions.length,0);});
test('host maps remote actions to fighter one and neutralizes stale remote controls',()=>{const h=controller();h.control.receive(start);h.control.receive({type:'input',input});assert.deepEqual(h.control.remoteInput,input);h.control.receive({type:'action',action:'punch',input});assert.equal(h.actions[0].index,1);h.setTime(1000);h.control.tick();assert.deepEqual(h.control.remoteInput,{move:0,crouch:false,block:false});assert.equal(h.control.paused,true);assert.ok(h.sent.some(p=>p.type==='pause'&&p.paused));});
test('pause application never echoes; only host may request resume with fresh neutral peer',()=>{const host=controller(),guest=controller(1);host.control.receive(start);guest.control.receive(start);host.control.receive({type:'pause',paused:true});assert.equal(host.sent.length,0);assert.equal(host.control.requestPause(false),false);host.control.receive({type:'input',input:{move:0,crouch:false,block:false}});assert.equal(host.control.requestPause(false),true);guest.control.receive({type:'pause',paused:true});assert.equal(guest.control.requestPause(false),false);assert.equal(guest.sent.length,0);});
test('host FX batches are replayed once and old rematch events are discarded',()=>{const guest=controller(1);guest.control.receive(start);const packet={type:'events',matchId:1,seq:1,events:[{type:'hit',x:100,y:200,attacker:0,target:1}]};guest.control.receive(packet);guest.control.receive(packet);guest.control.receive({...packet,seq:2,matchId:2});assert.equal(guest.events.length,1);});
test('travel interpolation leaves contact poses, phases and Deletions discrete',()=>{const h=controller(1);h.control.receive(start);const first=snapshot(match(),1);first.state.phase='fight';first.views[0].poseIndex=0;first.views[0].x=500;h.control.receive({type:'snapshot',snapshot:first});h.setTime(40);const second=structuredClone(first);second.seq=2;second.views[0].x=600;h.control.receive({type:'snapshot',snapshot:second});h.setTime(60);assert.equal(h.control.views()[0].x,550);const contact=structuredClone(second);contact.seq=3;contact.views[0].poseIndex=2;contact.views[0].x=700;h.control.receive({type:'snapshot',snapshot:contact});assert.equal(h.control.views()[0].x,700);const deletion=structuredClone(contact);deletion.seq=4;deletion.state.phase='deletion';deletion.state.winner=0;deletion.state._deletionOrigin={direction:1,target:700,victimFacing:'left',near:500,winner:500,victim:700};deletion.views[0].x=800;h.control.receive({type:'snapshot',snapshot:deletion});assert.equal(h.control.views()[0].x,800);});
test('a guest with stale snapshots pauses and cannot reset or rematch before result',()=>{const h=controller(1);h.control.receive(start);h.control.receive({type:'snapshot',snapshot:snapshot()});assert.equal(h.control.requestRematch('fight'),false);h.setTime(1200);h.control.tick();assert.equal(h.control.paused,true);assert.equal(h.control.requestRematch('over'),true);assert.equal(h.sent.at(-1).type,'rematch');assert.equal(h.starts.length,1);});
test('disconnect neutralizes controls and stops every subsequent authority action',()=>{const h=controller();h.control.receive(start);h.control.receive({type:'input',input});h.control.disconnect('Gone');h.control.disconnect('Again');assert.equal(h.disconnected.length,1);assert.deepEqual(h.control.remoteInput,{move:0,crouch:false,block:false});assert.equal(h.control.action('punch',input),false);assert.equal(h.control.publish(match(),[]),false);});
function sourceFunction(name,args){const source=readFileSync(new URL('../public/games/system-clash/play/fight.js',import.meta.url),'utf8');const body=source.match(new RegExp('function '+name+'\\([^)]*\\) \\{([\\s\\S]*?)\\n\\}'))?.[1];assert.ok(body);return new Function('env','with(env){return function('+args+'){'+body+'}}');}
test('guest tick renders but never advances combat, including after browser focus',()=>{let advances=0,draws=0;const env={pollGamepads(){},last:0,ready:true,screenSuspended:false,paused:false,inspectTime:null,motionTime:null,accumulator:0,attackInputs:{},attackCommands(){},flushAttackInputs:()=>[],performance:{now:()=>100},windowActive:true,document:{hidden:false},onlineCombat:{seat:1,started:true,input(){},tick(){},views:()=>[],publish(){}},controls:()=>[input,{move:0,crouch:false,block:false}],match:{phase:'fight',fighters:[{},{}]},getFighterView:()=>({}),advanceMatch:()=>advances++,dispatchEvents(){},effects:{update(){}},draw:()=>draws++,requestAnimationFrame(){},tick(){},previousTravelViews:null,previousTravelPhase:null};sourceFunction('tick','now')(env)(100);assert.equal(advances,0);assert.equal(draws,1);});
test('tournament result blocking routes controller confirm away from ordinary restart',()=>{let starts=0,tournament=0;const env={ready:true,effects:{startAudio(){}},reset(){starts++;},canvas:{focus(){}},onlineCombat:null,tournamentOverlay:{active:true,blocking:true,handleAction:action=>{assert.equal(action,'confirm');tournament++;return true;}}};sourceFunction('start','')(env)();assert.equal(starts,0);assert.equal(tournament,1);});



test('damage, attachments and host events preserve unsigned render seeds',()=>{const m=match();const mark={id:'damage-1',site:'torso',kind:'bruise',intensity:.5,amount:10,at:0,facing:'right',direction:1,heightRatio:.57,weaponType:null,seed:2654435761};m.fighters[0].damageMarks.push(mark);m.fighters[0].embeddedWeapons.push({id:'weapon-1',type:'neural-spike',site:'torso',facing:'right',direction:1,at:0,heightRatio:.57,seed:4294967295});assert.ok(snapshot(m));const host=controller();host.control.receive(start);assert.equal(host.control.publishEvents([{type:'hit',seed:4294967295}]),true);});
test('malformed projectiles, pickups and wear arrays fail closed before rendering',()=>{for(const change of [s=>s.state.projectiles=[{x:10,y:20}],s=>s.state.stagePickups=[{type:'admin',x:100,y:620}],s=>s.state.fighters[0].damageMarks=[{}],s=>s.views[0].embeddedWeapons=[{}],s=>s.state.fighters[0].damageSites.head.amount=-1]){const s=snapshot();change(s);assert.equal(net.readFightSnapshot(s,options),null);}});
test('unordered state cannot undo a newer reliable pause or replay a pre-resume pause',()=>{const guest=controller(1);guest.control.receive(start);guest.control.requestPause(true);const before=snapshot(match(),2);assert.equal(guest.control.receive({type:'snapshot',snapshot:before}),true);assert.equal(guest.control.paused,true);assert.equal(guest.states.at(-1).state.paused,true);guest.control.receive({type:'pause',paused:false,snapshotSeq:3});const stale=snapshot(match(),3);stale.state.paused=true;assert.equal(guest.control.receive({type:'snapshot',snapshot:stale}),false);assert.equal(guest.control.paused,false);});
test('host authority rejects an incoming resume but permits its own released-control resume',()=>{const host=controller();host.control.receive(start);host.control.receive({type:'pause',paused:true});assert.equal(host.control.receive({type:'pause',paused:false}),false);assert.equal(host.control.paused,true);host.control.receive({type:'input',input:{move:0,crouch:false,block:false}});assert.equal(host.control.requestPause(false),true);assert.equal(host.sent.at(-1).snapshotSeq,0);});
test('host snapshots are bounded to twenty-five publishes per second',()=>{const host=controller();host.control.receive(start);const m=match(),views=m.fighters.map((_,i)=>getFighterView(m,i));for(let i=0;i<1000;i++){host.setTime(i);host.control.publish(m,views);}assert.equal(host.sent.filter(p=>p.type==='snapshot').length,25);assert.ok(host.sent.every(p=>Buffer.byteLength(JSON.stringify(p))<=65536));});
test('a guest awaiting assets or handshake never enters autonomous combat',()=>{let advances=0;const env={pollGamepads(){},last:0,ready:true,screenSuspended:false,paused:false,motionTime:null,inspectTime:null,accumulator:0,onlineCombat:null,onlineBridge:{enabled:true},draw(){},requestAnimationFrame(){},tick(){},advanceMatch:()=>advances++};sourceFunction('tick','now')(env)(50);assert.equal(advances,0);});
test('online controls ignore P2 keyboard and hardware while preserving the own P1 controller',()=>{const env={held:new Set(['ArrowRight','ArrowDown','Digit0']),virtual:new Set(),latched:new Set(),tapMove:0,tapUntil:0,performance:{now:()=>0},onlineBridge:{enabled:true},match:{mode:'local'},gamepadPlayers:[{move:-1,crouch:true,block:true},{move:1,crouch:true,block:true}]};assert.deepEqual(sourceFunction('controls','')(env)(),[{move:-1,crouch:true,block:true},{move:0,crouch:false,block:false}]);});

test('host resolves remote contact and guest state receives that damage without a local simulation',()=>{const authoritative=match();authoritative.phase='fight';authoritative.fighters[0].x=1000;authoritative.fighters[1].x=1105;const guest=controller(1);guest.control.receive(start);const host=net.createOnlineCombatController({...options,seat:0,now:()=>0,onAction:c=>performAction(authoritative,c.index,c.action,c.input)});host.receive(start);host.receive({type:'action',action:'punch',input:{move:0,crouch:false,block:false}});for(let i=0;i<40;i++)advanceMatch(authoritative,1000/60,[{move:0,crouch:false,block:false},{move:0,crouch:false,block:false}]);assert.ok(authoritative.fighters[0].hp<100);assert.equal(authoritative.fighters[1].hp,authoritative.fighters[1].maxHp);const wire=snapshot(authoritative);assert.ok(wire);guest.control.receive({type:'snapshot',snapshot:wire});const local=match(),beforeClips=local.fighters[1]._clips;const rendered=net.applyFightSnapshot(local,guest.states[0]);assert.equal(rendered.fighters[0].hp,authoritative.fighters[0].hp);assert.equal(rendered.fighters[1]._clips,beforeClips);assert.deepEqual(rendered.events,[]);});
test('connected-room wall damage and cinematic origin survive public snapshots',()=>{const m=match();m.stage.wallRooms['sheila-office']={left:{damage:80,broken:true},right:{damage:20,broken:false}};m.stage.cinematicOrigin=640;m.stage.transitionSerial=1;m.stage.walls.right={damage:80,broken:true};const wire=snapshot(m);assert.ok(wire);assert.equal(wire.state.stage.wallRooms['sheila-office'].left.broken,true);assert.equal(wire.state.stage.cinematicOrigin,640);});

function pad(index=0,buttons=[]){return {index,id:'DualSense-'+index,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},(_,i)=>({pressed:buttons.includes(i),value:buttons.includes(i)?1:0}))};}
test('online gamepad routes only the own controller and ignores the remote hardware disconnect',async()=>{const {createGamepadInput}=await import('../public/games/system-clash/play/fight-gamepad.mjs');const calls=[],env={ready:true,paused:false,inspectTime:null,motionTime:null,windowActive:true,screenSuspended:false,matchOptions:{open:false},roundMenu:{open:false},onlineBridge:{enabled:true},tournamentOverlay:null,match:{mode:'local',phase:'fight'},gamepads:createGamepadInput(),gamepadPlayers:[],controllerLabel:'',attackInputs:{pending:new Map()},attackButtons:new Set(),document:{hidden:false,body:{classList:{contains:()=>false}}},navigator:{getGamepads:()=>env.pads},$:()=>({textContent:''}),controls:()=>[{move:0,crouch:false,block:false},{move:0,crouch:false,block:false}],action:(index,name)=>calls.push({index,name}),releaseAttackInput(){},clearInput:()=>calls.push({name:'clear'}),togglePause:()=>calls.push({name:'pause'}),pads:[]};const poll=sourceFunction('pollGamepads','now')(env);env.pads=[pad(),pad(1)];poll(0);env.pads=[pad(),pad(1,[5])];poll(10);env.pads=[pad(),null];poll(20);assert.deepEqual(calls,[]);env.pads=[pad(0,[5]),null];poll(30);poll(90);assert.deepEqual(calls,[{index:0,name:'grab'}]);});
test('blocking Tournament gamepad uses overlay navigation and confirm without underlying combat',async()=>{const {createGamepadInput}=await import('../public/games/system-clash/play/fight-gamepad.mjs');const handled=[],env={ready:true,paused:false,inspectTime:null,motionTime:null,windowActive:true,screenSuspended:false,matchOptions:{open:false},roundMenu:{open:false},onlineBridge:{enabled:false},tournamentOverlay:{blocking:true,handleAction:a=>handled.push(a)},match:{mode:'cpu',phase:'over'},gamepads:createGamepadInput(),gamepadPlayers:[],controllerLabel:'',attackInputs:{pending:new Map()},document:{hidden:false,body:{classList:{contains:()=>false}}},navigator:{getGamepads:()=>env.pads},$:()=>({textContent:''}),releaseAttackInput(){},pads:[]};const poll=sourceFunction('pollGamepads','now')(env);env.pads=[pad()];poll(0);env.pads=[pad(0,[15])];poll(10);env.pads=[pad()];poll(20);env.pads=[pad(0,[0])];poll(30);assert.deepEqual(handled,['ArrowRight','confirm']);});

test('Lost Marbles snapshots preserve selected seats, hidden local data and eight-key walk timing',()=>{
 for(const seat of [0,1]){
  const fighters=[{id:'6-bit'},{id:'6-bit'}];fighters[seat]={id:'lost-marbles'};
  const authoritative=createMatch({mode:'local',stage:'radio-studio',start:false,fighters});
  const schema={roster:['6-bit','lost-marbles'],fighterIds:fighters.map(f=>f.id),clipIds,matchId:1};
  const views=authoritative.fighters.map((_,index)=>getFighterView(authoritative,index));
  views[seat]={...views[seat],clip:'walk',elapsed:550,poseIndex:7};
  const wire=net.makeFightSnapshot(authoritative,views,{...schema,seq:1,at:100});assert.ok(wire);
  const received=[],guest=net.createOnlineCombatController({...schema,seat:1,onState:value=>received.push(value)});
  guest.receive(start);assert.equal(guest.receive({type:'snapshot',snapshot:wire}),true);
  assert.equal(guest.views()[seat].elapsed,550);assert.equal(guest.views()[seat].poseIndex,7);
  const local=createMatch({mode:'local',start:false,fighters});
  const rendered=net.applyFightSnapshot(local,received[0]);
  assert.equal(rendered.fighters[seat].id,'lost-marbles');assert.equal(rendered.fighters[seat].maxHp,authoritative.fighters[seat].maxHp);
  for(const key of ['_clips','_style','_statProfile','_statScalars'])assert.equal(rendered.fighters[seat][key],local.fighters[seat][key]);
  const swapped=structuredClone(wire);swapped.state.fighters[seat].id='6-bit';swapped.views[seat].id='6-bit';assert.equal(net.readFightSnapshot(swapped,schema),null);
  guest.destroy();
 }
});
test('Mutilator snapshots preserve selected seats, hidden local data and native walk timing',()=>{
 for(const seat of [0,1]){
  const fighters=[{id:'6-bit'},{id:'6-bit'}];fighters[seat]={id:'mutilator'};
  const authoritative=createMatch({mode:'local',stage:'radio-studio',start:false,fighters});
  const schema={roster:['6-bit','mutilator'],fighterIds:fighters.map(f=>f.id),clipIds,matchId:1};
  const views=authoritative.fighters.map((_,index)=>getFighterView(authoritative,index));
  views[seat]={...views[seat],clip:'walk',elapsed:450,poseIndex:3};
  const wire=net.makeFightSnapshot(authoritative,views,{...schema,seq:1,at:100});assert.ok(wire);
  const received=[],guest=net.createOnlineCombatController({...schema,seat:1,onState:value=>received.push(value)});
  guest.receive(start);assert.equal(guest.receive({type:'snapshot',snapshot:wire}),true);
  assert.equal(guest.views()[seat].elapsed,450);assert.equal(guest.views()[seat].poseIndex,3);
  const local=createMatch({mode:'local',start:false,fighters});
  const rendered=net.applyFightSnapshot(local,received[0]);
  assert.equal(rendered.fighters[seat].id,'mutilator');assert.equal(rendered.fighters[seat].maxHp,authoritative.fighters[seat].maxHp);
  for(const key of ['_clips','_style','_statProfile','_statScalars'])assert.equal(rendered.fighters[seat][key],local.fighters[seat][key]);
  const swapped=structuredClone(wire);swapped.state.fighters[seat].id='6-bit';swapped.views[seat].id='6-bit';assert.equal(net.readFightSnapshot(swapped,schema),null);
  guest.destroy();
 }
});test('station portal snapshots snap at the exit instead of interpolating across the arena',()=>{
 const h=controller(1);h.control.receive(start);const first=snapshot(match(),1);first.state.phase='fight';first.state.stage.id='interdimensional-station';first.state.stage.portalSerial=0;first.views[0].poseIndex=0;first.views[0].x=150;
 h.control.receive({type:'snapshot',snapshot:first});h.setTime(40);
 const second=structuredClone(first);second.seq=2;second.state.stage.portalSerial=1;second.state.stage.lastPortalTransit={serial:1,at:40,transits:[{target:0,from:'left',to:'right',fromX:150,toX:1650,exitX:1650,y:620}]};second.views[0].x=1650;
 h.control.receive({type:'snapshot',snapshot:second});h.setTime(60);assert.equal(h.control.views()[0].x,1650);
 const third=structuredClone(second);third.seq=3;third.views[0].x=1610;h.setTime(80);h.control.receive({type:'snapshot',snapshot:third});h.setTime(100);assert.equal(h.control.views()[0].x,1630);
});
test('guest waits for its first authoritative snapshot then enforces the ordinary stale-state limit',()=>{
 const h=controller(1);h.control.receive(start);h.setTime(1200);h.control.tick();assert.equal(h.control.paused,false);
 h.control.receive({type:'snapshot',snapshot:snapshot()});h.setTime(2199);h.control.tick();assert.equal(h.control.paused,false);h.setTime(2200);h.control.tick();assert.equal(h.control.paused,true);
 const missing=controller(1);missing.control.receive(start);missing.setTime(5000);missing.control.tick();assert.equal(missing.control.paused,true);
});

test('freshness starts after slow synchronous frame initialization and keeps the exact one-second rule',()=>{
 for(const seat of [0,1]){
  let time=0;const pauses=[];const control=net.createOnlineCombatController({...options,seat,now:()=>time,send:()=>true,onStart:()=>{time=1200;},onPause:value=>pauses.push(value)});
  control.receive(start);control.tick();assert.equal(control.paused,false);
  if(seat===1)control.receive({type:'snapshot',snapshot:snapshot()});
  time=2199;control.tick();assert.equal(control.paused,false);time=2200;control.tick();assert.equal(control.paused,true);assert.deepEqual(pauses,[true]);
 }
});
test('guest frame acknowledges and releases controls only after reset and focus finish',()=>{
 const order=[];let time=0;const env={reset:(active,seed)=>{assert.equal(active,true);assert.equal(seed,77);time=1200;order.push('reset');},effects:{startAudio:()=>order.push('audio')},canvas:{focus:()=>order.push('focus')},onlineBridge:{seat:1,send:packet=>{assert.equal(time,1200);assert.deepEqual(packet,{type:'started',matchId:1});order.push('started');}},onlineCombat:{input:value=>{assert.deepEqual(value,{move:0,crouch:false,block:false});order.push('neutral');}}};
 sourceFunction('startOnlineFight','packet')(env)(start);assert.deepEqual(order,['reset','audio','focus','started','neutral']);
 order.length=0;env.onlineBridge.seat=0;sourceFunction('startOnlineFight','packet')(env)(start);assert.deepEqual(order,['reset','audio','focus']);
});
