import test from 'node:test';import assert from 'node:assert/strict';import {createMatch,performAction,advanceMatch,consumeEvents} from '../public/games/system-clash/play/fight-engine.mjs';import {interpolateFightViews} from '../public/games/system-clash/play/fight-presentation.mjs';
const body={bounds:{left:-10,right:10,top:-320,bottom:0},hurt:[{site:'torso',left:-5,right:5,top:-220,bottom:-180}],measuredHurt:true,sites:{head:{x:0,y:-280},torso:{x:0,y:-200},legs:{x:0,y:-80},grip:{x:0,y:-220}},strikeRadius:3};
function scene({start=100,end=130,transition=110,from=120,to=260,bodyY=-200}={}){const idle={duration:600,combatPoses:{duration:600,loop:true,entries:[{index:0,start:0,end:600}],frames:{right:[body],left:[body]}}},p0={...body,strike:{x:from,y:bodyY},strikeStart:{x:from-12,y:bodyY}},p1={...body,strike:{x:to,y:bodyY},strikeStart:{x:to-12,y:bodyY}},punch={duration:300,contactMs:start,activeEndMs:end,combatPoses:{duration:300,entries:[{index:0,start:0,end:transition},{index:1,start:transition,end:300}],frames:{right:[p0,p1],left:[p0,p1]}}},m=createMatch({mode:'local',start:false,roundTimeMs:0,fighters:[{id:'6-bit',height:320},{id:'6-bit',height:320}],clips:[{idle,punch},{idle,punch}]});m.phase='fight';m.fighters[0].x=900;m.fighters[1].x=1100;assert(performAction(m,0,'punch'));Object.assign(m.fighters[0]._clips.punch,{playbackRate:1,contactMs:start,activeEndMs:end,duration:300});consumeEvents(m);return m;}
const hits=m=>consumeEvents(m).filter(e=>e.type==='hit'&&e.attacker===0&&e.action==='punch');
test('A native tip crossing the body between two active keys lands without a wider radius',()=>{const m=scene();m.fighters[0].actionTime=105;advanceMatch(m,10,[{},{}]);assert.equal(hits(m).length,1);assert.equal(m.fighters[0]._clips.punch.combatPoses.frames.right[0].strikeRadius,3);});
test('A short active occurrence crossed within one physics step is measured at its native contact pose',()=>{const m=scene({start:100,end:102,transition:100,to:200});m.fighters[0].actionTime=95;advanceMatch(m,10,[{},{}]);assert.equal(hits(m).length,1);});
test('Anticipation and recovery cannot borrow the active sweep',()=>{for(const time of [85,140]){const m=scene({to:200});m.fighters[0].actionTime=time;advanceMatch(m,10,[{},{}]);assert.equal(hits(m).length,0);}});
test('Measured alpha holes are not filled by old generic torso rectangles',()=>{const m=scene({from:200,to:200,bodyY:-170});m.fighters[0].actionTime=105;advanceMatch(m,10,[{},{}]);assert.equal(hits(m).length,0);});
test('Ordinary action changes interpolate whole travel while retaining current native pose and time',()=>{const old=[{clip:'walk',facing:'right',poseIndex:1,elapsed:85,x:500,y:0,opacity:1}],next=[{clip:'punch',facing:'right',poseIndex:0,elapsed:10,x:512,y:0,opacity:1}],v=interpolateFightViews(old,next,.25)[0];assert.equal(v.x,503);assert.equal(v.clip,'punch');assert.equal(v.poseIndex,0);assert.equal(v.elapsed,10);});
test('Facing changes interpolate root travel while keeping independently authored current facing',()=>{const v=interpolateFightViews([{clip:'idle',facing:'left',poseIndex:0,elapsed:10,x:500,y:0}],[{clip:'idle',facing:'right',poseIndex:0,elapsed:25,x:510,y:0}],.5)[0];assert.equal(v.x,505);assert.equal(v.facing,'right');assert.equal(v.elapsed,25);});
