import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import sharp from 'sharp';
import {loadFightArt,assetPath} from '../public/games/system-clash/play/fight-assets.mjs';
const play=new URL('../public/games/system-clash/play/',import.meta.url),sha=x=>createHash('sha256').update(x).digest('hex');
test('Hosted and prepared portable artwork select the local clarity derivative; older bundles retain their valid native source',async()=>{
 const frame={rect:[0,0,20,40],anchor:[10,40]},data={file:'body.webp',runtimeFile:'body.runtime.webp',clarityFile:'body.clarity-v1.webp',frames:{right:[frame],left:[frame]},order:[0],frameMs:[120]},manifest={id:'fixture',character:'Fixture',height:40,clips:Object.fromEntries(['idle','walk','crouch','block','punch','kick','high','low','grabbed','thrown','knockdown','getup'].map(n=>[n,data]))},savedImage=globalThis.Image,savedFetch=globalThis.fetch;
 globalThis.fetch=async()=>({ok:true,json:async()=>manifest});globalThis.Image=class{set src(value){this.loaded=value;this.width=20;this.height=40;queueMicrotask(()=>this.onload());}};
 try{for(const[images,expected]of[[undefined,'body.clarity-v1.webp'],[{'assets/fighters/fixture/body.clarity-v1.webp':'approved-clarity'},'approved-clarity'],[{'assets/fighters/fixture/body.runtime.webp':'approved-original'},'approved-original']]){const art=await loadFightArt({bundle:images?{manifests:{fixture:manifest},images}:undefined,baseURL:'https://system-clash.invalid/',ids:['fixture']});assert(art[0].clips.idle.image.loaded.endsWith(expected));}}finally{globalThis.Image=savedImage;globalThis.fetch=savedFetch;}
});
test('Every selected clarity atlas preserves all alpha, edge color, dimensions and native frame metadata with bounded interior luminance correction',async()=>{const roster=JSON.parse(readFileSync(new URL('assets/fight-roster.json',play))).fighters,done=new Set();let changed=0;for(const{id}of roster)for(const bank of ['fighters','arcade','deletions']){const mp=`assets/${bank}/${id}/manifest.json`,m=JSON.parse(readFileSync(new URL(mp,play)));for(const c of Object.values(m.clips)){if(['mac-modem','ash-flowers','mutilator','doofnoobler','bnl-01'].includes(id)){assert.equal(c.clarityFile,undefined,'Already-clear recent native art stays intact');continue;}if(!c.clarityFile)continue;const q=c.nativeClarity;assert.equal(q.kind,'bounded-interior-luminance-unsharp');assert.equal(q.version,1);assert.equal(q.maxChannelDelta,6);assert.equal(sha(JSON.stringify(c.frames)),q.frameMetadataSha256);const original=assetPath(mp,q.originalFile),derived=assetPath(mp,c.clarityFile);if(done.has(derived))continue;done.add(derived);const aBytes=readFileSync(new URL(original,play)),bBytes=readFileSync(new URL(derived,play));assert.equal(sha(aBytes),q.sourceSha256);assert.equal(sha(bBytes),q.derivativeSha256);const[a,b]=await Promise.all([sharp(aBytes).ensureAlpha().raw().toBuffer({resolveWithObject:true}),sharp(bBytes).ensureAlpha().raw().toBuffer({resolveWithObject:true})]);assert.equal(a.info.width,b.info.width);assert.equal(a.info.height,b.info.height);assert.equal(sha(b.data),q.derivativeRgbaSha256);assert.equal(sha(a.data),q.sourceRgbaSha256);let alphaMismatch=0,edgeMismatch=0,maxDelta=0;for(let y=0;y<a.info.height;y++)for(let x=0;x<a.info.width;x++){const i=(y*a.info.width+x)*4;alphaMismatch+=a.data[i+3]!==b.data[i+3];let interior=x>0&&y>0&&x<a.info.width-1&&y<a.info.height-1&&a.data[i+3]>=250;if(interior)for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)interior&&=a.data[(yy*a.info.width+xx)*4+3]>=250;for(let c=0;c<3;c++){const delta=Math.abs(a.data[i+c]-b.data[i+c]);maxDelta=Math.max(maxDelta,delta);if(!interior)edgeMismatch+=delta>0;changed+=delta>0;}}assert.equal(alphaMismatch,0,derived+' native alpha exact');assert.equal(edgeMismatch,0,derived+' transparency edge RGB exact');assert(maxDelta<=6,derived+' interior RGB correction stays bounded');}}assert(done.size>0,'Explicit selected active WebP derivatives exist');assert(changed>0);});
