import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const file=new URL('../public/games/system-clash/play/tournament-voice.mjs',import.meta.url);
const {createTournamentVoice=()=>({sync:async()=>{},enableMic:async()=>true,mute:async()=>{},dispose(){}})}=fs.existsSync(file)?await import(file):{};
const event=()=>({code:'ABCDEF',status:'running',currentBoutId:'bout-1',selfEntrantId:'p1',bouts:[{id:'bout-1',status:'live',roomCode:'ROOMAA',roomMatchId:1,p1:'p1',p2:'p2'}],entrants:[{id:'p1',fighter:'6-bit'},{id:'p2',fighter:'cliff'}]});
function fixture(){
 let stopped=0,captures=0,available=true,pending=null,publishFailure=false,peerFailure=false;const calls=[],states=[];
 const track=()=>({kind:'audio',stop(){stopped++;},addEventListener(){}});
 const stream=()=>({getTracks:()=>[track()],getAudioTracks:()=>[track()]});
 const node=()=>({gain:{value:1},frequency:{value:0},Q:{value:0},connect(){},disconnect(){},start(){},stop(){}});
 class Context{state='running';destination=node();async resume(){}async close(){}createMediaStreamSource(){return node()}createBiquadFilter(){return node()}createWaveShaper(){return node()}createDynamicsCompressor(){return{...node(),threshold:{},knee:{},ratio:{},attack:{},release:{}}}createGain(){return node()}createMediaStreamDestination(){return{...node(),stream:stream()}}createAnalyser(){return{...node(),fftSize:256,getByteTimeDomainData(a){a.fill(128)}}}createOscillator(){return node()}}
 class Peer{constructor(){if(peerFailure)throw new Error('Voice peer unavailable.')}iceGatheringState='complete';connectionState='connected';localDescription=null;addEventListener(){}removeEventListener(){}close(){}addTransceiver(){return{mid:'0',sender:{setParameters:async()=>{},getParameters:()=>({encodings:[{}]})}}}async createOffer(){return{type:'offer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=mid:0\r\na=sendonly\r\n'}}async setLocalDescription(v){this.localDescription=v}async setRemoteDescription(){}}
 const win={AudioContext:Context,RTCPeerConnection:Peer,navigator:{mediaDevices:{getUserMedia:async()=>{captures++;return pending?await pending:stream();}}},document:{createElement:()=>({play:async()=>{},pause(){},remove(){},volume:1})},setInterval:()=>1,clearInterval(){},setTimeout,clearTimeout,addEventListener(){},removeEventListener(){}};
 const fetch=async(url,options)=>{const body=JSON.parse(options.body);calls.push(body);let value={ok:true};if(body.action==='status')value={available,active:true,boutId:'bout-1',canPublish:true,speakers:[]};if(body.action==='ice')value={iceServers:[]};if(body.action==='publish'&&publishFailure)throw new Error('Voice provider unavailable.');if(body.action==='publish')value={handle:'publisher-handle',sessionDescription:{type:'answer',sdp:'v=0'}};return{ok:true,json:async()=>value};};
 const voice=createTournamentVoice({window:win,fetch,onState:s=>states.push(s)});
 return{voice,calls,states,stopped:()=>stopped,captures:()=>captures,setAvailable:v=>available=v,setPending:v=>pending=v,setPublishFailure:v=>publishFailure=v,setPeerFailure:v=>peerFailure=v,stream};
}
test('synchronizing a live bout never captures microphone automatically',async()=>{const f=fixture();await f.voice.sync(event());assert.equal(f.captures(),0);assert.equal(f.states.at(-1).canPublish,true);f.voice.dispose();});
test('absent SFU or an unassigned viewer cannot request microphone',async()=>{const f=fixture();f.setAvailable(false);await f.voice.sync(event());assert.equal(await f.voice.enableMic(),false);assert.equal(f.captures(),0);f.voice.dispose();const g=fixture();await g.voice.sync({...event(),selfEntrantId:null});assert.equal(await g.voice.enableMic(),false);assert.equal(g.captures(),0);g.voice.dispose();});
test('mute ends capture and withdraws publication without ending tournament or incoming audio',async()=>{const f=fixture();await f.voice.sync(event());assert.equal(await f.voice.enableMic(),true);await f.voice.mute(true);assert.ok(f.stopped()>=2);assert.ok(f.calls.some(c=>c.action==='close'&&c.handle==='publisher-handle'));assert.equal(f.states.at(-1).enabled,false);f.voice.dispose();});
test('late microphone permission after match change stops tracks and cannot publish into another bout',async()=>{const f=fixture();await f.voice.sync(event());let resolve;f.setPending(new Promise(r=>resolve=r));const enabling=f.voice.enableMic();await new Promise(r=>setImmediate(r));await f.voice.sync({...event(),status:'complete',currentBoutId:null});resolve(f.stream());assert.equal(await enabling,false);assert.ok(f.stopped()>0);assert.ok(!f.calls.some(c=>c.action==='publish'));f.voice.dispose();});

test('failed voice publication stops microphone and leaves voice disabled',async()=>{const f=fixture();await f.voice.sync(event());f.setPublishFailure(true);assert.equal(await f.voice.enableMic(),false);assert.ok(f.stopped()>=2);assert.equal(f.states.at(-1).enabled,false);assert.equal(f.states.at(-1).muted,true);f.voice.dispose();});
test('media setup failure after capture disposes the derived output track too',async()=>{const f=fixture();await f.voice.sync(event());f.setPeerFailure(true);assert.equal(await f.voice.enableMic(),false);assert.ok(f.stopped()>=2);f.voice.dispose();});

test('stale microphone completion keeps the newer enable operation pending',async()=>{const f=fixture();await f.voice.sync(event());let resolveOld,resolveNew;f.setPending(new Promise(r=>resolveOld=r));const old=f.voice.enableMic();await new Promise(r=>setImmediate(r));await f.voice.mute(true);f.setPending(new Promise(r=>resolveNew=r));const fresh=f.voice.enableMic();await new Promise(r=>setImmediate(r));resolveOld(f.stream());assert.equal(await old,false);assert.equal(f.states.at(-1).connecting,true);resolveNew(f.stream());assert.equal(await fresh,true);f.voice.dispose();});
