"use client";
import { useState } from "react";
import Link from "next/link";
import type { MemberAccess } from "@/lib/member-access";
import type { CrewShowOverview as ShowData, CrewShowTrack } from "@/lib/crew-show";
import { crewDuration, useCrewToolData } from "@/lib/crew-show-client";
function TrackCard({ label, track }: { label: string; track: CrewShowTrack | null }) {
 return <article style={{minWidth:0}} className="rounded-xl border border-border bg-background/60 p-5"><h2 className="text-sm font-semibold text-muted">{label}</h2>{track ? <><p className="mt-3 text-xl font-bold">{track.title}</p><p className="mt-2 text-accent">{track.artist}{track.collaborators.length > 0 ? ` · feat. ${track.collaborators.join(", ")}` : ""}</p><p className="mt-3 text-sm text-muted">{track.lane} lane · {track.status}</p></> : <p className="mt-3 text-muted">No track selected.</p>}</article>;
}
export function CrewShowOverview({ access }: { access: MemberAccess }) {
 const [selected, setSelected] = useState("");
 const { data, loading, error, refresh } = useCrewToolData<ShowData>(access, "show.overview", "/api/member/tools/show" + (selected ? `?trackId=${encodeURIComponent(selected)}` : ""));
 const timing = data?.timing, intro = data?.introduction;
 return <section style={{overflowWrap:"anywhere",minWidth:0}} className="mx-auto max-w-6xl rounded-xl border border-border bg-surface p-5 sm:p-8">
  <Link href={access.access.owner ? "/account/owner/radio" : "/account/crew"} className="text-accent underline">{access.access.owner ? "Back to Radio & shows" : "Back to Crew workspace"}</Link>
  <div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="public-kicker">BARCODE Radio</p><h1 className="mt-2 text-3xl font-bold">Live show overview</h1><p className="mt-3 text-muted">Current show information and credited artist introductions.</p></div><button type="button" onClick={() => void refresh()} disabled={loading} className="rounded-lg border border-border px-4 py-2 disabled:opacity-50">Refresh</button></div>
  {loading ? <p role="status" className="mt-6 text-muted">Checking access and current show information…</p> : error ? <p role="alert" className="mt-6 text-muted">{error}</p> : !data?.available ? <p role="status" className="mt-6 text-muted">Current queue information is unavailable.</p> : !data.session ? <p role="status" className="mt-6 text-muted">No current public broadcast is available.</p> : <>
   <p className="mt-6 text-muted">{data.session.title} · {data.session.showDate} · Submissions {data.session.submissionsOpen ? "open" : "closed"}</p>
   <div className="mt-5 grid gap-4 md:grid-cols-2"><TrackCard label="Current track" track={data.current} /><TrackCard label="Next In Line" track={data.next} /></div>
   {data.pressure && <p className="mt-5 text-sm text-muted">Queue pressure: {data.pressure.level} · {data.pressure.accepted} of {data.pressure.capacity} show slots accepted{data.pressure.full ? " · Full" : ""}</p>}
   {timing && <article className="mt-6 rounded-xl border border-border p-5"><h2 className="text-lg font-bold">Show timing estimates</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-sm text-muted">Music remaining</p><p className="mt-1 text-xl">{crewDuration(timing.remainingMusicSeconds)}</p></div><div><p className="text-sm text-muted">Show remaining</p><p className="mt-1 text-xl">{crewDuration(timing.remainingShowSeconds)}</p></div><div><p className="text-sm text-muted">Estimated end</p><p className="mt-1 text-xl">{timing.projectedEndAt ? new Date(timing.projectedEndAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : "Unavailable"}</p></div></div><p className="mt-4 text-sm text-muted">{timing.confidence} confidence · {timing.unknownDurationCount} tracks use estimated duration. End time includes modeled talk, Wheel and commercial time. Playback timing {timing.playbackEvidence === "player_reported" ? "is player reported" : "is unavailable"}.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><h3 className="font-semibold">Wheel</h3><p className="mt-2 text-sm text-muted">{timing.wheel.spinsOwed} spins owed · {timing.wheel.status.replaceAll("_", " ")} · {crewDuration(timing.wheel.estimatedSeconds)} estimated ceremony time</p></div><div><h3 className="font-semibold">Commercial</h3><p className="mt-2 text-sm text-muted">{timing.commercial.status.replaceAll("_", " ")} · {timing.commercial.eligible ? "Timing conditions met" : "Timing conditions not met"} · {crewDuration(timing.commercial.estimatedSeconds)} planned{timing.commercial.estimatedRemainingSeconds !== null ? ` · ${crewDuration(timing.commercial.estimatedRemainingSeconds)} remaining estimate` : ""}</p></div></div></article>}
   <article className="mt-6 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Artist introduction</h2><label htmlFor="crew-intro-track" className="mt-4 block text-sm text-muted">Upcoming song</label><select id="crew-intro-track" value={intro?.trackId ?? ""} onChange={event => setSelected(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background p-3" disabled={data.upcoming.length === 0}><option value="" disabled>Select an upcoming song</option>{data.upcoming.map(track => <option key={track.id} value={track.id}>{track.artist} — {track.title}</option>)}</select>
    {intro ? <><h3 className="mt-5 text-2xl font-bold">{intro.artist}</h3><p className="mt-2">{intro.title}{intro.collaborators.length > 0 ? ` · feat. ${intro.collaborators.join(", ")}` : ""}</p><p className="mt-3 text-sm text-accent">{intro.creditSource === "reviewed_credit" ? "Reviewed credits" : intro.creditSource === "inferred_credit" ? "Inferred credit grouping" : "Submitted credits"}</p><p className="mt-2 text-sm text-muted">Archive appearances describe a credited artist group. They do not verify an account or establish complete artist history.</p>{intro.archive.available ? <><p className="mt-4">{intro.archive.showCount} retained public shows · {intro.archive.trackCount} credited tracks</p><p className="mt-2 text-sm text-muted">Archive coverage begins {intro.archive.historyCoverageStartedAt}. {intro.archive.trackCount === 0 ? "No matching appearances are recorded in this coverage." : "Recorded appearances:"}</p>{intro.archive.appearances.length > 0 && <ul className="mt-3 space-y-2 text-sm">{intro.archive.appearances.map((appearance, i) => <li key={i}>{appearance.showDate} · {appearance.title} · {appearance.outcome}</li>)}</ul>}{intro.archive.href && <Link href={intro.archive.href} className="mt-4 inline-block text-accent underline">View credited archive group</Link>}</> : <p className="mt-4 text-muted">Public archive information is unavailable.</p>}</> : <p className="mt-4 text-muted">No upcoming song is available for an introduction.</p>}
   </article><p className="mt-5 text-xs text-muted">Read at {new Date(data.source.readAt).toLocaleString()}. Refresh to update.</p>
  </>}
 </section>;
}
