"use client";
import Link from "next/link";
import { CrewWorkspaceNavigation } from "@/components/CrewWorkspaceNavigation";
import { OwnerWorkspaceNavigation } from "@/components/OwnerWorkspaceNavigation";
import type { MemberAccess } from "@/lib/member-access";
import type { CrewShowAnalytics, CrewShowSummary } from "@/lib/crew-show-analytics";
import { crewDuration, useCrewToolData } from "@/lib/crew-show-client";
const number = (value: number | null | undefined) => typeof value === "number" ? String(Math.round(value * 10) / 10) : "Unavailable";
function recordedAmount(currency: string, cents: number) {
 try { const format = new Intl.NumberFormat(undefined, { style: "currency", currency }); const places = format.resolvedOptions().maximumFractionDigits ?? 2; return format.format(cents / 10 ** places) + ` ${currency}`; }
 catch { return `${cents} recorded minor units ${currency}`; }
}
function ComparisonCard({ label, show }: { label: string; show: CrewShowSummary | null }) {
 return <article style={{minWidth:0}} className="rounded-xl border border-border p-5"><h3 className="text-sm text-muted">{label}</h3>{show ? <><p className="mt-2 text-lg font-bold">{show.title} · {show.showDate}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><dt className="text-muted">Broadcast duration</dt><dd>{crewDuration(show.broadcastSeconds)}</dd><dt className="text-muted">Finished / skipped</dt><dd>{show.finished} / {show.skipped}</dd><dt className="text-muted">Modeled music</dt><dd>{crewDuration(show.pacing?.modeledMusicSeconds)}</dd><dt className="text-muted">Directly observed music</dt><dd>{crewDuration(show.pacing?.observedMusicSeconds)}</dd><dt className="text-muted">Observed track coverage</dt><dd>{show.pacing?.observedCoveragePercent === null || !show.pacing ? "Unavailable" : `${number(show.pacing.observedCoveragePercent)}%`}</dd><dt className="text-muted">Tracks per hour</dt><dd>{number(show.pacing?.tracksPerHour)}</dd><dt className="text-muted">Average transition</dt><dd>{show.pacing?.averageTransitionSeconds === null || !show.pacing ? "Unavailable" : `${number(show.pacing.averageTransitionSeconds)}s`}</dd></dl><p className="mt-4 text-xs text-muted">Partial retained event coverage. Modeled music and recorded playback are separate measures.</p></> : <p className="mt-3 text-muted">No archived show is available.</p>}</article>;
}
export function OwnerCrewAnalytics({ access }: { access: MemberAccess }) {
 const { data, currentAccess, loading, error, refresh } = useCrewToolData<CrewShowAnalytics>(access, "insights.read", "/api/member/tools/analytics");
 const summary = data?.overview;
 return <section style={{overflowWrap:"anywhere",minWidth:0}} className="mx-auto max-w-6xl rounded-xl border border-border bg-surface p-5 sm:p-8">
  {access.access.owner ? <OwnerWorkspaceNavigation section="radio" tool="Show & community insights" /> : currentAccess && !loading && !error ? <CrewWorkspaceNavigation access={currentAccess} section="insights" /> : <Link href="/account" className="text-accent underline">Your account</Link>}
  <div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="public-kicker">BARCODE Network</p><h1 className="mt-2 text-3xl font-bold">Show & community insights</h1><p className="mt-3 text-muted">Retained public broadcasts, pacing and participation.</p></div><button type="button" onClick={() => void refresh()} disabled={loading} className="rounded-lg border border-border px-4 py-2 disabled:opacity-50">Refresh</button></div>
  {loading ? <p role="status" className="mt-6 text-muted">Checking access and current insights…</p> : error ? <p role="alert" className="mt-6 text-muted">{error}</p> : data && <>
   {summary ? <><p className="mt-6 text-sm text-muted">Retained public archive since {data.source.historyCoverageStartedAt}. Rehearsals, simulations and private shows are excluded.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Archived shows", summary.showCount], ["Submitted tracks", summary.submitted], ["Credited artist groups", summary.creditedArtistGroups], ["Repeat artist groups", summary.repeatArtistGroups]].map(([label, value]) => <div key={label} className="rounded-xl border border-border p-5"><dt className="text-sm text-muted">{label}</dt><dd className="mt-2 text-2xl font-bold">{value}</dd></div>)}</dl><p className="mt-4 text-sm text-muted">Finished {summary.finished} · Skipped {summary.skipped} · Removed {summary.removed} · Unresolved/unknown {summary.unknown}</p></> : <p role="status" className="mt-6 text-muted">Public archive insights are unavailable.</p>}
   <h2 className="mt-8 text-xl font-bold">Recent show comparison</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><ComparisonCard label="Latest archived show" show={data.comparison.latest} /><ComparisonCard label="Previous archived show" show={data.comparison.previous} /></div>
   {data.shows.length > 0 && <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="mb-3 text-left font-semibold">Retained show outcomes</caption><thead><tr className="border-b border-border text-muted"><th className="p-3">Show</th><th className="p-3">Submitted</th><th className="p-3">Finished</th><th className="p-3">Skipped</th><th className="p-3">Removed</th><th className="p-3">Unknown</th></tr></thead><tbody>{data.shows.map(show => <tr key={show.id} className="border-b border-border"><th className="p-3 font-normal">{show.showDate} · {show.title}</th><td className="p-3">{show.submitted}</td><td className="p-3">{show.finished}</td><td className="p-3">{show.skipped}</td><td className="p-3">{show.removed}</td><td className="p-3">{show.unknown}</td></tr>)}</tbody></table></div>}
   <article className="mt-6 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Credited artist groups</h2><p className="mt-2 text-sm text-muted">Counts follow existing public archive credit grouping. They are not counts of verified people or account ownership. Up to 50 groups are shown.</p>{data.artists.length > 0 ? <ul className="mt-4 grid gap-3 sm:grid-cols-2">{data.artists.map((artist, i) => <li key={i} className="rounded-lg border border-border p-3"><span className="font-semibold">{artist.label}</span><p className="mt-1 text-sm text-muted">{artist.showCount} shows · {artist.trackCount} tracks</p></li>)}</ul> : <p className="mt-4 text-muted">No credited groups are available in this coverage.</p>}</article>
   <article className="mt-6 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Account participation</h2>{data.accounts ? <><p className="mt-4">{data.accounts.total} accounts · {data.accounts.verified} verified · {data.accounts.active} not suspended · {data.accounts.suspended} suspended</p><p className="mt-2 text-sm text-muted">Current account service totals; they do not identify show viewers.</p>{data.accounts.signupsByMonth.length > 0 && <ul className="mt-4 flex flex-wrap gap-3 text-sm">{data.accounts.signupsByMonth.map(row => <li key={row.month} className="rounded-lg border border-border p-3">{row.month}: {row.count} signups</li>)}</ul>}</> : <p className="mt-4 text-muted">Account aggregates are unavailable.</p>}</article>
   {access.access.owner && data.financials && <article className="mt-6 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Recorded confirmed gross</h2>{data.financials.available ? <><p className="mt-3 text-sm text-muted">Confirmed stored payments from {data.financials.scannedShows} of {data.financials.availableShows} retained public shows, up to the 20 most recent. Partial ledger coverage; currencies are separate.</p>{data.financials.currencies.length > 0 ? <ul className="mt-4 space-y-2">{data.financials.currencies.map(total => <li key={total.currency}>{recordedAmount(total.currency, total.amountCents)} · {total.paymentCount} recorded payments</li>)}</ul> : <p className="mt-4 text-muted">No eligible confirmed payment amounts are recorded in the scanned shows.</p>}</> : <p className="mt-3 text-muted">Confirmed payment totals are unavailable.</p>}<p className="mt-4 text-sm text-muted">Refund reconciliation and net revenue are unavailable. This is not a reconciled balance.</p></article>}
   <article className="mt-6 rounded-xl border border-border p-5"><h2 className="text-lg font-bold">Coverage limits</h2><p className="mt-3 text-sm text-muted">Website visits and referral funnels: unavailable; no tracking is connected. TikTok unique viewers: unavailable. Captured BNL and TikTok engagement: unavailable in this tool&apos;s current data contract.</p><p className="mt-3 text-xs text-muted">Archive built {data.source.archiveBuiltAt ? new Date(data.source.archiveBuiltAt).toLocaleString() : "time unavailable"}. Refresh to update.</p></article>
  </>}
 </section>;
}
