/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { listPublicBallads } from "@/lib/bnl-ballads-store";
import { BalladTrackStory } from "@/components/BalladTrackStory";
export const dynamic = "force-dynamic";
export const metadata = { title: "BNL-01 · Broadcast Ballads | BARCODE Network", description: "The broadcasts, in BNL-01’s own words and sound. Original ballads from BARCODE Radio." };
export default async function BalladDiscography({ searchParams }: { searchParams: Promise<{ show?: string; q?: string }> }) {
  const { show, q = "" } = await searchParams;
  const result = await listPublicBallads().then(entries => ({ entries, unavailable: false })).catch(() => ({ entries: [], unavailable: true }));
  const { entries: all, unavailable } = result;
  const entries = all.filter(entry => (!show || entry.show.sessionId === show) && `${entry.version.title} ${entry.show.title} ${entry.version.style} ${JSON.stringify(entry.version.palette)} ${Object.values(entry.linerNotes).join(" ")}`.toLowerCase().includes(q.toLowerCase()));
  return <main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-28 sm:px-6">
    <div className="mb-10 border-b border-border pb-8"><p className="text-xs font-bold uppercase tracking-[0.35em] text-accent">Written by BNL-01</p><h1 className="mt-4 text-4xl font-black tracking-tight text-foreground sm:text-6xl">Broadcast Ballads</h1><p className="mt-4 max-w-xl text-sm leading-relaxed text-muted">Every broadcast leaves something behind. BNL turns it into a song.</p><Link href="/radio/archive" className="mt-5 inline-block text-xs text-accent">Explore the Broadcast Archive ↗</Link></div>
    <form className="mb-8 flex gap-2"><label className="sr-only" htmlFor="ballad-search">Search songs, people, topics and styles</label><input id="ballad-search" name="q" defaultValue={q} placeholder="Find a ballad, person, topic or sound…" className="min-w-0 flex-1 rounded border border-border bg-background px-4 py-3 text-sm text-foreground" /><button className="rounded border border-accent px-5 text-xs font-bold text-accent">Search</button>{show && <Link className="self-center text-xs text-accent" href="/radio/ballads">All ballads</Link>}</form>
    <div className="space-y-8">{entries.map(entry => <article key={entry.show.sessionId} className="overflow-hidden rounded-lg border border-border bg-surface">
      <div className="grid gap-6 p-6 md:grid-cols-[160px_1fr]">
        <div className="aspect-square overflow-hidden rounded border border-border bg-accent/5">{entry.presentation.artworkUrl ? <img src={entry.presentation.artworkUrl} alt={`Cover for ${entry.version.title}`} className="h-full w-full object-cover" /> : <div className="flex h-full flex-col items-center justify-center p-4 text-center"><span className="text-3xl font-black text-accent">BNL-01</span><span className="mt-3 text-[10px] uppercase tracking-[0.3em] text-muted">Broadcast Ballads</span><span className="mt-5 text-xs text-muted">{entry.show.showDate}</span></div>}</div>
        <div className="min-w-0"><p className="text-xs uppercase tracking-widest text-muted">{entry.show.title}</p><h2 className="mt-2 text-2xl font-bold text-foreground">BNL-01 — {entry.version.title}</h2><audio className="mt-5 w-full" controls preload="none" src={`/api/ballads/media?showId=${encodeURIComponent(entry.show.sessionId)}&audioId=${encodeURIComponent(entry.audioId)}`} /><p className="mt-4 text-xs leading-relaxed text-muted">{entry.presentation.credits}</p><div className="mt-4 flex gap-5 text-xs text-accent"><Link href={`/radio/archive?view=shows&show=${encodeURIComponent(entry.show.sessionId)}`}>Explore this broadcast ↗</Link>{entry.presentation.sunoUrl && <a href={entry.presentation.sunoUrl} target="_blank" rel="noopener noreferrer">Listen on Suno ↗</a>}</div></div>
      </div>
      <BalladTrackStory notes={entry.linerNotes} />
      <div className="grid gap-4 border-t border-border p-6 md:grid-cols-2"><details><summary className="cursor-pointer text-sm font-bold text-foreground">Lyrics</summary><p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-muted">{entry.version.lyrics}</p></details><div className="space-y-4"><details><summary className="cursor-pointer text-sm font-bold text-foreground">The sound & Style prompt</summary><p className="mt-4 text-sm leading-relaxed text-muted">{entry.version.style}</p>{Object.entries(entry.version.palette).filter(([, value]) => value).map(([key, value]) => <p key={key} className="mt-3 text-xs text-muted"><span className="font-bold capitalize text-foreground">{key}: </span>{value}</p>)}{entry.presentation.sunoModel && <p className="mt-3 text-xs text-muted">Suno model: {entry.presentation.sunoModel}</p>}{entry.presentation.sunoSettings && <p className="mt-3 text-xs text-muted">{entry.presentation.sunoSettings}</p>}</details><p className="text-xs text-muted">An original creative interpretation by BNL-01.</p></div></div>
    </article>)}</div>
    {!entries.length && <p className="rounded border border-border p-8 text-sm text-muted">{unavailable ? "The discography is temporarily unavailable. Please try again shortly." : show ? "No ballad has been released for this broadcast yet." : q ? "No ballads match that search." : "BNL’s first Broadcast Ballad is on its way. Released songs will appear here."}</p>}
  </main>;
}
